<div class="col-12">
  <div class="row">
    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title"><?= LABEL_SENSOR_GRAPHS ?></li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'simulate_sensor_measure', 'action' => 'default_graph'],
          [
            'label' => LABEL_GRAPH,
            'class' => 'nav-link',
            'selected_controller' => 'simulate_sensor_measure',
            'selected_action' => 'graph',
            'http_params' => ['sensor_id' => $this->sensor->value['id']]
          ])
          ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'simulate_sensor_measure', 'action' => 'default_list'],
          [
            'label' => LABEL_LIST,
            'class' => 'nav-link',
            'selected_controller' => 'simulate_sensor_measure',
            'selected_action' => 'list',
            'http_params' => ['sensor_id' => $this->sensor->value['id']
          ]
          ])
          ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkJs(
          [
            'label' => LABEL_RTKS,
            'class' => 'pw-click nav-link',
            'pw-controller' => 'simulate_sensor',
            'pw-action' => 'open_rtk',
            'sensor_id' => $this->sensor->value['id']
          ])
          ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkJs(
          [
            'label' => LABEL_FILTERS,
            'class' => 'pw-click nav-link',
            'pw-controller' => 'simulate_sensor',
            'pw-action' => 'open_filter',
            'sensor_id' => $this->sensor->value['id']
          ])
          ?>
        </li>
      </ul>
    </nav>

  </div>
</div>