
<table class="table">
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$values['attribute'][$view_item['attribute_id']]['name']]): ?>

<? if ($view_item['form_type'] == 'hidden'): ?>
<? else: ?>
    <tr>
      <th><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></th>
      <td>
<? if ($view_item['form_type'] == 'textarea'): ?>
          <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formTextarea('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? elseif ($view_item['form_type'] == 'select'): ?>
          <? Tag::init()->formSelect($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
<? elseif ($view_item['form_type'] == 'checkbox'): ?>
          <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formCheckbox('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? elseif ($view_item['form_type'] == 'radio'): ?>
          <? Tag::init()->formRadio($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
<? elseif ($view_item['form_type'] == 'password'): ?>
          <? Tag::init()->formPassword($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]) ?>
<? else: ?>
          <? Tag::init()->formInput($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]) ?>
<? endif ?>
<? if ($view_item['note']): ?>
          <span class="text-danger"><?= $view_item['note'] ?></span>
<? endif ?>

      </td>
    </tr>
<? endif ?>

<? endif ?>
<? endforeach ?>
</table>

<? foreach ($values['view']['view_item'] as $view_item): ?>
  <? if ($view_item['form_type'] == 'hidden'): ?>
    <?= Tag::init()->hidden($view_item, $values['model'], $values['attribute']) ?>
  <? endif ?>
<? endforeach ?>
