<? foreach ($values['view']['view_item'] as $view_item): ?>
<div class="form-group row">
<? if (!Model::$required_columns[$values['attribute'][$view_item['attribute_id']]['name']]): ?>
<? if ($view_item['form_type'] == 'hidden'): ?>
<? else: ?>

      <label class="<?= View::formLabelClass($values['view']) ?>" for="<?= $values['attribute'][$view_item['attribute_id']]['name'] ?>"><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></label>
<? if ($view_item['form_type'] == 'textarea'): ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formTextarea('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? elseif ($view_item['form_type'] == 'select'): ?>
        <? Tag::init()->formSelect($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
<? elseif ($view_item['form_type'] == 'checkbox'): ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formCheckbox('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? elseif ($view_item['form_type'] == 'radio'): ?>
        <? Tag::init()->formRadio($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
<? elseif ($view_item['form_type'] == 'password'): ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formPassword('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? else: ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formInput('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
<? endif ?>

<? endif ?>
<? endif ?>
<? if ($view_item['note']): ?>
<span class="text-danger"><?= $view_item['note'] ?></span>
<? endif ?>
</div>
<? endforeach ?>

  <? Tag::init()->php('FormHelper::submit(LABEL_SAVE)') ?>

  <? Tag::init()->php('FormHelper::linkButton("cancel", LABEL_BACK)') ?>
  
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if ($view_item['form_type'] == 'hidden'): ?>
  <input type="hidden" name="<?= $values['model']['entity_name'] ?>[<?= $values['attribute'][$view_item['attribute_id']]['name'] ?>]" value="<?= ViewItem::hiddenValue($view_item) ?>">
<? endif ?>
<? endforeach ?>
