
<?php foreach ($values['view']['view_item'] as $view_item): ?>
<?php if (!PwModel::$required_columns[$values['attribute'][$view_item['attribute_id']]['name']]): ?>

<?php if ($view_item['form_type'] == 'hidden'): ?>
<? else: ?>
<div class="form-group row">
  <label class="<?= View::formLabelClass($values['view']) ?>" for="<?= $values['attribute'][$view_item['attribute_id']]['name'] ?>"><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></label>
  <?php if ($view_item['form_type'] == 'textarea'): ?>
  <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formTextarea('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
  <? elseif ($view_item['form_type'] == 'select'): ?>
  <? Tag::init()->formSelect($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
  <? elseif ($view_item['form_type'] == 'checkbox'): ?>
  <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formCheckbox('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
  <? elseif ($view_item['form_type'] == 'radio'): ?>
  <? Tag::init()->formRadio($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]); ?>
  <? elseif ($view_item['form_type'] == 'password'): ?>
  <? Tag::init()->formPassword($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]) ?>
  <? elseif ($view_item['form_type'] == 'selectdate'): ?>
  <? Tag::init()->formSelectDate($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]) ?>
  <? else: ?>
  <? Tag::init()->formInput($view_item, $values['model'], $values['attribute'][$view_item['attribute_id']]) ?>
  <?php endif ?>
  <?php if ($view_item['note']): ?>
  <span class="text-danger"><?= $view_item['note'] ?></span>
  <?php endif ?>

</div>
<?php endif ?>


<?php endif ?>
<?php endforeach ?>


<?php foreach ($values['view']['view_item'] as $view_item): ?>
<?php if ($view_item['form_type'] == 'hidden'): ?>
<?= Tag::init()->hidden($view_item, $values['model'], $values['attribute']) ?>
<?php endif ?>
<?php endforeach ?>
