<?= "<? include('_header.phtml') ?>" ?>

<? if ($values['view']['note']): ?>
  <div class="text-danger">
    <?= nl2br($values['view']['note']) ?>
  </div>
<? endif ?>

<div class="pt-3">
  <? Tag::init()->php('FormHelper::linkButton(\'new\', null, [\'label\' => LABEL_ADD, \'class\' => \'btn btn-primary\'] )') ?>

  <? Tag::init()->sortbleLink() ?>

</div>

<table id="list-table" class="table">
  <thead class="thead-deffault">
    <tr>
      <th>&nbsp;</th>
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['name']]): ?>
<? if ($view_item['attribute_id']): ?>
      <th><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></th>
      <? else: ?>
      <th></th>
<? endif ?>
<? endif ?>
<? endforeach ?>
    </tr>
  </thead>

  <? Tag::init()->ifs('$this->'.$values['model']['entity_name'].'->values') ?>
  <? Tag::init()->foreachs('$this->'.$values['model']['entity_name'].'->values as $values') ?>
  <tr id="<?= Tag::init()->valuesId() ?>">
    <td><? Tag::init()->php('FormHelper::linkButton(\'edit\', $values[\'id\'], [\'label\' => LABEL_EDIT])') ?></td>
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['name']]): ?>
<? if ($view_item['page_id']): ?>
    <td><? Tag::init()->tableItemUrlForAttribute ($values['attribute'][$view_item['attribute_id']], $values['pages'][$view_item['page_id']], $values['model'], $view_item) ?></td>
<? else: ?>
    <td><? Tag::init()->tableItemForAttribute($values['attribute'][$view_item['attribute_id']], $view_item) ?></td>
<? endif ?>
<? endif ?>
<? endforeach ?>
  </tr>
  <? Tag::init()->foreache() ?>
  <? Tag::init()->ife() ?>

</table>