<?= "<? include('_header.phtml') ?>" ?>


<div class="pt-3">
  <? Tag::init()->php('FormHelper::linkButton(\'new\', LABEL_ADD, null, [\'class\' => \'btn btn-primary\'])') ?>

  <? Tag::init()->php('FormHelper::linkButton(\'sort_order\', LABEL_SORT_ORDER)') ?>

</div>

<table class="table">
  <thead class="thead-deffault">
    <tr>
      <th>&nbsp;</th>
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['name']]): ?>
      <th><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></th>
<? endif ?>
<? endforeach ?>
    </tr>
  </thead>

  <? Tag::init()->ifs('$this->'.$values['model']['entity_name'].'->values') ?>
  <? Tag::init()->foreachs('$this->'.$values['model']['entity_name'].'->values as $values') ?>
  <tr>
    <td><? Tag::init()->php('FormHelper::linkButton(\'edit\', LABEL_EDIT, $values[\'id\'])') ?></td>
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['name']]): ?>
<? if ($view_item['page_id']): ?>
    <td>
      <? Tag::init()->tableItemUrlForAttribute(
          $values['attribute'][$view_item['attribute_id']],
          $values['pages'][$view_item['page_id']],
          $values['model']
      ) ?>
    </td>
<? else: ?>
    <td><? Tag::init()->tableItemForAttribute($values['attribute'][$view_item['attribute_id']]) ?></td>
<? endif ?>
<? endif ?>
<? endforeach ?>
  </tr>
  <? Tag::init()->foreache() ?>
  <? Tag::init()->ife() ?>

</table>
