<?= "<? include('_header.phtml') ?>" ?>

<form action="<? Tag::init()->php('url_for(\'add\')') ?>" method="post">

  <table class="table">
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['attribute_id']]): ?>
    <tr>
      <th><?= $view_item['label'] ?></th>
      <td><? Tag::init()->php('$this->'.$values['model']['entity_name']."->formInput('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?></td>
    </tr>
<? endif ?>
<? endforeach ?>
  </table>

  <? Tag::init()->php('FormHelper::submit(LABEL_SAVE)') ?>
  <? Tag::init()->php('FormHelper::linkButton("cancel", LABEL_BACK)') ?>
</form>