<?= "<? include('_header.phtml') ?>" ?>

<form action="<? Tag::init()->php('url_for(\'add\')') ?>" method="post">

  <table class="table">
<? foreach ($values['view']['view_item'] as $view_item): ?>
<? if (!Model::$required_columns[$view_item['attribute_id']]): ?>
    <? if ($view_item['form_type'] == 'hidden'): ?>
    <? else: ?>

    <tr>
      <th><?= Attribute::labelName($values['model'], $values['attribute'][$view_item['attribute_id']]) ?></th>
      <td>
        <? if ($view_item['form_type'] == 'textarea'): ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formTextarea('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
        <? else: ?>
        <? Tag::init()->php('$this->'.$values['model']['entity_name']."->formInput('{$values['attribute'][$view_item['attribute_id']]['name']}')") ?>
        <? endif ?>

      </td>
    </tr>

    <? endif ?>
<? endif ?>
<? endforeach ?>

  </table>

<? foreach ($values['view']['view_item'] as $view_item): ?>
  <? if ($view_item['form_type'] == 'hidden'): ?>
    <input type="hidden" name="<?= $values['attribute'][$view_item['attribute_id']]['name'] ?>" value="<?= ViewItem::hiddenValue($view_item) ?>">
  <? endif ?>
<? endforeach ?>

  <? Tag::init()->php('FormHelper::submit(LABEL_SAVE)') ?>
  <? Tag::init()->php('FormHelper::linkButton("cancel", LABEL_BACK)') ?>
</form>