<? if ($this->errors): ?>

  <div class="modal error-window">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Error</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul>
            <? if(is_array($this->errors)): ?>
              <? foreach ($this->errors as $model => $error): ?>
                <? foreach ($error as $key2 => $value): ?>
                  <li><?= ErrorMessage::display($value, $this->pw_params, $model)?></li>
                <? endforeach?>
              <? endforeach?>
            <? endif ?>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
        </div>
      </div>
    </div>
  </div>

<script type="text/javascript">
  $('.error-window').modal();
</script>
<? endif ?>