<form action="<?= $this->urlSelfFor('delete') ?>" method="post">
  <div class="modal delete-window">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
         <h5 id="from-delete-title"></h5> 
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 class="modal-title"><?= MESSAGE_DELETE ?></h5>
      </div>
      <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
        <input id="from-delete-id" type="hidden" name="id" value="">
        <input id="from-delete-id" type="hidden" name="pw_sid" value="<?= $this->pw_sid ?>">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>

      </div>
    </div>
  </div>
</form>
