<div id="graph_control_window" class="modal col-6">
  <div class="card">
    <div class="card-header">
      <h1><?= LABEL_SETTING ?></h1>
    </div>
    <div class="card-block">
  <? foreach ($this->graph_settings as $key => $graph_setting): ?>
      <div class="container">
        <h2><?= $graph_setting['label'] ?></h2>
        <div class="">
          <?= PwForm::select(
            [
              'name' => 'autoscale_types[]',
              'csv' => 'autoscale_type',
              'element_type' => $graph_setting['element_type'],
            ]
            , $graph_setting['autoscale_type']) ?>
            <?= LABEL_UPPER_LIMIT ?>
          <input class="form-control number col-2" type="number" name="upper_limits[]" value="<?= $graph_setting['upper_limit'] ?>" element_type="<?= $graph_setting['element_type'] ?>">
            <?= LABEL_LOWER_LIMIT ?>
          <input class="form-control number col-2" type="number" name="lower_limits[]" value="<?= $graph_setting['lower_limit'] ?>" element_type="<?= $graph_setting['element_type'] ?>">
        </div>
      </div>
  <? endforeach ?>
    </div>
    <div class="control-area">
      <div class="text-right">
        <input type="submit" class="pw-click btn btn-primary btn-close" pw-controller="<?= $this->jsControllerName() ?>" pw-action="js_graph" value="<?= LABEL_RELOAD ?>" target-window="graph_control_window">
        <a class="btn btn-outline-primary btn-close" target-window="graph_control_window"><?= LABEL_CLOSE ?></a>
      </div>
    </div>
  </div>
</div>

<? include('views/components/graph_control.phtml') ?>