<?php if ($this->page->value['id']): ?>
<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
  <span>Page</span>
  <a class="d-flex align-items-center text-muted" href="#"><span data-feather="plus-circle"></span></a>
</h6>
<ul class="nav flex-column mb-2">
  <li class="nav-item">
    <?= $this->linkTo(['controller' => 'view'],
                      [
                      'label' => 'View',
                      'class' => 'nav-link',
                      'icon_name' => 'table',
                      'http_params' => ['page_id' => $this->page->value['id']]
                    ]
                    ) ?>
  </li>
  <li class="nav-item">
    <?= $this->linkTo(['controller' => 'route'],
                      [
                      'label' => 'Route',
                      'class' => 'nav-link',
                      'icon_name' => 'road',
                      'http_params' => ['page_id' => $this->page->value['id']]
                    ]
                    ) ?>
  </li>
  <li class="nav-item">
    <?= $this->linkTo(['controller' => 'page_model'],
                      [
                      'label' => 'Request',
                      'class' => 'nav-link',
                      'icon_name' => 'handshake',
                      'http_params' => ['page_id' => $this->page->value['id']]
                    ]
                    ) ?>
  </li>
</ul>
<?php endif ?>