<div id="php-page-export-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:50rem; margin-left: -10rem;">

      <div class="modal-header">
        <h4>
          <?= $this->project->value['name'] ?>
          >
        <?= $this->page->value['name'] ?>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <? if (is_array($this->user_project_setting->values)): ?>
        <table class="table">
          <? foreach ($this->user_project_setting->values as $user_project_setting): ?>
          <tr>
            <td>
              <?= $user_project_setting['project_path'] ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>
              <label class="badge badge-success">exists</label>
              <? else: ?>
              <label class="badge badge-danger">not found php-work</label>
              <? endif ?>
              <? else: ?>
              <label class="badge badge-danger">not exists</label>
              <? endif ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>

              <div class="form-inline">
                <? if ($this->page->value): ?>
                <form action="<?= $this->urlFor(['controller' => 'page', 'action' => 'artisan']) ?>" method="post">
                  <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you run artisan make controller?">artisan controller</button>
                  <input type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
                  <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                </form>

                <form action="<?= $this->urlFor(['controller' => 'route', 'action' => 'export_route']) ?>" method="post">
                  <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export route?">export route</button>
                  <input type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
                  <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                </form>
                <? endif ?>

                <? if ($this->model->value): ?>
                <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'export_php_model']) ?>" method="post">
                  <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export PHP model?">PHP Model</button>
                  <input type="hidden" name="model_id" value="<?= $this->model->value['id'] ?>">
                  <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                </form>

                <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'export_python_model']) ?>" method="post">
                  <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export Python model?">Python Model</button>
                  <input type="hidden" name="model_id" value="<?= $this->model->value['id'] ?>">
                  <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                </form>

                <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'export_laravel_model']) ?>" method="post">
                  <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export Laravel model?">Laravel Model</button>
                  <input type="hidden" name="model_id" value="<?= $this->model->value['id'] ?>">
                  <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                </form>
                <? endif ?>

                <? if ($this->page->value): ?>
                <div>
                  <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'export_php_page']) ?>" method="post">
                    <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export PHP controller files?">Controller/View</button>
                    <input type="hidden" name="project_id" value="<?= $this->project->value['id'] ?>">
                    <input type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
                    <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
                    <input type="checkbox" name="is_overwrite" value="1"> overwrite
                  </form>
                </div>
                <? endif ?>
                <div>
                  <?= $this->linkTo(
                    [
                    'controller' => 'localize_string',
                    'action' => 'import_from_model'
                    ],
                    [
                    'label' => 'Localize',
                    'class' => 'btn btn-sm btn-primary',
                    'http_params' => [
                            'model_id' => $this->model->value['id'],
                            'user_project_setting_id' => $user_project_setting['id'],
                            'redirect' => 'attribute/list'
                            ]
                    ]
                    )
                  ?>
                </div>
              </div>

              <? endif ?>
              <? endif ?>
            </td>
          </tr>

          <? if (file_exists($user_project_setting['project_path'])): ?>
          <? if (!file_exists($user_project_setting['project_path']."app/")): ?>
          <tr>
            <td>
              <small class="text-danger">
                <?= UserProjectSetting::gitCloneCommand($user_project_setting) ?>
              </small>
            </td>
            <td></td>
          </tr>
          <? endif ?>
          <? endif ?>
          <? endforeach ?>

        </table>
        <? else: ?>
        <?= $this->linkTo(
          ['controller' => 'project', 'action' => 'export_list', 'id' => $this->project->value['id']],
          [
          'label' => LABEL_EXPORT.LABEL_SETTING
          ]
          ) ?>
        <? endif ?>

      </div>
    </div>
  </div>
</div>