<div id="php-export-window" class="pw-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:50rem; margin-left: -10rem;">

      <div class="modal-header">
        <h5 class="modal-title">PHP Export : <?= $this->project->value['name'] ?></h5>
        <button type="button" class="close pw-modal-close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <? if (is_array($this->user_project_setting->values)): ?>
        <div>
          <input id="is_overwrite" type="checkbox" name="is_overwrite"> overwrite
          <input id="project_id" type="hidden" name="project_id" value="<?= $this->project->value['id'] ?>">
        </div>
        <table class="table">
          <? foreach ($this->user_project_setting->values as $user_project_setting): ?>
          <tr>
            <td>
              <?= $user_project_setting['project_path'] ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>
              <label class="badge badge-success">exists</label>
              <? else: ?>
              <label class="badge badge-danger">not found php-work</label>
              <? endif ?>
              <? else: ?>
              <label class="badge badge-danger">not exists</label>
              <? endif ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>

              <div class="form-inline">
                <?= $this->linkJs(
                  [
                  'label' => 'All Files',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_all',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export all files?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'PHP models',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_php_models',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export PHP models?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'PHP pages',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_php_controller_view',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export PHP Controller and View files?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'SQL',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_php_controller_view',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export SQL?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'PHP Localize',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_php_localize',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export PHP Localize files?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'CSV',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_csv',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export CSV files?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Python Model',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_python_models',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export Python model files?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Laravel Model',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_laravel_models',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export Laravel model files?'
                   ]
                ) ?>

              <? endif ?>
              <? endif ?>
            </td>
          </tr>

          <? if (file_exists($user_project_setting['project_path'])): ?>
          <? if (!file_exists($user_project_setting['project_path']."app/")): ?>
          <tr>
            <td>
              <small class="text-danger">
                <?= UserProjectSetting::gitCloneCommand($user_project_setting) ?></small>
            </td>
            <td></td>
          </tr>
          <? endif ?>
          <? endif ?>
          <? endforeach ?>

        </table>
        <? else: ?>
        <?= PwForm::linkButton(
                [
                'controller' => 'user_project_setting',
                'action' => 'list',
                'project_id' => $this->project->value['id']
                ],
                ['label' => LABEL_EXPORT.LABEL_SETTING]
                ) ?>
        <? endif ?>

      </div>
    </div>
  </div>
</div>