
<div id="php-page-export-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:50rem; margin-left: -10rem;">

      <div class="modal-header">
        <h5 class="modal-title">PHP Export</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="alert alert-success">
         <p>
           if you export php models, need download PHP Framework 'php-work'.
         </p>
         <a class="btn btn-primary" href="<?= PHP_WORK_GIT_URL ?>" target="_blank">Download php-work(GitHub)</a>
       </div>
       <h4><?= $this->project->value['name'] ?></h4>
       <h5><?= $this->page->value['name'] ?></h5>
       <? if (is_array($this->user_project_setting->values)): ?>
       <table class="table">
        <? foreach ($this->user_project_setting->values as $user_project_setting): ?>
        <tr>
          <td>
            <?= $user_project_setting['project_path'] ?>
          </td>
          <td>
            <? if (file_exists($user_project_setting['project_path'])): ?>
            <? if (file_exists($user_project_setting['project_path']."app/")): ?>
            <label class="badge badge-success">exists</label>
          <? else: ?>
          <label class="badge badge-danger">not found php-work</label>
        <? endif ?>
      <? else: ?>
      <label class="badge badge-danger">not exists</label>
    <? endif ?>
  </td>
  <td>
    <? if (file_exists($user_project_setting['project_path'])): ?>
    <? if (file_exists($user_project_setting['project_path']."app/")): ?>

      <div class="form-inline">

        <form action="<?=url_for('project/export_php_page') ?>" method="post">
          <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export PHP files?">Controller/View</button>
          <div>
          <input type="checkbox" name="is_overwrite" value="1"> overwrite
          </div>
          <input type="hidden" name="project_id" value="<?= $this->project->value['id'] ?>">
          <input type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
          <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
        </form>

      </div>
  <? endif ?>
<? endif ?>
</td>
</tr>

<? if (file_exists($user_project_setting['project_path'])): ?>
<? if (!file_exists($user_project_setting['project_path']."app/")): ?>
<tr>
  <td>
    <small class="text-danger"><?= UserProjectSetting::gitCloneCommand($user_project_setting) ?></small>
  </td>
  <td></td>
</tr>
<? endif ?>
<? endif ?>
<? endforeach ?>

</table>
<? else: ?>
<?= FormHelper::linkButton('project/export_list', LABEL_EXPORT.LABEL_SETTING, $this->project->value['id']) ?>
<? endif ?>

</div>
</div>
</div>
</div>
