<div id="php-page-export-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:50rem; margin-left: -10rem;">

      <div class="modal-header">
        <h4>
          <?= $this->project->value['name'] ?>
          >
        <?= $this->page->value['name'] ?>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div>
          <input id="is_overwrite" type="checkbox" name="is_overwrite"> overwrite
          <input id="project_id" type="hidden" name="project_id" value="<?= $this->project->value['id'] ?>">
          <input id="page_id" type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
        </div>
        <? if (is_array($this->user_project_setting->values)): ?>
        <table class="table">
          <? foreach ($this->user_project_setting->values as $user_project_setting): ?>
          <tr>
            <td>
              <?= $user_project_setting['project_path'] ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>
              <label class="badge badge-success">exists</label>
              <? else: ?>
              <label class="badge badge-danger">not found php-work</label>
              <? endif ?>
              <? else: ?>
              <label class="badge badge-danger">not exists</label>
              <? endif ?>
            </td>
            <td>
              <? if (file_exists($user_project_setting['project_path'])): ?>
              <? if (file_exists($user_project_setting['project_path']."app/")): ?>

              <div class="form-inline">
                <? if ($this->model->value): ?>
                <?= $this->linkJs(
                  [
                  'label' => 'PHP Model',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_php_model',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export PHP model file?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Python Model',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_python_model',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'message' => 'Do you export Python model file?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Laravel Model',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_laravel_model',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'model_id' => $this->model->value['id'],
                  'message' => 'Do you export Laravel model file?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Laravel Controller',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_laravel_cotroller',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'model_id' => $this->model->value['id'],
                  'message' => 'Do you export Laravel Controller file?'
                   ]
                ) ?>

                <?= $this->linkJs(
                  [
                  'label' => 'Laravel Blade',
                  'class' => 'btn btn-primary btn-sm',
                  'pw-on-click' => 'export_php',
                  'pw-controller' => 'project',
                  'api-action' => 'export_laravel_blade',
                  'user_project_setting_id' => $user_project_setting['id'],
                  'model_id' => $this->model->value['id'],
                  'message' => 'Do you export Laravel Blade file?'
                   ]
                ) ?>

                <? endif ?>

                <? if ($this->page->value): ?>
                <? endif ?>
                <div>
                  <?= $this->linkJs(
                      [
                      'label' => 'PHP Page',
                      'class' => 'btn btn-primary btn-sm',
                      'pw-on-click' => 'export_php',
                      'pw-controller' => 'project',
                      'api-action' => 'export_php_page',
                      'user_project_setting_id' => $user_project_setting['id'],
                      'message' => 'Do you export Controller & View File?'
                       ]
                    ) ?>
                  <?= $this->linkTo(
                    [
                    'controller' => 'localize_string',
                    'action' => 'import_from_model'
                    ],
                    [
                    'label' => 'Localize',
                    'class' => 'btn btn-sm btn-primary',
                    'http_params' => [
                            'model_id' => $this->model->value['id'],
                            'user_project_setting_id' => $user_project_setting['id'],
                            'redirect' => 'attribute/list'
                            ]
                    ]
                    )
                  ?>
                </div>
              </div>

              <? endif ?>
              <? endif ?>
            </td>
          </tr>

          <? if (file_exists($user_project_setting['project_path'])): ?>
          <? if (!file_exists($user_project_setting['project_path']."app/")): ?>
          <tr>
            <td>
              <small class="text-danger">
                <?= UserProjectSetting::gitCloneCommand($user_project_setting) ?>
              </small>
            </td>
            <td></td>
          </tr>
          <? endif ?>
          <? endif ?>
          <? endforeach ?>

        </table>
        <? else: ?>
        <?= $this->linkTo(
          ['controller' => 'user_project_setting', 'action' => 'list', 'project_id' => $this->project->value['id']],
          [
          'label' => LABEL_EXPORT.LABEL_SETTING
          ]
          ) ?>
        <? endif ?>

      </div>
    </div>
  </div>
</div>