<div class="php_error">
  <div class="card">

    <div class="card-block">
      <table class="table">
      <?php foreach ($errors as $key => $error) : ?>
      <?php if ($key == 'request') : ?>
        <tr>
          <th><?= $key ?></th>
          <td>
            <dl>
        <?php foreach ($error as $param_key => $param) : ?>
            <dt><?= $key ?></dt>
            <dd><?= $param ?></dd>
        <?php endforeach ?>
            </dl>
          </td>
        </tr>
      <?php else : ?>
        <tr>
          <th><?= $key ?></th>
          <td><?= $error ?></td>
        </tr>
      <?php endif ?>
      <?php endforeach ?>
      </table>
    </div>

  </div>
</div>
