<? if ($this->project->value['id']): ?>

<div class="row">

  <div class="col-5">
    <table class="table">
      <tr>
        <th>Project</th>
        <td><?= $this->project->value['name'] ?></td>
        <td><?= FormHelper::linkModal('#php-export-window', 'PHP Export', ['class' => 'btn btn-sm btn-success']) ?></td>
      </tr>
    </table>
  </div>

  <div class="col-5">
    <table class="table">
      <tr>
        <th>Database</th>
        <td><?= $this->database->value['name'] ?></td>
        <td><?= FormHelper::linkButton('project/export_db', 'DB Export (Excel)', null, ['class' => 'btn btn-sm btn-success confirm-dialog']) ?></td>
      </tr>
    </table>
  </div>

</div>

<? include('php_export_window.phtml') ?>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <ul class="nav nav-pills">
    <li class="nav-item"><a class="nav-link <?= cssClass('page', $this->params['controller'], 'active'); ?>" href="<?= url_for('page/list', array('project_id' => $this->project->value['id'])) ?>">Page</a></li>
    <li class="nav-item"><a class="nav-link <?= cssClass('model', $this->params['controller'], 'active'); ?>" href="<?= url_for('model/list', array('project_id' => $this->project->value['id'])) ?>">Model</a></li>
  </ul>
</nav>

<? endif ?>
