<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <h2>Project Manager</h2>
  <div class="sidebar-sticky">

    <ul class="nav flex-column">
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'project'], [ 'label' => 'Project', 'class' => 'nav-link', 'icon_name' => 'home' ]) ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'database'], [ 'label' => 'Database', 'class' => 'nav-link', 'icon_name' => 'database' ]) ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'user'], [ 'label' => 'User', 'class' => 'nav-link', 'icon_name' => 'users' ]) ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'setting'], [ 'label' => 'Setting', 'class' => 'nav-link', 'icon_name' => 'cog' ]) ?>
      </li>
    </ul>

    <? include('views/components/project_nav.phtml') ?>

    <? include('views/components/page_nav.phtml') ?>
  </div>
</nav>