
<a href="#" class="btn btn-outline-primary change-sortable" table_id="sortable-table"><?= TagHelper::iconTag('sort') ?><?= LABEL_SORT_ORDER ?></a>
<a href="#" class="btn btn-primary update-sortable" pw-controller="<?= $this->name ?>" pw-action='update_sort'><?= TagHelper::iconTag('save') ?><?= LABEL_UPDATE ?></a>
<a href="#" class="btn btn-outline-primary close-sortable"><?= TagHelper::iconTag('times') ?><?= LABEL_CLOSE ?></a>