<div id="sql-export-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:50rem; margin-left: -10rem;">

      <div class="modal-header">
        <h5 class="modal-title">SQL Export from models</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="alert alert-success">
          <p>
            if you export sql from models, need download PHP Framework 'php-work'.
          </p>
          <a class="btn btn-primary" href="<?= PHP_WORK_GIT_URL ?>" target="_blank">Download php-work(GitHub)</a>
        </div>
        <h5>
          <?= $this->project->value['name'] ?>
        </h5>
        <?php if (is_array($this->user_project_setting->values)): ?>
        <table class="table">
          <?php foreach ($this->user_project_setting->values as $user_project_setting): ?>
          <tr>
            <td>
              <?= $user_project_setting['project_path'] ?>
            </td>
            <td>
              <?php if (file_exists($user_project_setting['project_path'])): ?>
              <?php if (file_exists($user_project_setting['project_path']."app/")): ?>
              <label class="badge badge-success">exists</label>
              <? else: ?>
              <label class="badge badge-danger">not found php-work</label>
              <?php endif ?>
              <? else: ?>
              <label class="badge badge-danger">not exists</label>
              <?php endif ?>
            </td>
            <td>
              <?php if (file_exists($user_project_setting['project_path'])): ?>
              <?php if (file_exists($user_project_setting['project_path']."app/")): ?>
              <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'export_sql_from_models']) ?>" method="post">
                <button class="btn btn-sm btn-primary confirm-dialog" href="#" message="Do you export SQL from models?">
                  <?= LABEL_EXPORT ?></button>
                <input type="hidden" name="project_id" value="<?= $this->project->value['id'] ?>">
                <input type="hidden" name="user_project_setting_id" value="<?= $user_project_setting['id'] ?>">
              </form>
              <?php endif ?>
              <?php endif ?>
            </td>
          </tr>

          <?php if (file_exists($user_project_setting['project_path'])): ?>
          <?php if (!file_exists($user_project_setting['project_path']."app/")): ?>
          <tr>
            <td>
              <small class="text-danger">
                <?= UserProjectSetting::gitCloneCommand($user_project_setting) ?></small>
            </td>
            <td></td>
          </tr>
          <?php endif ?>
          <?php endif ?>
          <?php endforeach ?>

        </table>
        <? else: ?>
        <?= PwForm::linkButton(
              [
              'controller' => 'project',
              'action' => 'export_list',
              'id' => $this->project->value['id']
              ],
              ['label' => LABEL_EXPORT.LABEL_SETTING]
              ) ?>
        <?php endif ?>

      </div>
    </div>
  </div>
</div>