
<h2 id="table-list">Table</h2>
<div class="database-index">
  <?= count($this->pg_classes) ?> tables
  <a href="#" class="change-show-all-table">show all</a>
  <a href="#" class="change-hide-all-table">hide all</a>
  <table class="table">
    <? foreach ($this->pg_classes as $pg_class): ?>
      <tr>
        <td><input type="checkbox" name="check_<?= $pg_class['pg_class_id'] ?>" class="change-show-table" rel="<?= $pg_class['pg_class_id'] ?>"></td>
        <td><a href="#<?= $pg_class['pg_class_id'] ?>"><?= $pg_class['tablename'] ?></a></td>
        <td><?= $pg_class['comment'] ?></td>
      </tr>
    <? endforeach ?>
  </table>

  <a class="change-list-col" target-class=".db-table" data="1" href="#"><i class="fa fa-list"></i></a>
  <a class="change-list-col" target-class=".db-table" data="2" href="#"><i class="fa fa-th"></i></a>
</div>

<? if ($this->pg_classes): ?>
  <div class="row db-list"">
    <? foreach ($this->pg_classes as $pg_class): ?>
      <div id="<?= $pg_class['pg_class_id'] ?>" class="db-table col-6 mb-3">
        <div class="card">

          <div class="card-header">
            <div><?= $pg_class['tablename'] ?>
              <?= $pg_class['comment'] ?></div>
            <div></div>
          </div>

          <div>
            <table class="table">
              <? foreach ($pg_class['pg_attribute'] as $attnum => $pg_attribute): ?>
                <tr>
                  <td>
                    <div id="<?= $pg_class['pg_class_id'] ?>-<?= $attnum ?>"><?= $pg_attribute['attname'] ?></div>
                  </td>
                  <td>
                    <? if ($pg_attribute['comment']): ?><?= $pg_attribute['comment'] ?><? else: ?><span class="badge badge-danger">undefined</span><? endif ?>
                  </td>
                  <td>
                    <div><?= $pg_attribute['udt_name'] ?></div>
                  </td>
                </tr>
              <? endforeach ?>
            </table>
          </div>

        </div>
      </div>


    <? endforeach ?>

  </div>
<? endif ?>
