<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', LABEL_ADD, null, ['class' => 'btn btn-primary']) ?>
  <a href="#" class="btn btn-outline-primary change-sortable" rel="list-table"><?= LABEL_SORT_ORDER ?></a>

  <a href="#" class="btn btn-primary update-sortable" controller="view_item_group">更新</a>
</div>

<table id="list-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_VIEW_ITEM_GROUPS_NAME ?></th>
    </tr>
  </thead>

  <? if ($this->view_item_group->values): ?>
    <? foreach ($this->view_item_group->values as $values): ?>
      <tr id="<?= $values['id'] ?>">
        <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $values['id']) ?></td>
        <td><a href="<?= url_for('view_item_group_member/', ['view_item_group_id' => $values['id']]) ?>"><?= $values['name'] ?></a></td>
      </tr>
    <? endforeach ?>
  <? endif ?>

</table>