<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table id="sortable-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_VIEW_ITEM_GROUPS_NAME ?></th>
    </tr>
  </thead>

  <? if ($this->view_item_group->values): ?>
    <? foreach ($this->view_item_group->values as $values): ?>
      <tr row-id="<?= $values['id'] ?>">
        <td><?= $this->view_item_group->linkEdit([], $values) ?></td>
        <td><a href="<?= $this->urlFor(['controller' => 'view_item_group_member'], ['view_item_group_id' => $values['id']]) ?>"><?= $values['name'] ?></a></td>
      </tr>
    <? endforeach ?>
  <? endif ?>

</table>