<? include('_header.phtml') ?>

<div class="">
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>Name</th>
        <th>Table</th>
        <th></th>
        <th></th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>

    <?php if ($this->pg_constraints): ?>
      <?php foreach ($this->pg_constraints as $pg_constraints): ?>
        <?php foreach ($pg_constraints as $pg_constraint): ?>
          <tr>
            <td><?= $pg_constraint['conname'] ?></td>
            <td><?= $pg_constraint['relname'] ?></td>
            <td>
              <?= $pg_constraint['attname'] ?>
            </td>
            <td>
              <?= $pg_constraint['foreign_relname'] ?>.<?= $pg_constraint['foreign_attname'] ?>
            </td>
            <td>
              <?php if ($pg_constraint['confupdtype'] == 'c'): ?>
                <? $class = 'badge badge-danger' ?>
              <? else: ?>
                <? $class = 'badge badge-default' ?>
              <?php endif ?>
              <span class="<?= $class ?>"><?= PwPgsql::$constraint_actions[$pg_constraint['confupdtype']] ?></span>
            </td>
            <td>
              <?php if ($pg_constraint['confdeltype'] == 'c'): ?>
                <? $class = 'badge badge-danger' ?>
              <? else: ?>
                <? $class = 'badge badge-default' ?>
              <?php endif ?>
              <span class="<?= $class ?>"><?= PwPgsql::$constraint_actions[$pg_constraint['confdeltype']] ?></span>
            </td>
          </tr>
        <?php endforeach ?>
      <?php endforeach ?>
    <?php endif ?>
  </table>
</div>
