<div class="card">
  <h3 class="card-header">Model</h3>
  <div class="card-block">
    <form id="form-edit" action="<?= url_for('update', $this->model['id']) ?>" method="post" autocomplete="off">
      <div class="form-group row">
        <label for="model-name" class="col-1 col-form-label">Name</label>
        <input class="form-control col-5 <?= FormHelper::validateRequired($this->errors, 'name') ?>" type="text" name="model[name]" value="<?= $this->model['name'] ?>" required autocomplete="off">
      </div>

      <div class="form-group row">
        <label for="" class="col-1 col-form-label">Label</label>
        <input class="form-control col-5 <?= FormHelper::validateRequired($this->errors, 'label') ?>" type="text" name="model[label]" value="<?= $this->model['label'] ?>" required autocomplete="off">
      </div>
      
      <button class="btn btn-primary" type="submit"><?= LABEL_UPDATE ?></button>
      <a class="btn btn-outline-primary" href="<?= url_for('list') ?>"><?= LABEL_CANCEL ?></a>
    </form>

    <? if ($this->model['id']): ?>
    <form id="" action="<?=url_for('delete', $this->model['id']) ?>" method="post">
      <input class="btn btn-outline-danger" type="submit" value="<?= LABEL_DELETE ?>">
    </form>
  <? endif ?>
</div>
</div>