<div id="help-model" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Models</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body alert alert-success">
        <ul>
          <li>if you 'Import from DB', will automatically add model's information for O/R mapping from PostgreSQL.</li>
          <li>if you 'Add', create model's information on 'project-manager' and create table on PostgreSQL.</li>
          <li>Model's name by plural form is recommended.</li>
          <li>When table is created, will automatically add columns. * id, created_at, updated_at, sort_order</li>
          <li>When you click 'PHP Export', PHP model's file(O/R map) to local path specified. *
            your_project_dir(php-work)/app/models/</li>
          <li>You can generate PHP controller files by models.</li>
        </ul>
      </div>
    </div>
  </div>
</div>