<? include('_header.phtml') ?>

<div class="">
  <div class="pt-3">
    <?= FormHelper::linkModal('#add-table-window', LABEL_ADD) ?>
  </div>

  <? include('add_table_window.phtml'); ?>

  <table class="table">
    <thead class="thead-default">
      <tr>
        <th></th>
        <th>Name</th>
        <th>Entity</th>
        <th>Class</th>
        <th>Page</th>
        <th>DB</th>
      </tr>
    </thead>
    <? foreach ($this->models as $model): ?>
    <tr>
      <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $model['id']) ?></td>
      <td>
      <div><?= FormHelper::link('attribute/', $model['name'], ['model_id' => $model['id']]) ?></div>
      <div><?= $model['label'] ?></div>
      </td>
      <td><?= $model['entity_name'] ?></td>
      <td><?= $model['class_name'] ?></td>
      <td>
        <form action="<?= url_for('page/create_page_from_model') ?>" method="post">
          <?= FormHelper::button(LABEL_CREATE, ['class' => 'btn btn-sm btn-primary confirm-dialog', 'message' => "Create page?"]) ?>
          <?= FormHelper::hidden('model_id', $model['id']) ?>
        </form>
      </td>
      <td>
        <? if ($model['pg_class']): ?>
        <?= FormHelper::badgeTag($model['pg_class']['pg_class_id']) ?>
      <? else: ?>
      <form action="<?= url_for('add_table') ?>" method="post">
        <?= FormHelper::submit(LABEL_ADD, ['class' => 'btn btn-primary btn-sm']) ?>
        <?= FormHelper::hidden('model_id', $model['id']) ?>
      </form>
    <? endif ?>

    <? if ($model['pg_class_id'] == $model['pg_class']['pg_class_id']): ?>
    <?= FormHelper::badgeTag('sync', null, 'success') ?>
    <label class="badge badge-pill badge-success">sync</label>
  <? else: ?>
  <?= FormHelper::badgeTag('unsync', null, 'danger') ?>
<? endif ?>

<? if ($model['label'] == $model['pg_class']['comment']): ?>
<?= FormHelper::badgeTag('label', null, 'success') ?>
<? else: ?>
<?= FormHelper::badgeTag('different label', null, 'danger') ?>
<?= FormHelper::badgeTag($model['pg_class']['comment'], null, 'default') ?>
<? endif ?>
</td>

</tr>
<? endforeach ?>
</table>
</div>
