<? include('_header.phtml') ?>

<? include('add_window.phtml'); ?>

<? include('help.phtml'); ?>

<div class="">
  <div class="pt-3">
    <form action="<?= $this->urlFor(['controller' => 'project', 'action' => 'sync_db']) ?>" method="post">
      <?= PwForm::linkModal('#add-window', LABEL_ADD) ?>
      <?= $this->linkTo(
        ['controller' => 'page', 'action' => 'creates_from_project'],
        [
          'class' => 'btn btn-outline-primary confirm-dialog',
          'label' => 'Quick Create',
          'message' => 'Do you create pages from all models.',
          'http_params' => ['project_id' => $this->project->value['id']]
        ]
      ) ?>
      <?= PwForm::submit('Import from DB', ['class' => 'btn btn-outline-primary confirm-dialog', 'message' => 'Do you import from DB?']) ?>
      <?= PwForm::hidden('project_id', $this->project->value['id']) ?>
      <?= PwForm::linkModal('#help-model', 'Help', ['class' => 'btn btn-outline-primary']) ?>
    </form>
  </div>

  <table class="table">
    <thead class="thead-default">
      <tr>
        <th></th>
        <th>Table Name</th>
        <th>
          <div>PwEntity Name</div>
          <div>Class Name</div>
        </th>
        <th>Controller</th>
        <th>DB info</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <? if ($this->model->values): ?>
    <? foreach ($this->model->values as $model): ?>
    <tr>
      <td>
        <?= $this->model->linkEdit([], $model) ?>
      </td>
      <td>
        <div>
          <?= $this->linkTo(['controller' => 'attribute'], 
                [
                  'label' => $model['name'], 
                  'http_params' => ['model_id' => $model['id']]
                ]
              )
              ?>
          &nbsp;
          <? if ($model['is_lock']): ?>
          <?= PwTag::iconTag('lock') ?>
          <? endif ?>
        </div>
        <div>
          <?= $model['label'] ?>
        </div>
        <? if ($model['old_name']): ?>
        <div>(
          <?= $model['old_name'] ?> :
          <?= $model['old_database_id'] ?>)</div>
        <? endif ?>
      </td>

      <td>
        <div>
          <?= $model['entity_name'] ?>
        </div>
        <div>
          <?= $model['class_name'] ?>
        </div>
      </td>
      <td>
        <form action="<?= $this->urlFor(['controller' => 'page', 'action' => 'create_page_from_model']) ?>" method="post">
          <?= PwForm::button(LABEL_CREATE, ['class' => 'btn btn-sm btn-primary confirm-dialog', 'message' => "Create page?"]) ?>
          <?= PwForm::hidden('model_id', $model['id']) ?>
        </form>
      </td>
      <td>
        <? if ($model['pg_class_id'] == $model['pg_class']['pg_class_id']): ?>
        <?= $this->linkTo(['action' => 'sync_model', 'id' => $model['id']], [ 'label' => 'Sync', 'class' => 'btn btn-sm btn-success' ]) ?>
        <? else: ?>

        <?= $this->linkTo(['action' => 'sync_model', 'id' => $model['id']], [ 'label' => 'Sync', 'class' => 'btn btn-sm btn-danger' ]) ?>
        <span class="badge badge-default">
          <?= $model['pg_class_id'] ?> =
          <?= $model['pg_class']['pg_class_id'] ?></span>
        <? endif ?>

        <? if ($model['label'] != $model['pg_class']['comment']): ?>
        <?= PwForm::badgeTag('different label', null, 'danger') ?>
        <?= PwForm::badgeTag($model['pg_class']['comment'], null, 'default') ?>
        <? endif ?>
      </td>
      <td>
        <?= $this->linkTo(['action' => 'values', 'id' => $model['id']],
            [
            'label' => 'Data',
            'class' => 'btn btn-sm btn-outline-primary'
            ]) ?>
      </td>
      <td>
        <?= $this->linkTo(['action' => 'duplicate', 'id' => $model['id']],
            [
            'label' => LABEL_DUPLICATE,
            'class' => 'btn btn-sm btn-outline-primary confirm-dialog',
            'message' => 'Do you duplicate?'
            ]
            ) ?>
      </td>

    </tr>
    <? endforeach ?>
    <? endif ?>
  </table>
</div>