
<div id="model-value-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form action="<?= $this->urlFor(['action' => 'add_value', 'id' => $this->model->value['id']]) ?>" method="post">
        <div class="modal-header">
          <h5 class="modal-title">Model</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <? foreach ($this->pg_class['pg_attribute'] as $column): ?>
        <? if (!Model::$required_columns[$column['attname']]): ?>
          <div class="form-group row">
            <label for="" class="col-6 col-form-label"><?= $column['attname'] ?></label>
            <input class="form-control col-5" type="text" name="model[<?= $column['attname'] ?>]" value="">
          </div>
        <? endif ?>
        <? endforeach ?>
        </div>
        <div class="modal-footer">
          <input class="btn btn-primary" type="submit" value="<?= LABEL_ADD ?>">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
        </div>
      </form>
    </div>
  </div>
</div>