
<?php if ($this->pg_classes): ?>
<h3><?= $this->model->value['name'] ?></h3>
<table class="table table-sm">
  <?php foreach ($this->pg_classes as $database_name => $pg_classes): ?>
  <?php foreach ($pg_classes as $pg_class): ?>
  <?php if (!Model::isNumberingName($pg_class['relname'])): ?>
  <tr>
    <td>
      <?= $database_name ?>
    </td>
    <td>
      <?= $pg_class['relname'] ?>
    </td>
    <td>
      <form action="<?= $this->urlFor(['controller' => 'model', 'action' => 'update_old_table']) ?>" method="post">
        <input type="hidden" name="model_id" value="<?= $this->model->value['id'] ?>">
        <input type="hidden" name="old_name" value="<?= $pg_class['relname'] ?>">
        <?= PwForm::submit(
          LABEL_UPDATE,
          [
          'class' => 'btn btn-primary',
          ]) ?>
        </form>
      </td>
    </tr>
  <?php endif ?>
<?php endforeach ?>
<?php endforeach ?>
</table>
<?php endif ?>