<? include('_header.phtml') ?>
  <form action="<?= $this->linkTo('update', $this->pw_params['id']) ?>" method="post">
    <div class="card">

      <div class="card-header">
        <h4></h4>
      </div>

      <div class="card-block">

        <? include('form.phtml') ?>
      </div>

      <div class="card-footer">
        <div class="text-left">
          <?= FormHelper::submit(LABEL_SAVE) ?>
          <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
          <?= $this->page_model->confirmDelete() ?>
        </div>
      </div>
    </div>
  </form>