<table class="table table-form">
  <tr>
    <th>Model</th>
    <td>
      <?= $this->page_model->formSelect('model_id', [
                        'unselect' => true,
                        'label_separate' => '-',
                        'label' => ['name',' label'],
                        'model' => 'Model',
                        'where' => "project_id = {$this->project->value['id']}",
                        'order' => 'name',
                        ]) ?>
    </td>
  </tr>

  <tr>
    <th class="form-control-label col-2" for="is_fetch_list_values">
      fetch value for action list() 
    </th>
    <td>
      <?= $this->page_model->formRadio('is_fetch_list_values', ['csv' => 'active', 'unselect' => true]) ?>
    </td>

    <tr>
      <th>
        request model for before_action()
      </th>
      <td>
        <?= $this->page_model->formRadio('is_request_session', ['csv' => 'active', 'unselect' => true]) ?>
      </td>
    </tr>
</table>
<input type="hidden" name="page_model[page_id]" value="<?= $this->page->value['id'] ?>">