<? include('_header.phtml') ?>

  <div class="pt-3">
    <?= PwForm::linkButton(['action' => 'new'], ['class' => 'btn btn-primary', 'label' => LABEL_ADD]) ?>
    <? include('views/components/lib/sortable.phtml') ?>
  </div>

  <table id="sortable-table" class="table">
    <thead class="thead-default">
      <tr>
        <th>&nbsp;</th>
        <th>Model</th>
        <th>
          <?= LABEL_PAGE_MODELS_IS_FETCH_LIST_VALUES ?>
        </th>
        <th>
          <?= LABEL_PAGE_MODELS_IS_REQUEST_SESSION ?>
        </th>
      </tr>
    </thead>

    <? if ($this->page_model->values): ?>
      <? foreach ($this->page_model->values as $values): ?>
        <tr row-id="<?= $values['id'] ?>">
          <td>
            <?= PwForm::linkButton(['action' => 'edit', 'id' => $values['id']], ['label' => LABEL_EDIT]) ?>
          </td>
          <td>
            <?= $this->model->values[$values['model_id']]['name'] ?>
          </td>
          <td>
            <?= PwForm::changeActiveLabelTag(['controller' => $this->name, 'action' => 'change_fetch_list_values', 'id' => $values['id']], $values['is_fetch_list_values']) ?>
          </td>
          <td>
            <?= PwForm::changeActiveLabelTag(['controller' => $this->name, 'action' => 'change_request_session', 'id' => $values['id']], $values['is_request_session']) ?>
          </td>
        </tr>
        <? endforeach ?>
          <? endif ?>
</table>