<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', LABEL_ADD, null, ['class' => 'btn btn-primary']) ?>
  <?= FormHelper::linkButton('sort_order', LABEL_SORT_ORDER) ?>
</div>

<table class="table">
  <thead class="thead-deffault">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_MODELS ?></th>
      <th><?= LABEL_PAGES ?></th>
    </tr>
  </thead>

  <? if ($this->page_model->values): ?>
  <? foreach ($this->page_model->values as $values): ?>
  <tr>
    <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $values['id']) ?></td>
    <td><?= $values['model_id'] ?></td>
    <td><?= $values['page_id'] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>
