<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <img class="first-slide" src="" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Part1</h1>
          <p>Note:</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="second-slide" src="" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Part2</h1>
          <p>Note:</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="third-slide" src="" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Part3</h1>
          <p>Note:</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="row">
  <div class="col-xs-4 col-sm-4 col-md-4">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-4">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-4">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

</div>

<div class="row">
  <div class="col-xs-4 col-sm-8 col-md-8">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-4">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-4">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

  <div class="col-xs-8 col-sm-8 col-md-8">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

</div>

<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="hero-unit">
      <h1>Hello, world!</h1>

      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>

    </div>
  </div>

</div>
