<div id="bottom" class="hero-unit">

  <h1>Scroll Bottom Sample</h1>

  <h2>Scroll me!</h2>

  <div>
    <h3>sample1</h3>
    <p><img class="image" src="<?= url_for('images/sample1.jpg') ?>"></p>
  </div>

  <div>
    <h3>sample2</h3>
    <p><img class="image" src="<?= url_for('images/sample2.jpg') ?>"></p>
  </div>

  <div>
    <h3>sample3</h3>
    <p><img class="image" src="<?= url_for('images/sample3.jpg') ?>"></p>
  </div>

</div>