
<table class="table">
  <tr>
    <th>upload_file_path</th>
    <td><%= $this->upload_file_path %></td>
  </tr>

  <tr>
    <th>file_type</th>
    <td><%= $this->file_type %></td>
  </tr>

  <tr>
    <th>image_ext</th>
    <td><%= $this->file_type %></td>
  </tr>

  <tr>
    <th>before encoding</th>
    <td><%= $this->encoding %></td>
  </tr>

  <tr>
    <th>contents</th>
    <td><%= $this->contents %></td>
  </tr>
</table>
