<?= '<?php'?>

/**
 * <?= Page::className($values['page']) ?> 
 *
 * @create  <?= $values['page']->value['created_at'] ?> 
 */

<? if ($values['page']->parent): ?>
require_once '<?= $values['page']->parent->value['name'] ?>Controller.php';
<? else: ?>
require_once 'AppController.php';
<? endif ?>

<? if ($parent = $values['page']->parent): ?>
class <?= $values['page']->value['name'] ?>Controller extends <?= $parent->value['name'] ?>Controller {
<? else: ?>
class <?= $values['page']->value['name'] ?>Controller extends AppController {
<? endif ?>

    public $name = '<?= $values['page']->value['entity_name'] ?>';
<? if ($values['page']->value['layout_name']): ?>
    public $layout = '<?= $values['page']->value['layout_name'] ?>';
<? endif ?>

   /**
    * before_action
    *
    * @param string $action
    * @return void
    */
    function before_action($action) {
        parent::before_action($action);
        <?= Tag::init()->requestInstance($page_model) ?>

    }

   /**
    * index
    *
    * @param
    * @return void
    */
    function index() {
        PwSession::clear('posts');
        $this->redirectTo(['action' => 'list']);;
    }

   /**
    * list
    *
    * @param
    * @return void
    */
    function action_list() {
        <?= Tag::init()->listValues($values['model'], $values['page']) ?>

        <?= Tag::init()->modelValues($page_model) ?>
        
    }

   /**
    * new
    *
    * @param
    * @return void
    */
    function action_new() {
<? if ($model = $values['model']): ?>
        $this-><?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')->new();
<? endif ?>
    }

   /**
    * edit
    *
    * @param
    * @return void
    */
    function action_edit() {
<? if ($model = $values['model']): ?>
        $this-><?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')->edit();
<? endif ?>
    }

   /**
    * add
    *
    * @param
    * @return void
    */
    function action_add() {
        $this->redirectForAdd($this->insertByModel('<?= $model->value['class_name'] ?>'));
    }

   /**
    * update
    *
    * @param
    * @return void
    */
    function action_update() {
        $this->redirectForUpdate($this->updateByModel('<?= $model->value['class_name'] ?>'));
    }

   /**
    * delete
    *
    * @param
    * @return void
    */
    function action_delete() {
<? if ($values['model']): ?>
        $this->redirectForDelete($this->deleteByModel('<?= $model->value['class_name'] ?>'));
<? endif ?>
    }

   /**
    * update sort order
    *
    * @param
    * @return void
    */
    function action_update_sort() {
<? if ($values['model']): ?>
        $this->updateSort('<?= $model->value['class_name'] ?>');
<? endif ?>
    }

}