<?= '<?php'?>

/**
 * <?= Page::className($values['page']) ?> 
 *
 * @create  <?= $values['page']->value['created_at'] ?> 
 */

<? if ($values['page']->parent): ?>
require_once '<?= $values['page']->parent->value['name'] ?>Controller.php';
<? else: ?>
require_once 'AppController.php';
<? endif ?>

<? if ($parent = $values['page']->parent): ?>
class <?= $values['page']->value['name'] ?>Controller extends <?= $parent->value['name'] ?>Controller {
<? else: ?>
class <?= $values['page']->value['name'] ?>Controller extends AppController {
<? endif ?>

    public $name = '<?= $values['page']->value['entity_name'] ?>';
<? if ($values['page']->value['layout_name']): ?>
    public $layout = '<?= $values['page']->value['layout_name'] ?>';
<? endif ?>
<? if ($values['page_filter']): ?>
    <? Tag::init()->pageFilters($values['page_filter']) ?>
<? endif ?>

   /**
    * before_action
    *
    * @param string $action
    * @return void
    */
    function before_action($action) {
        parent::before_action($action);
        <?= Tag::init()->requestInstance($page_model) ?>

    }

   /**
    * index
    *
    * @param
    * @return void
    */
    function index() {
        PwSession::clear('posts');
        $this->redirectTo(['action' => 'list']);;
    }

   /**
    * cancel
    *
    * @param
    * @return void
    */
    function action_cancel() {
        PwSession::clear('posts');
        $this->redirectTo(['action' => 'list']);;
    }

   /**
    * list
    *
    * @param
    * @return void
    */
    function action_list() {
        <?= Tag::init()->listValues($values['model'], $values['page']) ?>

        <?= Tag::init()->modelValues($page_model) ?>
        
    }

   /**
    * new
    *
    * @param
    * @return void
    */
    function action_new() {
<? if ($model = $values['model']): ?>
        $this-><?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')->init()->takeValues($this->pw_posts['<?= $model->value['entity_name'] ?>']);
<? endif ?>
    }

   /**
    * edit
    *
    * @param
    * @return void
    */
    function action_edit() {
<? if ($model = $values['model']): ?>
        $this->checkEdit();

        $this-><?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')
                    ->fetch($this->pw_params['id'])
                    ->takeValues($this->pw_posts['<?= $model->value['entity_name'] ?>']);
<? endif ?>
    }

   /**
    * add
    *
    * @param
    * @return void
    */
    function action_add() {
        if (!isPost()) exit;
<? if ($model = $values['model']): ?>
        $posts = $this->pw_posts["<?= $model->value['entity_name'] ?>"];
        $<?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')->insert($posts);

        if ($<?= $model->value['entity_name'] ?>->errors) {
            $this->addErrorByModel($<?= $model->value['entity_name'] ?>);
            $this->redirectTo(['action' => 'new']);
        } else {
            $this->redirectTo(['action' => 'index']);
        }
<? endif ?>
    }

   /**
    * update
    *
    * @param
    * @return void
    */
    function action_update() {
        if (!isPost()) exit;
<? if ($model = $values['model']): ?>
        $posts = $this->pw_posts["<?= $model->value['entity_name'] ?>"];
        $<?= $model->value['entity_name'] ?> = DB::model('<?= $model->value['class_name'] ?>')->update($posts, $this->pw_params['id']);

        if ($<?= $model->value['entity_name'] ?>->errors) {
            $this->addErrorByModel($<?= $model->value['entity_name'] ?>);
        }
        $this->redirectTo(['action' => 'edit', 'id' => $this->pw_params['id']]);
<? endif ?>
    }

   /**
    * delete
    *
    * @param
    * @return void
    */
    function action_delete() {
        if (!isPost()) exit;
<? if ($values['model']): ?>
        DB::model('<?= $model->value['class_name'] ?>')->delete($this->pw_params['id']);
<? endif ?>
        $this->redirectTo();
    }

   /**
    * update sort order
    *
    * @param
    * @return void
    */
    function action_update_sort() {
<? if ($values['model']): ?>
        $this->updatSort('<?= $model->value['class_name'] ?>');
<? endif ?>
        exit;
    }

}