<?= '<?php'?>

/**
 * <?= Page::className($values['page']) ?> 
 *
 * @create  <?= $values['page']['created_at'] ?> 
 */

<?php if ($values['page']['parent']): ?>
require_once '<?= $values['page']['parent']['name'] ?>Controller.php';
<? else: ?>
require_once 'AppController.php';
<?php endif ?>

<?php if ($values['page']['parent']): ?>
class <?= $values['page']['name'] ?>Controller extends <?= $values['page']['parent']['name'] ?>Controller {
<? else: ?>
class <?= $values['page']['name'] ?>Controller extends AppController {
<?php endif ?>

    public $name = '<?= $values['page']['entity_name'] ?>';
<?php if ($values['page']['view_name']): ?>
    public $view = '<?= $values['page']['view_name'] ?>';
<?php endif ?>
<?php if ($values['page']['layout_name']): ?>
    public $layout = '<?= $values['page']['layout_name'] ?>';
<?php endif ?>
<?php if ($values['page_filter']): ?>
    <? Tag::init()->pageFilters($values['page_filter']) ?>
<?php endif ?>

   /**
    * before_action
    *
    * @param string $action
    * @return void
    */
    function before_action($action) {
        parent::before_action($action);
        <?= Tag::init()->requestInstance($values['page_model']) ?>
    }

}