<?= '<?php'?>

/**
 * <?= Page::className($values['page']) ?> 
 *
 * @create  <?= $values['page']['created_at'] ?> 
 */

<? if ($values['page']['extend_class_name']): ?>
require_once '<?= $extend_file_name ?>.php';
<? else: ?>
require_once 'AppController.php';
<? endif ?>

<? if ($values['page']['extend_class_name']): ?>
class <?= $values['page']['name'] ?>Controller extends <?= $values['page']['extend_class_name'] ?> {
<? else: ?>
class <?= $values['page']['name'] ?>Controller extends AppController {
<? endif ?>

    var $name = '<?= $values['page']['entity_name'] ?>';
    var $session_name = '<?= $values['page']['entity_name'] ?>';

<? if ($values['page']['layout_name']): ?>
    var $layout = '<?= $values['page']['layout_name'] ?>';
<? endif ?>

   /**
    * 事前処理
    *
    * @param string $action
    * @return void
    */
    function before_action($action) {
        parent::before_action($action);
    }

   /**
    * トップページ
    * セッションクリア＆一覧画面リダイレクト
    *
    * @param
    * @return void
    */
    function index() {
        unset($this->session['posts']);
        $this->redirect_to('list');
    }

   /**
    * キャンセル
    * セッションクリア＆トップページ
    *
    * @param
    * @return void
    */
    function action_cancel() {
        unset($this->session['posts']);
        $this->redirect_to('list');
    }

   /**
    * 一覧画面
    *
    * @param
    * @return void
    */
    function action_list() {
<? if ($values['model']): ?>
        $this-><?= $values['model']['name'] ?> = DB::table('<?= $values['model']['class_name'] ?>')
                ->select()
                ->values;
<? endif ?>
    }

   /**
    * 新規作成画面
    *
    * @param
    * @return void
    */
    function action_new() {
        $this-><?= $values['model']['entity_name'] ?> = DB::table('<?= $values['model']['class_name'] ?>')
                    ->takeValues($this->session['posts']);
    }

   /**
    * 編集画面
    *
    * @param
    * @return void
    */
    function action_edit() {
<? if ($values['model']): ?>
        $this-><?= $values['model']['entity_name'] ?> = DB::table('<?= $values['model']['class_name'] ?>')
                    ->fetch($this->params['id'])
                    ->takeValues($this->session['posts']);
<? endif ?>
    }

   /**
    * 新規作成追加処理
    *
    * @param
    * @return void
    */
    function action_add() {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
<? if ($values['model']): ?>
            $posts = $this->session['posts'] = $_REQUEST["<?= $values['model']['entity_name'] ?>"];
            DB::table('<?= $values['model']['name'] ?>')->insert($posts);

            if ($<?= $values['model']['entity_name'] ?>->errors) {
                $this->redirect_to('new');
            } else {
                $this->redirect_to('index');
            }
<? endif ?>
        }
    }

   /**
    * 更新処理
    *
    * @param
    * @return void
    */
    function action_update() {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
<? if ($values['model']): ?>
            $posts = $this->session['posts'] = $_REQUEST["<?= $values['model']['entity_name'] ?>"];
            $<?= $values['model']['entity_name'] ?> = DB::table('<?= $values['model']['class_name'] ?>')->update($posts, $this->params['id']);

            if ($<?= $values['model']['entity_name'] ?>->errors) {
                $this->redirect_to('edit', $this->params['id']);
            } else {
                $this->redirect_to('index');
            }
<? endif ?>
        }
    }

   /**
    * 削除処理
    *
    * @param
    * @return void
    */
    function action_delete() {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
<? if ($values['model']): ?>
            DB::table('<?= $values['model']['class_name'] ?>')->delete($this->params['id']);
<? endif ?>
        }
        $this->redirect_to('index');
    }

   /**
    * ソート画面
    *
    * @param
    * @return void
    */
    function sort_order() {

    }

   /**
    * ソート更新
    *
    * @param
    * @return void
    */
    function action_update_sort() {
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
<? if ($values['model']): ?>
            DB::table('<?= $values['model']['class_name'] ?>')->updateSortOrder($_REQUEST['sort_order']);
<? endif ?>
        }
    }

}