<?= '<?php' ?>

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class crate_<?= $values['model']->value['name'] ?>_table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (Schema::hasTable('<?= $values['model']->value['name'] ?>')) return;
        Schema::create('<?= $values['model']->value['name'] ?>', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
<? foreach($values['attribute']->values as $attribute_value): ?>
<? $attribute = DB::model('Attribute')->setValue($attribute_value) ?>
            <?= PwLaravel::migrateFunction(DB::model('Attribute')->setValue($attribute_value)) ?>;
<? endforeach ?>
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('<?= $values['model']->value['name'] ?>');
    }
}