
<div id="add-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form action="<?= $this->urlFor(['action' => 'add']) ?>" method="post">
        <div class="modal-header">
          <h5 class="modal-title"><?= $this->database->value['name'] ?></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <label for="" class="col-3 col-form-label">Old database</label>
      <?= $this->relation_database->formSelect('old_database_id', 
        [
        'class' => ['col-5'],
        'model' => 'Database',
        'unselect' => true,
        'label' => array('name', 'hostname'),
        'label_separate' => ' : '
        ])
        ?>
          </div>
        </div>
        <div class="modal-footer">
          <input class="btn btn-primary" type="submit" value="<?= LABEL_ADD ?>">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
          <input type="hidden" name="relation_database[project_id]" value="<?= $this->project->value['id'] ?>">
        </div>
      </form>
    </div>
  </div>
</div>