<div class="card">
  <h3 class="card-header">Relation Database</h3>
  <div class="card-block">

    <form id="" action="<?= $this->linkTo('update', $this->relation_database->value['id']) ?>" method="post" autocomplete="off">

      <div class="form-group row">
        <label for="" class="col-1 col-form-label">Database</label>
        <?= $this->relation_database->formSelect('old_database_id', [
          'unselect' => true,
          'label_separate' => '-',
          'label' => ['name'],
          'model' => 'Database',
          'order' => 'name',
          ]) ?>    
        </div>


        <?= FormHelper::submit(LABEL_UPDATE) ?>
        <?= FormHelper::linkButton('cancel', LABEL_BACK) ?>
      </form>

      <?= $this->relation_database->confirmDelete() ?>
    </div>
  </div>