<? include('_header.phtml') ?>

<? include('add_window.phtml'); ?>

<div class="">
  <div class="pt-3">
    <?= PwForm::linkModal('#add-window', LABEL_ADD) ?>
    <?= PwForm::hidden('project_id', $this->project->value['id']) ?>
  </div>

  <table class="table">
    <thead class="thead-default">
      <tr>
        <th></th>
        <th>Name</th>
        <th>Host</th>
      </tr>
    </thead>

    <?php if ($this->relation_database->values): ?>
    <?php foreach ($this->relation_database->values as $relation_database): ?>
    <tr>
      <td><?= PwForm::linkButton('edit', LABEL_EDIT, $relation_database['id']) ?></td>
      <td><?= $relation_database['database_name'] ?></td>
      <td><?= $relation_database['database_hostname'] ?></td>
    </tr>
  <?php endforeach ?>
<?php endif ?>
</table>
</div>
