<? include('_header.phtml') ?>

<? include('model_value_window.phtml'); ?>

<div class="">
  <div class="pt-3">
    <?= PwForm::linkModal('#model-value-window', LABEL_ADD) ?>
    <a class="btn btn-outline-primary" href="<?= $this->linkTo('list'); ?>"><?= LABEL_BACK ?></a>
  </div>

  <div class="pt-3">
    <h3><?= $this->model->value['name'] ?></h3>
  </div>
  <div>
    <table class="table table-headerfixed">
      <thead class="thead-default">
        <tr>
        <?php foreach ($this->values[0] as $column_name => $value): ?>
        <th><?= $column_name ?></th>
        <?php endforeach ?>
        </tr>
      </thead>

      <?php if ($this->values): ?>
      <?php foreach ($this->values as $values): ?>
      <tr>
        <?php foreach ($values as $column_name => $value): ?>
        <td><?= $value ?></td>
        <?php endforeach ?>
      </tr>
      <?php endforeach ?>
      <?php endif ?>
    </table>
  </div>
</div>
