<? include('_header.phtml') ?>
<div class="card">

  <form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_params['id']]) ?>" method="post">
    <div class="card-header">
      <h4></h4>
      <div class="text-left">
        <?= FormHelper::submit(LABEL_SAVE) ?>
        <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
      </div>
    </div>

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>

  </form>

  <div class="card-footer">
    <div class="text-left">
      <?= $this->api_param->confirmDelete() ?>
    </div>
  </div>

</div>
