<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table id="sortable-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_API_PARAMS_NAME ?></th>
            <th><?= LABEL_API_PARAMS_TYPE ?></th>
            <th><?= LABEL_API_PARAMS_NOTE ?></th>
          </tr>
  </thead>

  <? if ($this->api_param->values): ?>
  <? foreach ($this->api_param->values as $values): ?>
  <tr row-id="<?= $values['id'] ?>">
    <td><?= $this->api_param->linkEdit([], $values) ?></td>
    <td><?= $values['name'] ?></td>
    <td><?= $values['type'] ?></td>
    <td><?= $values['note'] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>