<? include('_header.phtml') ?>
<div class="card">

  <form action="<?= $this->linkTo('add') ?>" method="post">

    <div class="card-header">
      <h4></h4>
      <div class="text-left">
        <?= FormHelper::submit(LABEL_SAVE) ?>
        <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
      </div>
    </div>

    <div class="card-block">
      <? include('form.phtml') ?>
    </div>

  </form>

</div>
