<nav class="navbar bg-faded">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <?= $this->linkJs(
        [
          'label' => LABEL_SENSORS,
          'icon_name' => 'chart-bar',
          'class' => 'pw-click nav-link',
          'is_use_selected' => true,
          'pw-controller' => 'multi_graph_member',
          'pw-action' => 'change_sensor',
        ]
      )
      ?>
    </li>
    <li class="nav-item">
      <?= $this->linkJs(
        [
          'label' => LABEL_SENSOR_GROUPS,
          'icon_name' => 'chart-bar',
          'class' => 'pw-click nav-link',
          'is_use_selected' => true,
          'pw-controller' => 'multi_graph_member',
          'pw-action' => 'change_sensor_group',
        ]
      )
      ?>
    </li>
    <li class="nav-item">
      <?= $this->linkJs(
          [
            'label' => LABEL_SENSOR_DISPLACE_TYPES,
            'icon_name' => 'chart-bar',
            'class' => 'pw-click nav-link',
            'is_use_selected' => true,
            'pw-controller' => 'multi_graph_member',
            'pw-action' => 'change_sensor_displace_type',
          ]
        )
        ?>
    </li>
  </ul>
</nav>

<nav class="navbar bg-faded">
  <ul class="nav nav-pills">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="multi_graph_instrument" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <?= PwTag::iconTag('tachometer-alt') ?>
        <?= LABEL_INSTRUMENTS ?></a>
      <div class="dropdown-menu text-nowrap" aria-labelledby="multi_graph_instrument">
        <? foreach($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
        <?= $this->linkJs(
          [
            'label' => $label,
            'class' => 'pw-click nav-link',
            'is_use_selected' => true,
            'pw-controller' => 'multi_graph_member',
            'pw-action' => 'change_instrument',
            'instrument_type' => $instrument_type,
          ]
        )
        ?>
        <? endforeach ?>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="multi_graph_instrument_group" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <?= PwTag::iconTag('tachometer-alt') ?>
        <?= LABEL_INSTRUMENT_GROUPS ?></a>
      <div class="dropdown-menu text-nowrap" aria-labelledby="multi_graph_instrument_group">
        <? foreach($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
        <?= $this->linkJs(
            [
              'label' => $label,
              'class' => 'pw-click nav-link',
              'is_use_selected' => true,
              'pw-controller' => 'multi_graph_member',
              'pw-action' => 'change_instrument_group',
              'instrument_type' => $instrument_type,
            ]
          )
          ?>
        <? endforeach ?>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="multi_graph_instrument_displace_type" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <?= PwTag::iconTag('tachometer-alt') ?>
        <?= LABEL_INSTRUMENT_DISPLACE_TYPES ?></a>
      <div class="dropdown-menu text-nowrap" aria-labelledby="multi_graph_instrument_displace_type">
        <? foreach($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
        <?= $this->linkJs(
            [
              'label' => $label,
              'class' => 'pw-click nav-link',
              'is_use_selected' => true,
              'pw-controller' => 'multi_graph_member',
              'pw-action' => 'change_instrument_displace_type',
              'instrument_type' => $instrument_type,
            ]
          )
          ?>
        <? endforeach ?>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle <?= PwTag::classActive('depth_group', $this->sub_menu_name) ?>" href="#"
        id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?= PwTag::iconTag('sitemap') ?>
        <?= LABEL_DEPTH_GROUPS ?></a>
      <div class="dropdown-menu" aria-labelledby="dropdown01">
        <?= $this->linkJs(
          [
            'id' => 'select_slope_group',
            'label' => $this->csv_options['instrument_type']['slope'],
            'class' => 'pw-click nav-link',
            'is_use_selected' => true,
            'pw-controller' => 'multi_graph_member',
            'pw-action' => 'change_slope_group',
          ]
        )
        ?>
        <?= $this->linkJs(
          [
            'id' => 'select_pipe_group',
            'label' => $this->csv_options['instrument_type']['pipe'],
            'class' => 'pw-click nav-link',
            'is_use_selected' => true,
            'pw-controller' => 'multi_graph_member',
            'pw-action' => 'change_pipe_group',
          ]
        )
        ?>
      </div>
    </li>


  </ul>
</nav>