
<? include('views/components/menu/admin/sensor.phtml') ?>

<? if ($this->sensor_group->value['id']): ?>
  <div class="p-2">
    <h2>
      <?= $this->sensor_group->value['name'] ?>
    </h2>
  </div>

  <nav class="navbar bg-faded">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'sensor_group',
          'action' => 'edit',
          'id' => $this->sensor_group->value['id'],
          ],
          [
            'class' => 'nav-link',
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'is_use_selected' => true,
          ]
        )
        ?>
      </li>
      <li class="nav-item">
          <?= $this->linkTo(
            [
            'controller' => 'sensor_group_member',
            'action' => 'list',
            ],
            [
              'class' => 'nav-link',
              'label' => LABEL_SENSORS,
              'icon_name' => 'edit',
              'is_use_selected' => true,
              'http_params' => [
                'sensor_group_id' => $this->sensor_group->value['id'],
              ],
            ]
          )
          ?>
        </li>
      <li class="nav-item">
          <?= $this->linkTo(
            [
            'controller' => 'sensor_group_graph',
            'action' => 'edit',
            ],
            [
              'class' => 'nav-link',
              'label' => LABEL_GRAPH,
              'icon_name' => 'edit',
              'is_use_selected' => true,
              'http_params' => [
                'sensor_group_id' => $this->sensor_group->value['id'],
              ],
            ]
          )
          ?>
        </li>
    </ul>
  </nav>
<? endif ?>
