<? if ($this->spot->value['id']): ?>
<nav class="navbar navbar-light bg-faded">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'sensor'],
          [
            'label' => LABEL_SENSORS,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'menu_group' => 'sensor',
            'icon_name' => 'compass'
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'instrument'],
          [
            'label' => LABEL_INSTRUMENTS,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'tachometer-alt'
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <? foreach ($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
      <?= $this->linkTo(
            ['controller' => "{$instrument_type}_instrument"],
            [
              'label' => $label,
              'class' => 'dropdown-item',
              'is_use_selected' => true,
              'menu_group' => $instrument_type,
              'http_params' => ['instrument_type' => $instrument_type],
            ]
          )
          ?>
      <? endforeach ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'spot_diagram'],
          [
            'label' => LABEL_SPOT_DIAGRAMS,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'globe'
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'vector_diagram'],
          [
            'label' => LABEL_VECTOR_DIAGRAMS,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'map-marker-alt',
            'menu_group' => 'vector_diagram',
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
            ['controller' => 'multi_graph'],
            [
              'label' => LABEL_MULTI_GRAPHS,
              'class' => 'nav-link',
              'is_use_selected' => true,
              'icon_name' => 'chart-bar',
              'selected_key' => 'multi_graph',
              'selected_value' => $this->group_name,
            ]
          )
          ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
              ['controller' => 'correlation_graph_group'],
              [
                'label' => LABEL_CORRELATION_GRAPHS,
                'class' => 'nav-link',
                'icon_name' => 'chart-line',
                'is_use_selected' => true,
                'selected_key' => 'correlation_graph',
                'selected_value' => $this->group_name,
              ]
            )
            ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
              ['controller' => 'event'],
              [
                'label' => LABEL_EVENT,
                'class' => 'nav-link',
                'is_use_selected' => true,
                'icon_name' => 'comment',
                'selected_key' => 'event',
                'selected_value' => $this->group_name,
              ]
            )
            ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'spot_local_weather_graph'],
          [
            'label' => LABEL_SPOT_LOCAL_WEATHER_GRAPHS,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'cloud'
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'temperature_instrument'],
          [
            'label' => LABEL_TEMPERATURE,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'thermometer-three-quarters'
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(
          ['controller' => 'soil_moisture_instrument'],
          [
            'label' => LABEL_SOIL_MOISTURE_MEASURES,
            'class' => 'nav-link',
            'is_use_selected' => true,
            'icon_name' => 'tint'
          ]
        )
        ?>
    </li>
  </ul>
</nav>
<? endif ?>