<? include('_header.phtml') ?>
<form action="<?= url_for('update', $this->params['id']) ?>" method="post">

  <table class="table">

    <tr>
      <th><?= LABEL_RECORD_ITEMS_KEY ?></th>
      <td>
                <?= $this->record_item->formInput('key') ?>        
      </td>
    </tr>


    <tr>
      <th><?= LABEL_RECORD_ITEMS_VALUE ?></th>
      <td>
                <?= $this->record_item->formInput('value') ?>        
      </td>
    </tr>


  </table>

  <?= FormHelper::submit(LABEL_SAVE) ?>
  <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>  

</form>

<?= $this->record_item->formDelete() ?>