<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_params['id']]) ?>" method="post">
  <div class="card">

    <div class="card-header">
      <h4></h4>
      <div class="text-left">
      </div>
    </div>

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>


    <div class="card-footer">
      <div class="text-left">
        <?= FormHelper::submit(LABEL_SAVE) ?>
        <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
        <?= $this->record_item->confirmDelete() ?>
      </div>
    </div>

  </div>
  </form>