
<div class="form-group row">
  <label class="form-control-label col-2" for="key"><?= LABEL_RECORD_ITEMS_KEY ?></label>
    <?= $this->record_item->formInput('key') ?>    
</div>



<div class="form-group row">
  <label class="form-control-label col-2" for="value"><?= LABEL_RECORD_ITEMS_VALUE ?></label>
    <?= $this->record_item->formInput('value') ?>    
</div>






<?= FormHelper::submit(LABEL_SAVE) ?>
<?= FormHelper::linkButton("cancel", LABEL_BACK) ?>
<input type="hidden" name="record_item[record_id]" value="<?= $this->record->value['id'] ?>">
