<? include('_header.phtml') ?>
<form action="<?= url_for('add') ?>" method="post">

  <table class="table">

    <tr>
      <th><?= LABEL_RECORD_ITEMS_KEY ?></th>
      <td>
                <?= $this->record_item->formInput('key') ?>        
      </td>
    </tr>


    <tr>
      <th><?= LABEL_RECORD_ITEMS_VALUE ?></th>
      <td>
                <?= $this->record_item->formInput('value') ?>        
      </td>
    </tr>


  </table>

  <?= FormHelper::submit(LABEL_SAVE) ?>  
  <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>
  <input type="hidden" name="record_item[record_id]" value="<?= $this->record->value['id'] ?>">


</form>