<? include('spot.phtml') ?>

<div class="col-12">
  <div class="row">
    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title">
          <?= LABEL_PIPE_GROUPS ?>
        </li>
        <li class="nav-item nav-element pt-1 pl-1">
          <?= PwForm::select([
          'name' => 'pipe_group_id',
          'label' => 'name',
          'value' => 'id',
          'model' => 'PipeGroup',
          'where' => ['spot_id', $this->spot->value['id']],
          'id' => 'pipe_group_id',
          'class' => 'form-control pw-change',
          'pw-controller' => $this->jsControllerName(),
          'pw-action' => 'change',
        ],
        $this->pipe_group->value['id']
        ) ?>
        </li>
      </ul>
    </nav>
  </div>
</div>
