<? include('views/components/menu/admin/spot.phtml') ?>

<? if ($this->rainfall_area->value['id']): ?>
  <div class="d-flex p-2">
    <h2>
      <?= $this->rainfall_area->value['code'] ?>
      <?= $this->rainfall_area->value['name'] ?>
      (<?= $this->rainfall_area->typeName() ?>)
    </h2>
  </div>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">

      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'observe_rainfall',
          'action' => 'list'
          ],
          [
            'label' => LABEL_MEASUREMENT,
            'icon_name' => 'database',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'http_params' => ['rainfall_area_id' => $this->rainfall_area->value['id']]
          ]
        )
        ?>
      </li>
    </ul>
  </nav>

<? endif ?>