<? include('views/components/observe/spot.phtml') ?>

<? if ($this->soil_moisture_instrument->value['id']): ?>
  <div class="d-flex p-2">
    <h2><?= $this->soil_moisture_instrument->value['name'] ?></h2>
    <input type="hidden" id="soil_moisture_instrument" value="<?= $this->soil_moisture_instrument->value['id'] ?>">
  </div>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
      <? if ($this->isDeveloper()): ?>
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'observe_soil_moisture_measure',
          'action' => 'list',
          ],
          [
            'label' => LABEL_MEASUREMENT,
            'icon_name' => 'database',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'http_params' => ['soil_moisture_instrument_id' => $this->soil_moisture_instrument->value['id']]
          ]
        )
        ?>
      </li>
      <? endif ?>
    </ul>
  </nav>

<? endif ?>