<div class="col-12">
  <div class="row">
    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title"><?= LABEL_VECTOR_DIAGRAMS ?></li>
        <li class="nav-item nav-element p-1">
          <?= PwForm::select(
          [
          'name' => 'vector_diagram_id',
          'unselect' => false,
          'label' => ['name'],
          'value' => 'id',
          'id' => 'vector_diagram_id',
          'class' => 'form-control pw-change',
          'model' => 'VectorDiagram',
          'wheres' => [
              ['spot_id', $this->spot->value['id']],
              ['diagram_type', 'S'],
          ],
          'pw-controller' => 'observe_spot_diagram',
          'pw-action' => 'change',
          'pw-callback' => $this->pw_action
          ],
          $this->spot_diagram->value['id']
          ) ?>
        </li>
      </ul>
    </nav>

    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title">
          <?= LABEL_DOWNLOAD ?>
        </li>
        <li class="nav-item nav-element">
          <?= PwTag::a(
            [
              'label' => LABEL_DIAGRAM,
              'icon_name' => 'download',
              'class' => 'pw-click btn btn-outline-primary',
              'message' => MESSAGE_DOWNLOAD,
              'pw-controller' => $this->js_controller,
              'pw-action' => 'diagram_download',
            ]
          )
          ?>
        </li>
      </ul>
    </nav>
  </div>

</div>
