
<nav class="navbar bg-faded">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <?= $this->linkJs(
        [
          'label' => LABEL_SENSORS,
          'icon_name' => 'chart-bar',
          'class' => 'pw-click nav-link',
          'is_use_selected' => true,
          'pw-controller' => 'event',
          'pw-action' => 'sensorList',
        ]
      )
      ?>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="multi_graph_instrument" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <?= PwTag::iconTag('tachometer-alt') ?>
        <?= LABEL_INSTRUMENTS ?></a>
      <div class="dropdown-menu text-nowrap" aria-labelledby="multi_graph_instrument">
        <? foreach($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
        <?= $this->linkJs(
          [
            'label' => $label,
            'class' => 'pw-click nav-link',
            'is_use_selected' => true,
            'pw-controller' => 'event',
            'pw-action' => 'instrumentList',
            'instrument_type' => $instrument_type,
          ]
        )
        ?>
        <? endforeach ?>
      </div>
    </li>

  </ul>
</nav>