<? include('views/components/menu/admin/instrument.phtml') ?>

<? if ($this->instrument_multi_group->value['id']): ?>
<div class="d-flex p-2">
  <h2>
    <?= $this->instrument_multi_group->value['name'] ?>
  </h2>
</div>

<nav class="navbar bg-faded">
  <ul class="nav nav-pills">

    <li class="nav-item">
      <?= $this->linkTo(
          [
          'controller' => "{$this->instrument_type}_instrument_multi_group",
          'action' => 'edit',
          'id' => $this->instrument_multi_group->value['id'],
          ],
          [
            'label' => LABEL_SETTING,
            'icon_name' => 'cog',
            'class' => 'nav-link',
            'is_use_selected' => true,
          ]
        )
        ?>
    </li>

    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'instrument_multi_group_member'],
          [
            'label' => LABEL_INSTRUMENTS,
            'icon_name' => 'tachometer-alt',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'http_params' => ['instrument_multi_group_id' => $this->instrument_multi_group->value['id']]
          ]
        )
        ?>
    </li>
  </ul>
</nav>
<? endif ?>