
<? include('views/components/menu/admin/instrument_group.phtml') ?>

<? if ($this->pipe_group->value['id']): ?>
  <h2><?= $this->pipe_group->value['name'] ?></h2>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
    <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'pipe_group',
          'action' => 'edit',
          'id' => $this->pipe_group->value['id']
          ],
          [
            'class' => 'nav-link',
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'is_use_selected' => true,
            'http_params' => ['pipe_group_id' => $this->pipe_group->value['id']], 
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'pipe_depth_graph'],
          [
            'class' => 'nav-link',
            'label' => LABEL_DEPTH_GRAPHS,
            'icon_name' => 'chart-bar',
            'is_use_selected' => true,
            'http_params' => ['pipe_group_id' => $this->pipe_group->value['id']], 
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'pipe_depth_time_graph'],
          [
            'class' => 'nav-link',
            'label' => LABEL_DEPTH_TIME_GRAPHS,
            'icon_name' => 'chart-bar',
            'is_use_selected' => true,
            'http_params' => ['pipe_group_id' => $this->pipe_group->value['id']], 
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'pipe_group_member'],
          [
            'class' => 'nav-link',
            'label' => LABEL_INSTRUMENTS,
            'icon_name' => 'tachometer-alt',
            'is_use_selected' => true,
            'http_params' => ['pipe_group_id' => $this->pipe_group->value['id']], 
          ]
        )
        ?>
      </li>
    </ul>
  </nav>
<? endif ?>
