<div class="col-12">
  <div class="row">

    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title">
          <?= LABEL_SENSOR_GRAPHS ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'sensor_measure', 'action' => 'graph'], ['label' => LABEL_GRAPH, 'class' => 'nav-link', 'is_use_selected' => 1, 'http_params' => ['sensor_id' => $this->sensor->value['id'], 'is_latest' => 1]]) ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'sensor_measure', 'action' => 'list'], ['label' => LABEL_LIST, 'class' => 'nav-link', 'is_use_selected' => 1, 'http_params' => ['sensor_id' => $this->sensor->value['id'], 'is_latest' => 1]]) ?>
        </li>
        <li class="nav-item nav-title">
          <?= LABEL_DISPLACE ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'sensor_displace', 'action' => 'graph'], ['label' => LABEL_GRAPH, 'class' => 'nav-link', 'is_use_selected' => 1, 'http_params' => ['sensor_id' => $this->sensor->value['id'], 'is_latest' => 1]]) ?>
        </li>
        <li class="nav-item nav-element">
          <?= $this->linkTo(['controller' => 'sensor_displace', 'action' => 'list'], ['label' => LABEL_LIST, 'class' => 'nav-link', 'is_use_selected' => 1, 'http_params' => ['sensor_id' => $this->sensor->value['id'], 'is_latest' => 1]]) ?>
        </li>
      </ul>
    </nav>

    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title">
          <?= LABEL_DOWNLOAD ?>
        </li>
        <li class="nav-item nav-element">
          <?= PwTag::a(
            [
              'label' => LABEL_GRAPH,
              'icon_name' => 'download',
              'class' => 'pw-click btn btn-outline-primary',
              'message' => MESSAGE_DOWNLOAD,
              'pw-controller' => $this->pw_controller,
              'pw-action' => 'graph_download',
            ]
          )
          ?>
          <?= PwTag::a(
            [
              'label' => LABEL_CSV,
              'icon_name' => 'download',
              'class' => 'pw-click btn btn-outline-primary',
              'message' => MESSAGE_DOWNLOAD,
              'pw-controller' => $this->pw_controller,
              'pw-action' => 'csv_download',
            ]
          )
          ?>
        </li>
      </ul>
    </nav>
  </div>

</div>
