<?= PwTag::javascriptController('SlopeGroupController') ?>

<? include('views/components/menu/admin/instrument_group.phtml') ?>

<? if ($this->slope_group->value['id']): ?>
  <div id="change-slope_group-window" class="modal"></div>
  <div class="d-flex p-2">
    <h2>
      <?= $this->slope_group->value['name'] ?>
      <button type="button" class="pw-click btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#change-slope_group-window" pw-controller="slope_group" pw-action="change_select" spot-id="<?= $this->spot->value['id'] ?>"><?= LABEL_SELECT ?></button>
    </h2>
  </div>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'slope_group',
          'action' => 'edit',
          'id' => $this->slope_group->value['id'],
          ], 
          [
            'class' => 'nav-link',
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'is_use_selected' => true,
            'http_params' => ['slope_group_id' => $this->slope_group->value['id']], 
          ]
        )
        ?>
      </li>

      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'slope_depth_graph'],
          [
            'class' => 'nav-link',
            'label' => LABEL_DEPTH_GRAPHS,
            'icon_name' => 'chart-bar',
            'is_use_selected' => true,
            'http_params' => ['slope_group_id' => $this->slope_group->value['id']], 
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'slope_depth_time_graph'],
          [
            'class' => 'nav-link',
            'label' => LABEL_DEPTH_TIME_GRAPHS,
            'icon_name' => 'chart-bar',
            'is_use_selected' => true,
            'http_params' => ['slope_group_id' => $this->slope_group->value['id']], 
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'slope_group_member'],
          [
            'class' => 'nav-link',
            'label' => LABEL_INSTRUMENTS,
            'icon_name' => 'tachometer-alt',
            'is_use_selected' => true,
            'http_params' => ['slope_group_id' => $this->slope_group->value['id']], 
          ]
        )
        ?>
      </li>
    </ul>
  </nav>
<? endif ?>