<? include('views/components/menu/admin/spot.phtml') ?>
<h1 class="h1">
  <?= LABEL_SPOT_MANAGERS ?>
</h1>

<? if ($this->spot_manager->value): ?>
<div class="mt-2">
  <h2 class="">
    <?= $this->spot_manager->value['name'] ?>
    :
    <?= $this->spot_manager->value['login_name'] ?>
  </h2>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <?= $this->linkTo(
            [
            'controller' => 'spot_manager',
            'action' => 'edit',
            'id' => $this->spot_manager->value['id'],
            ],
            [
              'label' => LABEL_SETTING, 
              'class' => 'nav-link',
              'icon_name' => 'edit',
              'is_use_selected' => true,
            ]
          )
          ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'spot_manager_member'],
          [
            'label' => LABEL_SPOT_MANAGER_MEMBERS, 
            'class' => 'nav-link',
            'icon_name' => 'users',
            'is_use_selected' => true,
            'http_params' => ['spot_manager_id' => $this->spot_manager->value['id']]
          ]
        )
        ?>
      </li>
      <li class="nav-item">
          <?= $this->linkTo(['controller' => 'spot_manager_map'],
            [
              'label' => LABEL_MAP, 
              'class' => 'nav-link',
              'icon_name' => 'map',
              'is_use_selected' => true,
              'http_params' => ['spot_manager_id' => $this->spot_manager->value['id']]
            ]
          )
          ?>
        </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'spot_manager_instrument_type'],
          [
            'label' => LABEL_INSTRUMENT_TYPE, 
            'class' => 'nav-link',
            'icon_name' => 'tachometer-alt',
            'is_use_selected' => true,
            'http_params' => ['spot_manager_id' => $this->spot_manager->value['id']]
          ]
        )
        ?>
      </li>
      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'spot_manager_menu'],
          [
            'label' => LABEL_SPOT_MANAGER_MENUS, 
            'class' => 'nav-link',
            'icon_name' => 'tachometer-alt',
            'is_use_selected' => true,
            'http_params' => ['spot_manager_id' => $this->spot_manager->value['id']]
          ]
        )
        ?>
      </li>
    </ul>
  </nav>
</div>
<? endif ?>