<? if ($this->spot->value['id']): ?>
<div class="p-2">
  <span id="side_btn">
    <?= $this->linkJs([
        'class' => 'pw-click',
        'icon_name' => 'bars',
        'pw-controller' => 'shamen',
        'pw-action' => 'change_side_bar',
        ]) ?>
  </span>
  <span class="title">
    <?= $this->spot->value['code'] ?>
    <?= $this->spot->value['name'] ?>
  </span>
  <input id="spot-id" type="hidden" value="<?= $this->spot->value['id'] ?>">
</div>
<nav class="navbar">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <?= $this->linkTo(
          [
          'controller' => 'spot',
          'action' => 'edit',
          'id' => $this->spot->id
          ],
          [
            'class' => 'nav-link',
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'is_use_selected' => true,
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'spot_menu'],
          [
            'class' => 'nav-link',
            'label' => LABEL_SPOT_MENUS,
            'icon_name' => 'bars',
            'is_use_selected' => true,
            'menu_group' => 'spot_menu',
            'http_params' => ['spot_id' => $this->spot->value['id']]
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'spot_alert_level'],
      [
        'class' => 'nav-link',
        'label' => LABEL_SPOT_ALERT_LEVELS,
        'icon_name' => 'signal',
        'is_use_selected' => true,
        'http_params' => ['spot_id' => $this->spot->value['id']]
      ]
    )
    ?>
    </li>
    <li class="nav-item dropdown text-nowrap">
      <a class="nav-link dropdown-toggle" href="#" id="dropdown-system" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?= PwTag::iconTag('users') ?>
        <?= LABEL_CONTACTS ?></a>
      <div class="dropdown-menu" aria-labelledby="dropdown-system">
        <?= $this->linkTo(['controller' => 'customer'],
              [
                'class' => 'nav-link',
                'label' => LABEL_CONTACTS,
                'icon_name' => 'users',
                'is_use_selected' => true,
                'menu_group' => 'alert',
                'http_params' => ['spot_id' => $this->spot->value['id']]
              ]
            )
            ?>
        <?= $this->linkTo(['controller' => 'spot_error_contact'],
            [
              'class' => 'nav-link',
              'label' => LABEL_SPOT_ERROR_CONTACTS,
              'icon_name' => 'exclamation-circle',
              'is_use_selected' => true,
              'menu_group' => 'alert',
              'http_params' => ['spot_id' => $this->spot->value['id']]
            ]
          )
          ?>
      </div>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'spot_display_day'],
          [
            'class' => 'nav-link',
            'label' => LABEL_SPOT_DISPLAY_DAYS,
            'icon_name' => 'edit',
            'is_use_selected' => true,
            'http_params' => ['spot_id' => $this->spot->value['id']]
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'update_schedule'],
          [
            'class' => 'nav-link',
            'label' => LABEL_UPDATE_SCHEDULES,
            'icon_name' => 'clock',
            'is_use_selected' => true,
            'http_params' => ['spot_id' => $this->spot->value['id']]
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'logger_mail_setting'],
          [
            'class' => 'nav-link',
            'label' => LABEL_LOGGER_MAIL_SETTINGS,
            'icon_name' => 'paper-plane',
            'is_use_selected' => true,
            'http_params' => ['spot_id' => $this->spot->value['id']]
          ]
        )
        ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'information'],
          [
            'class' => 'nav-link',
            'label' => LABEL_INFORMATIONS,
            'icon_name' => 'comment',
            'is_use_selected' => true,
            'http_params' => ['spot_id' => $this->spot->value['id']]
          ]
        )
        ?>
    </li>
  </ul>
</nav>
<? endif ?>