<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_gets['id']]) ?>" method="post">

  <table class="table">
    <tr>
      <th>Name</th>
      <td>
        <?= $this->localize_string->formInput('name', ['class' => 'form-control col-5']) ?>
      </td>
    </tr>

    <?php foreach ($this->lang->values as $lang): ?>
    <tr>
      <th>Language(<?= $lang['name'] ?>)</th>
      <td><input class="form-control" name="localize_string[label][<?= $lang['lang'] ?>]" value="<?= $this->localize_string->value['label'][$lang['lang']] ?>"></td>
    </tr>
    <?php endforeach ?>

  </table>

  <?= PwForm::submit(LABEL_SAVE) ?>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
  <?= $this->localize_string->confirmDelete() ?>

</form>