<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', null, ['class' => 'btn btn-primary', 'label' => LABEL_ADD]) ?>
  <?= FormHelper::linkButton('import_from_model', null, ['class' => 'btn btn-outline-primary', 'label' => LABEL_IMPORT]) ?>
  <?= FormHelper::linkButton('sort_order', null, ['class' => 'btn btn-outline-primary', 'label' => LABEL_SORT_ORDER]) ?>
</div>
<div>
  <form action="<?= url_for('csv_import'); ?>" method="post" enctype="multipart/form-data">
    <input class="btn btn-primary" type="submit" value="<?= LABEL_CSV_IMPORT ?>">
    <input type="file" name="file">
  </form>
</div>
<table class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>坝称</th>
      <th>言語</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <? if ($this->localize_string->values): ?>
    <? foreach ($this->localize_string->values as $values): ?>
      <tr>
        <td><?= FormHelper::linkButton('edit', $values['id'], ['label' => LABEL_EDIT]) ?></td>
        <td><?= $values['name'] ?></td>
        <td>
          <dl class="row">
          <? foreach ($this->lang->values as $lang): ?>
            <? $labels = json_decode($values['label'], true) ?>
            <dt class="col-2"><?= $lang['name'] ?></dt>
            <dd class="col-10"><?= $labels[$lang['lang']] ?></dd>
          <? endforeach ?>
          </dl>
        </td>
        <td><a class="btn btn-outline-primary" href="<?= url_for('duplicate', $values['id']) ?>"><?= LABEL_DUPLICATE ?></a></td>
      </tr>
    <? endforeach ?>
  <? endif ?>

</table>
