<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['class' => 'btn btn-primary', 'label' => LABEL_ADD]) ?>
  <?= PwForm::linkButton(['controller' => 'lang'], ['class' => 'btn btn-outline-primary', 'label' => 'Language']) ?>
  <?= PwForm::linkButton(['action' => 'import_from_model'], ['class' => 'btn btn-outline-primary', 'label' => LABEL_IMPORT]) ?>
</div>
<div>
  <form action="<?= $this->urlFor(['action' => 'csv_import']); ?>" method="post" enctype="multipart/form-data">
    <input class="btn btn-primary" type="submit" value="<?= LABEL_IMPORT ?>">
    <input type="file" name="file">
  </form>
</div>
<table class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Label</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <?php if ($this->localize_string->values): ?>
    <?php foreach ($this->localize_string->values as $values): ?>
      <tr>
        <td><?= $this->localize_string->linkEdit([], $values) ?></td>
        <td><?= $values['name'] ?></td>
        <td>
          <dl class="row">
          <?php foreach ($this->lang->values as $lang): ?>
            <? $labels = json_decode($values['label'], true) ?>
            <dt class="col-2"><?= $lang['name'] ?></dt>
            <dd class="col-10"><?= $labels[$lang['lang']] ?></dd>
          <?php endforeach ?>
          </dl>
        </td>
        <td>
          <?= $this->linkTo(['action' => 'duplicate', 'id' => $values['id']],
                            [
                            'label' => LABEL_DUPLICATE,
                            'class' => 'btn btn-outline-primary',
                            ]
          ) ?>
        </td>
      </tr>
    <?php endforeach ?>
  <?php endif ?>

</table>
