<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'add']) ?>" method="post">

  <table class="table">
    <tr>
      <th>Name</th>
      <td><?= $this->localize_string->formInput('name') ?></td>
    </tr>

    <? foreach ($this->lang->values as $lang): ?>
    <tr>
      <th>Lang(<?= $lang['name'] ?>)</th>
      <td><input class="form-control" name="localize_string[label][<?= $lang['lang'] ?>]" value=""></td>
    </tr> 
    <? endforeach ?>

    </table>

  <?= PwForm::submit(LABEL_SAVE) ?>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>  
    
  <input type="hidden" name="localize_string[project_id]" value="<?= $this->project->value['id'] ?>">
</form>

  <?= $this->localize_string->confirmDelete() ?>