
<div class="card">
  <h4 class="card-header">
    <?= $this->model->value['name'] ?>
    <label class="badge badge-pill badge-info"><?= $this->pg_class['pg_class_id'] ?></label>
  </h4>
  
  <? if ($this->pg_class['pg_class_id'] != $this->model->value['pg_class_id']): ?>
  <div class="alert alert-danger">
    pg_class is not match on PostgreSQL.
    <ul>
      <li>pg_class : <?= $this->pg_class['pg_class_id'] ?></li>
      <li>model : <?= $this->model->value['pg_class_id'] ?></li>
    </ul>
  </div>
  <? endif ?>

  <div class="card-body">
    <table class="table">
      <thead class="thead-default">
        <tr>
          <th></th>
          <th>Name</th>
          <th>Label</th>
          <th>Relation</th>
          <th>Type</th>
          <th>Required</th>
          <th>DB</th>
        </tr>
      </thead>

      <tbody>
        <? if ($this->attribute->values): ?>
        <? foreach ($this->attribute->values as $attribute): ?>
        <tr>
          <td>
            <? if (!Model::$required_columns[$attribute['name']]): ?><?= FormHelper::linkButton('edit', LABEL_EDIT, $attribute['id']) ?><? endif ?>
          </td>

          <td>
          <?= $attribute['name'] ?>
          <? if ($attribute['old_name']): ?>
          <div>
          (<?= $attribute['old_name'] ?>)
          <a class="btn btn-danger btn-sm" href="<?= url_for('delete_old_name', ['attribute_id' => $attribute['id']]) ?>"><?= LABEL_DELETE ?></a>
          </div>
        <? endif ?>
          </td>

          <td>
            <form method="post" action="<?= url_for('update_label', $attribute['id']) ?>">
              <div class="row">
               <div class="input-group">
                 <?= FormHelper::input(['class' => 'form-control form-control-sm'], 'attribute[label]', $attribute['label']) ?>
                 <span class="input-group-btn"><?= FormHelper::button(LABEL_UPDATE, ['class' => 'btn btn-primary btn-sm']) ?></span>
               </div>
             </div>
             <?= FormHelper::hidden('pg_class_id', $attribute['pg_attribute']['pg_class_id']) ?>
             <?= FormHelper::hidden('database_id', $this->database->value['id']) ?>
           </form>
         </td>

         <td>
          <? if ($attribute['fk_attribute_id'] > 0): ?>
          <?= FormHelper::linkModal('#relation-window', 'relation', 
            [
            'class' => 'btn btn-success btn-sm pw-app', 
            'pw-controller' => 'attribute',
            'pw-action' => 'relation_model_list', 
            'attribute_id' => $attribute['id'], 
            ]) ?>
          <? else: ?>
          <?= FormHelper::linkModal('#relation-window', 'relation', 
            [
            'class' => 'btn btn-outline-primary btn-sm pw-app', 
            'pw-controller' => 'attribute',
            'pw-action' => 'relation_model_list', 
            'attribute_id' => $attribute['id'], 
            ]) ?>
          <? endif ?>
        </td>

        <td>
          <label class="badge badge-pill badge-info">
            <?= $attribute['type'] ?> <? if ($attribute['length'] > 0): ?> (<?= $attribute['length'] ?>) <? endif ?>
          </label>
        </td>
        
        <td>
          <? if (!Model::$required_columns[$attribute['name']]): ?>
          <? if ($attribute['is_required']): ?>
          <?= FormHelper::link('change_required', 'required', $attribute['id'], ['class' => 'badge badge-success']) ?>
        <? else: ?>
        <?= FormHelper::link('change_required', 'required', $attribute['id'], ['class' => 'badge badge-default']) ?>
      <? endif ?>
    <? endif ?>
  </td>
  
  <td>
    <?= FormHelper::badgeTag($attribute['pg_attribute']['attnum'], null, 'info') ?>
    <? if ($attribute['pg_attribute'] && $attribute['attnum'] == $attribute['pg_attribute']['attnum']): ?>
    <?= FormHelper::badgeTag('sync', null, 'success') ?>

    <? if ($attribute['pg_attribute']['attname'] != $attribute['name']): ?><?= FormHelper::badgeTag($attribute['pg_attribute']['attname'], null, 'danger') ?><? endif ?>

    <? if ($attribute['pg_attribute']['udt_name'] != $attribute['type']): ?><?= FormHelper::badgeTag($attribute['pg_attribute']['udt_name'], null, 'danger') ?>
    <?= FormHelper::badgeTag($attribute['pg_attribute']['character_maximum_length'], null, 'danger') ?><? endif ?>

    <? if ($attribute['is_primary_key']): ?><?= FormHelper::badgeTag('Primary', null, 'info') ?><? endif ?>
    <? if ($attribute['pg_attribute']['attnotnull'] == 't'): ?><?= FormHelper::badgeTag('Not Null', null, 'info') ?><? endif ?>
  <? else: ?>
  <label class="badge badge-pill badge-danger">unsync</label>
  <form action="<?= url_for('add_table', $attribute['id']) ?>" method="post">
    <?= FormHelper::submit(LABEL_ADD, ['class' => 'btn btn-outline-primary']) ?>
    <?= FormHelper::hidden('model_id', $this->model->value['id']) ?>
    <?= FormHelper::hidden('table_name', $this->model->value['name']) ?>
  </form>
<? endif ?>
</td>
</tr>
<? endforeach ?>
<? endif ?>
</tbody>
</table>
</div>
</div>
