
<? include('unique_attribute_window.phtml') ?>

<div class="card">
  <div class="card-header">Primary</div>

  <div class="card-body">

    <div class="p-4">
      <? include('constraints_primary.phtml') ?>
    </div>

  </div>

</div>


<div class="card">
  <div class="card-header">Foreign</div>

  <div class="card-body">

    <div class="p-4">
      <? include('constraints_foreign.phtml') ?>
    </div>

  </div>

</div>


<div class="card">
  <div class="card-header">
    Unique
    <?= FormHelper::linkModal('#unique_attribute_window', LABEL_ADD, 
      ['class' => 'btn btn-sm btn-primary pw-click',
      'pw-controller' => 'attribute',
      'pw-action' => 'unique_attribute_list',
      'model_id' => $this->model->value['id'],
      ]) ?>
    </div>

    <div class="card-body">

      <div class="p-4">
        <? include('constraints_unique.phtml') ?>
      </div>

    </div>

  </div>
