<? if ($this->pg_class['pg_constraint']['foreign']): ?>
<? foreach ($this->pg_class['pg_constraint']['foreign'] as $pg_constraint): ?>
<div class="row">
  <div class="col-4">
    <form action="<?= $this->urlFor(['action' => 'rename_constraint']) ?>" method="post">
      <div class="input-group">
        <?= PwForm::input(['class' => 'form-control form-control'], 'new_constraint_name', $pg_constraint['conname']) ?>
        <span class="input-group-btn"><?= PwForm::button(LABEL_UPDATE, ['class' => 'btn btn-primary btn-sm confirm-dialog', 'message' => 'Do you rename Constrain key?']) ?></span>
      </div>
      <?= PwForm::hidden('constraint_name', $pg_constraint['conname']) ?></a>
      <?= PwForm::hidden('model_id', $this->model->value['id']) ?></a>
      <?= PwForm::hidden('database_id', $this->database->value['id']) ?></a>
    </form>
  </div>

  <div class="col-4">
    <?= $pg_constraint['attname'] ?>
    ->
    <?= $pg_constraint['foreign_relname'] ?>.<?= $pg_constraint['foreign_attname'] ?>
  </div>

  <div class="col-3">
    <div>
      update : <span class="badge badge-info"><?= PwPgsql::$constraint_actions[$pg_constraint['confupdtype']] ?></span>
    </div>
    <div>
      delete : <span class="badge badge-info"><?= PwPgsql::$constraint_actions[$pg_con1traint['confdeltype']] ?></span>
    </div>
  </div>

  <div class="col-1">
    <form action="<?= $this->urlFor(['action' => 'delete_constraint']) ?>" method="post">
      <?= PwForm::submit(LABEL_DELETE, ['class' => 'btn btn-sm btn-danger confirm-dialog', 'message' => 'Do you delete Constrain key?']) ?></a>
      <?= PwForm::hidden('constraint_name', $pg_constraint['conname']) ?></a>
      <?= PwForm::hidden('model_id', $this->model->value['id']) ?></a>
      <?= PwForm::hidden('database_id', $this->database->value['id']) ?></a>
    </form>

  </div>

</div>
<? endforeach ?>

<? endif ?>
