<div class="card">
  <h3 class="card-header">Attribute</h3>
  <div class="card-block">
    <form id="" action="<?= url_for('update', $this->attribute['id']) ?>" method="post" autocomplete="off">
      <div class="form-group row">
        <label class="form-control-label col-2">attrelid</label>
        <?= $this->attribute['attrelid'] ?>
      </div>

      <div class="form-group row">
        <label class="form-control-label col-2">attnum</label>
        <?= $this->attribute['attnum'] ?>
      </div>

      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Name</label>
        <input class="form-control col-4 <?= FormHelper::validateRequired($this->errors, 'name') ?>" type="text" name="attribute[name]" value="<?= $this->attribute['name'] ?>" required autocomplete="off">
      </div>

      <div class="form-group row">
        <label for="recipient-name" class="form-control-label col-2">Label</label>
        <input class="form-control col-4 <?= FormHelper::validateRequired($this->errors, 'label') ?>" type="text" name="attribute[label]" value="<?= $this->attribute['label'] ?>" autocomplete="off">
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Type</label>
        <?= FormHelper::select($this->forms['pg_types'], $this->attribute['type']) ?>
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Length</label>
        <input class="form-control col-2" type="text" name="attribute[length]" value="<?= $this->attribute['length'] ?>">
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Requied</label>
        <?= FormHelper::checkbox($this->forms['is_required'], (bool) $this->attribute['is_required']) ?>
      </div>

      <button class="btn btn-primary" type="submit"><?= LABEL_UPDATE ?></button>
      <a class="btn btn-outline-primary" href="<?= url_For('list') ?>" class="btn"><?= LABEL_BACK ?></a>
      <input type="hidden" name="attribute['attnum']" value="<?= $this->attribute['attnum'] ?>">

    </form>

    <? if ($this->attribute['id']): ?>
    <form id="" action="<?=url_for('delete', $this->attribute['id']) ?>" method="post">
      <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
    </form>
  <? endif ?>

</div>
</div>
