<form id="form-edit" action="<?= url_for('update', $this->attribute['id']) ?>" method="post" autocomplete="off">

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Name</label>
    <input class="form-control col-4 <?= FormHelper::validateRequired($this->errors, 'name') ?>" type="text" name="attribute[name]" value="<?= $this->attribute['name'] ?>" required autocomplete="off">
  </div>

  <div class="form-group row">
    <label for="recipient-name" class="form-control-label col-2">Label</label>
    <input class="form-control col-4 <?= FormHelper::validateRequired($this->errors, 'label') ?>" type="text" name="attribute[label]" value="<?= $this->attribute['label'] ?>" required autocomplete="off">
  </div>

  <div class="form-group row">
    <label for="" class="col-2 col-form-label">Type</label>
    <?= FormHelper::select($this->forms['pg_types'], $this->attribute['type']) ?>
  </div>

  <div class="form-group row">
    <label for="" class="col-2 col-form-label">Length</label>
    <input class="form-control col-2" type="text" name="attribute[length]" value="<?= $this->attribute['length'] ?>">
  </div>

  <button class="btn btn-primary" type="submit"><?= LABEL_UPDATE ?></button>
  <a class="btn btn-secondary" href="<?= url_For('list') ?>" class="btn"><?= LABEL_BACK ?></a>
</form>

<? if ($this->attribute['id']): ?>
<form id="" action="<?=url_for('delete', $this->attribute['id']) ?>" method="post">
  <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
</form>
<? endif ?>