<div class="card">
  <h3 class="card-header">Attribute</h3>
  <div class="card-block">
    <form id="" action="<?= url_for('update', $this->attribute->value['id']) ?>" method="post" autocomplete="off">
      <div class="form-group row">
        <label class="form-control-label col-2">attrelid</label>
        <?= $this->attribute->value['attrelid'] ?>
      </div>

      <div class="form-group row">
        <label class="form-control-label col-2">attnum</label>
        <?= $this->attribute->value['attnum'] ?>
      </div>

      <div class="form-group row">
        <label for="" class="form-control-label col-2">Name</label>
        <?= $this->attribute->formInput('name') ?>
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Type</label>
        <?= $this->attribute->formSelect('type', ['csv' => 'pg_types']) ?>
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Length</label>
        <?= $this->attribute->formInput('length', ['class' => 'col-2']) ?>
      </div>

      <div class="form-group row">
        <label for="" class="col-2 col-form-label">Requied</label>
        <?= $this->attribute->formCheckbox('is_required') ?>
      </div>

      <div class="form-group row">
        <label for="" class="form-control-label col-2">Label</label>
        <?= $this->attribute->formInput('label') ?>
      </div>

      <div class="form-group row">
        <label for="" class="form-control-label col-2">Default value</label>
        <?= $this->attribute->formInput('default_value') ?>
      </div>

      <div class="form-group row">
        <label for="" class="form-control-label col-2">Relation CSV</label>
        <?= $this->attribute->formInput('csv') ?>
      </div>

      <? if ($this->attribute->value['fk_attribute_id']): ?>
        <div class="form-group row">
          <label for="" class="col-2 col-form-label">Update Action</label>
          <?= $this->attribute->formSelect('update_action', ['csv' => 'constraint_action', 'unselect' => true]) ?>
        </div>

        <div class="form-group row">
          <label for="" class="col-2 col-form-label">Delete Action</label>
          <?= $this->attribute->formSelect('delete_action', ['csv' => 'constraint_action', 'unselect' => true]) ?>
        </div>
      <? endif ?>

      <? if ($this->attribute->value['old_name']): ?>
        <div class="form-group row">
          <label for="" class="col-2 col-form-label">Old Column</label>
          <?= $this->attribute->value['old_name'] ?>
          &nbsp;
          <a class="btn btn-danger btn-sm" href="<?= url_for('delete_old_name', $this->attribute->value['id']) ?>"><?= LABEL_DELETE ?></a>
        </div>
      <? endif ?>

      <div class="form-group row">
        <label for="" class="form-control-label col-2">Note</label>
        <?= $this->attribute->formTextarea('note') ?>
      </div>

      <?= FormHelper::submit(LABEL_UPDATE) ?>
      <?= FormHelper::linkButton('list', LABEL_BACK) ?>

      <?= $this->attribute->formHidden('attnum') ?>

    </form>

    <?= $this->attribute->formDelete() ?>

  </div>
</div>
