<div id="help-attribute" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Attributes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body alert alert-success">
        <ul>
          <li>if you 'Import from DB', will automatically add model's information for O/R mapping from PostgreSQL.</li>
          <li>if you 'Add', create attribute's information on 'project-manager' and add attribute on PostgreSQL.</li>
          <li>The columns (id, created_at, updated_at, sort_order) is required.</li>
          <li>You can add and delete constraint on PostgreSQL.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
