<h4><?= $this->model->value['name'] ?></h4>
<form action="<?= $this->urlFor(['action' => 'add_index']) ?>" method="post">
  <table class="table table-sm">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <? foreach ($this->model->attribute->values as $attribute): ?>
    <tr>
      <td>
        <?= PwForm::checkbox([
          'name' => "attribute_id[{$attribute['id']}]",
          'label' => $attribute['name'],
          ]
          ) ?>
        </td>
      </tr>
    <? endforeach ?>
  </table>
  <input type="submit" class="btn btn-sm btn-primary" value="<?= LABEL_UPDATE ?>">
  <input type="hidden" name="model_id" value="<?= $this->model->value['id'] ?>">
</form>
