<? if ($this->pg_indexes): ?>
<div class="card">
  <div class="card-header">
    Index
    <?= PwForm::linkModal('#index_window', LABEL_ADD, 
    ['class' => 'btn btn-sm btn-primary pw-click',
    'pw-controller' => 'attribute',
    'pw-action' => 'index_list',
    'model_id' => $this->model->value['id'],
    ]) ?>
  </div>

  <div class="card-body">

    <div class="p-2">
      <? foreach ($this->pg_indexes as $pg_index): ?>
      <div class="row">
        <div class="col-6">
            <? if (strpos($pg_index['indexdef'], 'CREATE UNIQUE') === 0): ?>
            <?= $pg_index['indexname'] ?>
            <span class="badge badge-info">UNIQUE</span>
            <? else: ?>
            <?= PwForm::input(['class' => 'form-control form-control'], 'new_index_name', $pg_index['indexname']) ?>
            <? endif ?>
          <!--
            <span class="input-group-btn"><?= PwForm::button(LABEL_UPDATE, ['class' => 'btn btn-primary btn-sm confirm-dialog', 'message' => 'Do you rename Index?']) ?></span>
          -->
        </div>
        <div class="col-6">
          <!--
          <form action="<?= $this->urlFor(['action' => 'delete_index']) ?>" method="post">
            <?= PwForm::submit(LABEL_DELETE, ['class' => 'btn btn-sm btn-danger confirm-dialog', 'message' => 'Do you delete Index?']) ?></a>
            <?= PwForm::hidden('index_name', $pg_index['indexname']) ?></a>
            <?= PwForm::hidden('model_id', $this->model->value['id']) ?></a>
            <?= PwForm::hidden('database_id', $this->database->value['id']) ?></a>
          </form>
          -->
        </div>
      </div>
      <? endforeach ?>
    </div>

  </div>

</div>
<? endif ?>

<? include('index_window.phtml') ?>