<?php if ($this->pg_indexes): ?>
<div class="card">
  <div class="card-header">
    Index
    <?= PwForm::linkModal('#index_window', LABEL_ADD, 
    ['class' => 'btn btn-sm btn-primary pw-click',
    'pw-controller' => 'attribute',
    'pw-action' => 'index_list',
    'model_id' => $this->model->value['id'],
    ]) ?>
  </div>

  <div class="card-body">

    <div class="p-2">
      <?php foreach ($this->pg_indexes as $pg_index): ?>
      <div class="row">
        <div class="col-6">
          <?php if (strpos($pg_index['indexdef'], 'CREATE UNIQUE') === 0): ?>
          <?= $pg_index['indexname'] ?>
          <span class="badge badge-info">UNIQUE</span>
          <? else: ?>
          <?= PwForm::input(['class' => 'form-control form-control'], 'new_index_name', $pg_index['indexname']) ?>
          <?php endif ?>
        </div>
        <div class="col-6">
        </div>
      </div>
      <?php endforeach ?>
    </div>

  </div>

</div>
<?php endif ?>

<? include('index_window.phtml') ?>