<? include('_header.phtml') ?>

<? include('help.phtml') ?>

<div class="col-12">
  <div class="row">
    <form action="<?= $this->urlFor(['action' => 'sync_model', 'id' => $this->model->value['id']]) ?>" method="post">
      <?= PwForm::linkModal('#add-attribute', LABEL_ADD) ?>
      <?= $this->linkTo(['controller' => 'model'], ['label' => LABEL_BACK, 'class' => 'btn btn-outline-primary']) ?>
      <?= PwForm::submit('Sync DB', ['class' => 'btn btn-outline-primary confirm-dialog', 'message' => 'Do you sync from DB?']) ?>
      <?= PwForm::hidden('project_id', $this->project->value['id']) ?>
      <?= PwForm::linkModal('#php-page-export-window', 'Export', ['class' => 'btn btn-outline-primary']) ?>
    </form>

    &nbsp;
    <form action="<?= $this->urlFor(['controller' => 'page', 'action' => 'create_page_from_model']) ?>" method="post">
      <? if ($this->page->value): ?>
      <?= $this->linkTo(['controller' => 'view'],
        [
          'label' => 'View',
          'class' => 'btn btn-outline-primary',
          'http_params' => ['page_id' => $this->page->value['id']]
        ]
      )
      ?>
      <? else: ?>
      <?= PwForm::button('Create Page', ['class' => 'btn btn-outline-primary confirm-dialog', 'message' => "Do you create page from Model?"]) ?>
      <?= PwForm::hidden('model_id', $this->model->value['id']) ?>
      <? endif ?>
      <?= PwForm::linkModal('#help-attribute', 'Help', ['class' => 'btn btn-outline-primary']) ?>
    </form>
  </div>
</div>

<? include('add_window.phtml') ?>

<? include('relation_window.phtml') ?>

<? include('attributes.phtml') ?>

<? include('constraints.phtml') ?>
<? include('views/components/php_page_export_window.phtml') ?>