<div class="row car">
  <div class="card col-xs-6 col-sm-6 col-md-6">
    <div class="card-block">
      <form id="form-edit" action="<?= url_for('add') ?>" method="post" autocomplete="off">
        <div class="form-group">
          <label for="recipient-name" class="form-control-label"><?= LABEL_PAGE_NAME ?></label>
          <input class="form-control <?= FormHelper::validateRequired($this->errors, 'name') ?>" type="text" name="name" value="<?= $this->page['name'] ?>" required autocomplete="off">
        </div>

        <div class="form-group">
          <label for="recipient-name" class="form-control-label"><?= LABEL_LABEL ?></label>
          <input class="form-control <?= FormHelper::validateRequired($this->errors, 'label') ?>" type="text" name="label" value="<?= $this->page['label'] ?>" required autocomplete="off">
        </div>

      <button class="btn btn-primary" type="submit"><?= LABEL_ADD ?></button>
    </form>
  </div>
</div>
</div>
