
<h4>
    <?= FormHelper::link('#', LABEL_BACK, null,
        [
        'class' => 'pw-app btn btn-sm btn-outline-primary', 
        'pw-controller' => 'attribute',
        'pw-action' => 'relation_model_list', 
        'attribute_id' => $this->attribute->value['id'], 
        ]) ?>
</h4>
<h4 class=""><?= $this->model->value['name'] ?> -> <?= $this->attribute->value['name'] ?></h4>

<? if ($this->fk_attribute->value): ?>
<form action="<?= url_for('remove_relation') ?>" method="post">
  <?= $this->fk_model['name'] ?> -> <?= $this->fk_attribute['name'] ?>
  <input class="btn btn-sm btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  <input type="hidden" name="attribute_id" value="<?= $this->attribute['id'] ?>">
</form>
<? endif ?>

<h4><?= $this->fk_model->value['name'] ?></h4>
<table class="table table-sm">
  <? foreach ($this->fk_model->attribute->values as $fk_attribute): ?>
  <tr>
    <td><?= $fk_attribute['name'] ?></a></td>
    <td>
      <form action="<?= url_for('update_relation') ?>" method="post">
      <input type="submit" class="btn btn-sm btn-primary" value="<?= LABEL_UPDATE ?>">
        <input type="hidden" name="fk_attribute_id" value="<?= $fk_attribute['id'] ?>">
        <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
      </form>
    </td>
  </tr>
<? endforeach ?>
</table>
