<h3 class=""><?= $this->model->value['name'] ?> -> <?= $this->attribute->value['name'] ?></h3>

<? if ($this->fk_attribute->value): ?>
<form action="<?= $this->urlActionFor('remove_relation') ?>" method="post">
  
  <?= $this->fk_model->value['name'] ?> -> <?= $this->fk_attribute->value['name'] ?>

  <input class="btn btn-sm btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
</form>
<? endif ?>

<table class="table table-sm">
  <? foreach ($this->relation_model->values as $relation_model->value): ?>
  <tr>
    <td>
    <?= FormHelper::link('#relation-window',
        [
        'label' => $relation_model->value['name'],
        'class' => 'pw-app', 
        'pw-controller' => 'attribute',
        'pw-action' => 'relation_attribute_list', 
        'fk_model_id' => $relation_model->value['id'], 
        'attribute_id' => $this->attribute->value['id'], 
        ]) ?>
      </td>
    </tr>
  <? endforeach ?>
</table>
<? if (!$this->attribute->value['fk_attribute_id']): ?>

<? else: ?>
<form action="<?= $this->urlActionFor('remove_relation')?>" method="post">
  <input class="btn btn-sm btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
</form>
<? endif ?>