<h3 class="">
  <?= $this->model->value['name'] ?> ->
  <?= $this->attribute->value['name'] ?>
</h3>

<?php if ($this->fk_attribute->value): ?>
<form action="<?= $this->urlFor(['action' => 'remove_relation']) ?>" method="post">

  <?= $this->fk_model->value['name'] ?> ->
  <?= $this->fk_attribute->value['name'] ?>

  <input class="btn btn-sm btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
</form>
<?php endif ?>

<form action="<?= $this->urlFor(['action' => 'update_relation']) ?>" method="post">
<?php if ($this->candidate_model->value): ?>
<h2><?= $this->candidate_model->value['name'] ?></h2>
<table class="table table-sm">
<?php if ($this->candidate_attribute->value): ?>
<tr>
  <td>
    <?= $this->candidate_attribute->value['name'] ?>
  </td>
  <td>
    <input type="submit" class="btn btn-sm btn-primary" value="<?= LABEL_UPDATE ?>">
    <input type="hidden" name="fk_attribute_id" value="<?= $this->candidate_attribute->value['id'] ?>">
    <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
  </td>
</tr>
<?php endif ?>
<?php endif ?>
</table>
</form>

<h2>other models</h2>
<table class="table table-sm">
  <?php foreach ($this->relation_model->values as $relation_model->value): ?>
  <tr>
    <td>
      <?= $this->linkJs(
        [
        'label' => $relation_model->value['name'],
        'class' => 'pw-click', 
        'pw-controller' => 'attribute',
        'pw-action' => 'relation_attribute_list', 
        'fk_model_id' => $relation_model->value['id'], 
        'attribute_id' => $this->attribute->value['id'], 
        ]) ?>
    </td>
  </tr>
  <?php endforeach ?>
</table>

<?php if ($this->attribute->value['fk_attribute_id']): ?>
<form action="<?= $this->urlFor(['action' => 'remove_relation'])?>" method="post">
  <input class="btn btn-sm btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  <input type="hidden" name="attribute_id" value="<?= $this->attribute->value['id'] ?>">
</form>
<?php endif ?>