
<div id="unique_attribute_window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Unique</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="unique_attribute_list"></div>
      </div>
    </div>
  </div>
</div>

<?= PwTag::javascript('controllers/AttributeController') ?>
