  <table>

         
    <tr>
      <th>デフォルトプロジェクトパス</th>
      <td><%=$this->user_config['default_project_dir'] %></td>
    </tr>
                 
    <tr>
      <th>デフォルト開発URL</th>
      <td><%=$this->user_config['default_dev_url'] %></td>
    </tr>
                 
    <tr>
      <th>ユーザ</th>
      <td><%=$this->user_config['user_id'] %></td>
    </tr>
                             

  </table>

