
  <table class="table table-striped">
         
    <tr>
      <th>デフォルトプロジェクトパス</th>
      <td><input name="user_config[default_project_path]" type="text" value="<%=$this->user_config['default_project_path'] %>" size="80" /></td>
    </tr>
                 
    <tr>
      <th>デフォルト開発URL</th>
      <td><input name="user_config[default_dev_url]" type="text" value="<%=$this->user_config['default_dev_url'] %>" size="80" /></td>
    </tr>
                 
  </table>

