
  この内容でよろしいですか？
  
  <form action="<%=url_for('add', $this->user_config['id']) %>" method="post" enctype="multipart/form-data">
  <table>

         
    <tr>
      <th>デフォルトプロジェクトパス</th>
      <td><%=$this->user_config['default_project_path'] %></td>
    </tr>
                 
    <tr>
      <th>デフォルト開発URL</th>
      <td><%=$this->user_config['default_dev_url'] %></td>
    </tr>
                 
    <tr>
      <th>ユーザ</th>
      <td><%=$this->user_config['user_id'] %></td>
    </tr>
                             

  </table>

  <input type="image" src="<%=image('/btn_save.gif') %>" alt="保存" />
  <a href="<%=url_for('new') %>"><img src="<%=image('/btn_new.gif') %>" alt="戻る" /></a>
</form>
