
  <form action="<%=url_for('new_confirm', $this->user_config['id']) %>" method="post" enctype="multipart/form-data">
  <table>
         
    <tr>
      <th>デフォルトプロジェクトパス</th>
      <td><input name="user_config[default_project_path]" type="text" value="<%=$this->user_config['default_project_path'] %>" size="80" /></td>
    </tr>
                 
    <tr>
      <th>デフォルト開発URL</th>
      <td><input name="user_config[default_dev_url]" type="text" value="<%=$this->user_config['default_dev_url'] %>" size="80" /></td>
    </tr>
                 
  </table>

  <input name="user_config[id]" type="hidden" value="<%=$this->user_config['id'] %>" class="" />
  <input name="user_config[user_id]" type="text" value="<%=$this->user['id'] %>" size="" />
                            
  <input type="image" src="<%=image('/btn_confirm.gif') %>" alt="確認" />
  <a href="<%=url_for('cancel') %>"><img src="<%=image('/btn_cancel.gif') %>" alt="戻る" /></a>
  <% if ($this->user_config): %>  <br />
  <a href="<%=url_for('delete', $this->user_config['id']) %>" onclick="<%=js_post('削除してもよろしいですか？') %>"><img src="<%=image('/btn_delete.gif') %>" alt="削除" /></a>  <% endif %>
</form>
