<% include('_header.phtml') %>
<div id="user_config">

  <form id="input_form" action="<%=url_for('update', $this->user_config['id']) %>" method="post">

    <% include('_edit.phtml') %>

    <a class="btn" href="javascript:submitForm('#input_form')"><%=LABEL_UPDATE %></a>
    <a class="btn" href="<%=url_for('cancel') %>"><%=LABEL_BACK %></a>
    <% if ($this->user_config): %>
    <a class="btn" href="<%=url_for('delete', $this->user_config['id']) %>" onclick="<%=js_post(MESSAGE_DELETE) %>"><%=LABEL_DELETE %></a>
    <% endif %>

  </form>

</div>
