<? include('_header.phtml') ?>
<h3><?= $this->attribute->value['name'] ?></h3>
<form action="<?= url_for('update', $this->params['id']) ?>" method="post">

  <table class="table">
    <tr>
      <th>ラベル</th>
      <td><?= $this->view_item->formInput('label') ?></td>
    </tr>
    <tr>
      <th>Formタイプ</th>
      <td><?= $this->view_item->formInput('form_type') ?></td>
    </tr>
    <tr>
      <th>link page</th>
      <td>
        <?= $this->view_item->formSelect('page_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => '-',
          'model' => 'Page',
          'where' => "project_id = {$this->project->value['id']}"
        ]
         ) ?>
       </td>
    </tr>
    <tr>
      <th>link</th>
      <td><?= $this->view_item->formInput('link') ?></td>
    </tr>
    <tr>
      <th>css_class</th>
      <td><?= $this->view_item->formCheckbox('css_class') ?></td>
    </tr>
  </table>

  <?= FormHelper::submit(LABEL_SAVE) ?>
  <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>  
</form>
<form action="<?= url_for('delete', $this->view_item->value['id']) ?>" method="post">
  <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
</form>
