<? include('_header.phtml') ?>

<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_gets['id']]) ?>" method="post">

  <h4>Page public</h4>
  <table class="table">
    <tr>
      <th>PHP label</th>
      <td>
        <?= $this->view_item->formSelect('localize_string_id',
        [
          'unselect' => true,
          'label' => ['name'],
          'label_separate' => ' - ',
          'model' => 'LocalizeString',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
      </td>
    </tr>

    <tr>
      <th>csv</th>
      <td>
        <?= $this->view_item->formInput('csv', ['class' => 'form-control']) ?>
      </td>
    </tr>

    <tr>
      <th>display column name</th>
      <td>
        <?= $this->view_item->formInput('label_column', ['class' => 'form-control']) ?>
      </td>
    </tr>

    <tr>
      <th>css class</th>
      <td>
        <?= $this->view_item->formInput('css_class', ['class' => 'form-control']) ?>
      </td>
    </tr>

    <tr>
      <th>Note</th>
      <td>
        <?= $this->view_item->formInput('note', ['class' => 'form-control']) ?>
      </td>
    </tr>

  </table>

  <h4>Page list</h4>
  <table class="table">
    <tr>
      <th>link page</th>
      <td>
        <?= $this->view_item->formSelect('page_id',
        [
          'unselect' => true,
          'label' => ['name'],
          'label_separate' => ' - ',
          'model' => 'Page',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
      </td>
    </tr>

    <tr>
      <th>link id attribute</th>
      <td>
        <?= $this->view_item->formSelect('link_param_id_attribute_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => ' : ',
          'model' => 'Attribute',
          'where' => "model_id = {$this->page->value['model_id']}",
          'order' => 'name'
        ]
         ) ?>
      </td>
    </tr>

  </table>

  <h4>Page edit</h4>
  <table class="table">
    <tr>
      <th>form type</th>
      <td>
        <?= $this->view_item->formSelect('form_type', ['unselect' => true, 'csv' => 'form']) ?>
      </td>
    </tr>

    <tr>
      <th>Model</th>
      <td>
        <?= $this->view_item->formSelect('form_model_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => '-',
          'model' => 'Model',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
      </td>
    </tr>
    <th>condition</th>
    <td>
      <?= $this->view_item->formSelect('where_attribute_id',
      [
        'unselect' => true,
        'label' => ['name', 'label'],
        'label_separate' => '-',
        'model' => 'Attribute',
        'where' => "model_id = {$this->page->value['model_id']}",
        'order' => 'name'
      ]
       ) ?>
      =
      <?= $this->view_item->formSelect('where_model_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => '-',
          'model' => 'Model',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
      .id
    </td>
    </tr>

    <tr>
      <th>value column</th>
      <td>
        <?= $this->view_item->formInput('value_column') ?>
      </td>
    </tr>

    <tr>
      <th>order column</th>
      <td>
        <?= $this->view_item->formInput('where_order') ?>
      </td>
    </tr>

  </table>

  <?= PwForm::submit(LABEL_SAVE) ?>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
</form>
<form action="<?= $this->urlFor(['action' => 'delete', 'id' => $this->view_item->value['id']]) ?>" method="post">
  <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
</form>