<? include('_header.phtml') ?>

<form action="<?= url_for('update', $this->params['id']) ?>" method="post">

<h4>Page public</h4>
  <table class="table">
    <tr>
      <th>PHP label</th>
      <td>
        <?= $this->view_item->formSelect('localize_string_id',
        [
          'unselect' => true,
          'label' => ['name'],
          'label_separate' => ' - ',
          'model' => 'LocalizeString',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
      </td>
    </tr>

    <tr>
      <th>csv</th>
      <td><?= $this->view_item->formInput('csv') ?></td>
    </tr>

    <tr>
      <th>display column name</th>
      <td><?= $this->view_item->formInput('label_column') ?></td>
    </tr>

    <tr>
      <th>css class</th>
      <td><?= $this->view_item->formInput('css_class') ?></td>
    </tr>
  </table>

<h4>Page list</h4>
  <table class="table">
    <tr>
      <th>link page</th>
      <td>
        <?= $this->view_item->formSelect('page_id',
        [
          'unselect' => true,
          'label' => ['name'],
          'label_separate' => ' - ',
          'model' => 'Page',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
       </td>
    </tr>
  </table>

<h4>Page edit form</h4>
  <table class="table">
    <tr>
      <th>form type</th>
      <td>
        <?= $this->view_item->formRadio('form_type', ['unselect' => true, 'csv' => 'form']) ?>
      </td>
    </tr>

    <tr>
      <th>form condition</th>
      <td>
        <?= $this->view_item->formSelect('form_model_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => '-',
          'model' => 'Model',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
       </td>
    </tr>

    <tr>
      <th>form where condition</th>
      <td>
        <?= $this->view_item->formSelect('where_model_id',
        [
          'unselect' => true,
          'label' => ['name', 'label'],
          'label_separate' => '-',
          'model' => 'Model',
          'where' => "project_id = {$this->project->value['id']}",
          'order' => 'name'
        ]
         ) ?>
       </td>
    </tr>

    <tr>
      <th>form order column</th>
      <td><?= $this->view_item->formInput('where_order') ?></td>
    </tr>

    <tr>
      <th>Note</th>
      <td><?= $this->view_item->formInput('note') ?></td>
    </tr>

  </table>

  <?= FormHelper::submit(LABEL_SAVE) ?>
  <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>  
</form>
<form action="<?= url_for('delete', $this->view_item->value['id']) ?>" method="post">
  <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
</form>
