<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>

  <? include('views/components/lib/sortable.phtml') ?>

  <?= $this->linkTo(['controller' => 'view'], ['label' => LABEL_BACK, 'class' => 'btn btn-outline-primary']) ?>
  <?= $this->linkTo(['action' => 'add_all'], ['label' => LABEL_ALL.LABEL_ADD, 'class' => 'btn btn-primary']) ?>
</div>

<table id="sortable-table" class="table table-list">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>カラム</th>
      <th>リンクページ</th>
      <th>form/class</th>
      <th>items</th>
      <th></th>
    </tr>
  </thead>

  <?php if ($this->view->view_item->values): ?>
  <tbody>
    <?php foreach ($this->view->view_item->values as $view_item): ?>
    <?php if ($view_item['form_model_id']): ?>
    <? $model = DB::model('Model')->fetch($view_item['form_model_id']) ?>
    <?php endif ?>
    <tr row-id="<?= $view_item['id'] ?>">
      <td>
        <?= $this->linkTo(
            [
            'controller' => $this->pw_controller,
            'action' => 'edit',
            'id' => $view_item['id']
            ],
            [
            'label' => LABEL_EDIT,
            'class' => 'btn btn-outline-primary'
            ])
            ?>
      </td>
      <td>
        <?= $this->page->model->attribute->values[$view_item['attribute_id']]['name'] ?>
        <div>
          <small class="text-danger">
            <?= $view_item['note'] ?>
          </small>
        </div>

        <div>
          <?php if ($view_item['attribute_id']): ?>
          <?= $this->page->model->attribute->values[$view_item['attribute_id']]['label'] ?>
          <? elseif ($view_item['localize_string_id']): ?>
          <?= $this->localize_string->values[$view_item['localize_string_id']]['name'] ?>
          <?php endif ?>
        </div>
      </td>

      <td>
        <?= $this->pages[$view_item['page_id']]['name'] ?>
        <div>
          <?php if ($view_item['link_param_id_attribute_id']): ?>
          id =
          <?= DB::model('Attribute')->fetch($view_item['link_param_id_attribute_id'])->value['name'] ?>
          <?php endif ?>
        </div>
      </td>
      <td>
        <div>
          <?php if (in_array($this->view->value['name'], ['new' ,'edit'])): ?>
          <?php if ($view_item['form_type'] == 'select'): ?>
          <select class="form-control">
            <option>
              <?php if ($view_item['where_attribute_id']): ?><?= $model->value['name'] ?>.<?php endif ?>
              <?= $view_item['label_column'] ?>
            </option>
          </select>
          <? elseif ($view_item['form_type'] == 'hidden'): ?>
          hidden
          <? elseif ($view_item['form_type'] == 'radio'): ?>
          <input class="form-control" type="radio" name="">
          <?= $view_item['label_column'] ?>
          <? elseif ($view_item['form_type'] == 'checkbox'): ?>
          <input class="form-control" type="checkbox" name="">
          <?= $view_item['label_column'] ?>
          <? elseif ($view_item['form_type'] == 'textarea'): ?>
          <textarea></textarea>
          <? elseif ($view_item['form_type'] == 'password'): ?>
          <input class="form-control col-4" type="password" name="">
          <? else: ?>
          <input class="form-control col-4" type="text" name="">
          <?php endif ?>
          <?php endif ?>
        </div>
        <div>
          <?= PwForm::activeLabelTag($view_item['css_class']) ?>
        </div>
      </td>
      <td>
        <?php if ($view_item['form_model_id']): ?>
        Model: <?= $model->value['name'] ?>
        <div>
        <?php if ($view_item['where_attribute_id']): ?>
        <?= $model->value['name'] ?>.<?= DB::model('Attribute')->fetch($view_item['where_attribute_id'])->value['name'] ?>
        <?php endif ?>
        <?php endif ?>

        <?php if ($view_item['where_model_id']): ?>
        =
        <?= DB::model('Model')->fetch($view_item['where_model_id'])->value['name'] ?>.id
        <?php endif ?>
        </div>

        <?php if ($view_item['csv']): ?>csv :
        <?= $view_item['csv'] ?>
        <?php endif ?>
      </td>

      <td>
        <form action="<?= $this->urlFor(['action' => 'delete']) ?>" method="post">
          <?= PwForm::submit(LABEL_DELETE, ['class' => 'btn btn-sm btn-danger confim-dialog', 'message' => 'Delete Topic?']) ?>
          <?= PwForm::hidden('id', $view_item['id']) ?>
        </form>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
  <?php endif ?>
</table>

<table class="table table-sm">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>カラム</th>
      <th>ラベル</th>
    </tr>
  </thead>

  <?php if ($this->page->model->attribute->values): ?>
  <?php foreach ($this->page->model->attribute->values as $view_item): ?>
    <?php if (!in_array($view_item['name'], PwEntity::$app_columns)): ?>
  <tr>
    <td>
      <form action="<?= $this->urlFor(['action' => 'add_for_attribute']) ?>" method="post">
        <?= PwForm::submit(LABEL_ADD, ['class' => 'btn btn-sm btn-primary']) ?>
        <?= PwForm::hidden('view_item[attribute_id]', $view_item['id']) ?>
      </form>
    </td>
    <td>
      <?= $view_item['name'] ?>
    </td>
    <td>
      <?= $view_item['label'] ?>
    </td>
  </tr>
    <?php endif ?>
  <?php endforeach ?>
  <?php endif ?>
  </table>