<? include('_header.phtml') ?>
<form action="<?= $this->urlSelfFor('update', $this->pw_params['id']) ?>" method="post">

  <div class="card">

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>

    <div class="card-footer">
      <div class="text-left">

        <?= FormHelper::submit(LABEL_SAVE) ?>        
        <?= FormHelper::linkButton("cancel", null, ['label' => LABEL_BACK]) ?>

        <?= $this->api->confirmDelete() ?>
      </div>
    </div>

  </div>
</form>
