<? include('_header.phtml') ?>

<div id="log-window" class="pw-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h1 id="log_title" class="modal-title"></h1>
      </div>

      <div class="modal-body">
        <div id="log-contents" class="pw-load" pw-controller="pw_admin" pw-function="logList"></div>
      </div>

      <div class="modal-footer">
        <div class="card-block text-right">
          <a href="#" class="pw-lib btn btn-outline-primary" pw-lib="PwLog" pw-action="reload"><?= LABEL_RELOAD ?></a>
          <a href="#" class="pw-lib btn btn-danger" pw-lib="PwLog" pw-action="delete" message="<?= MESSAGE_DELETE ?>"><?= LABEL_DELETE ?></a>
          <button type="button" class="pw-modal-close btn btn-secondary"><?= LABEL_CLOSE ?></button>
        </div>
      </div>

    </div>
  </div>
</div>

<div id="log_list"></div>
<div id="log_detail"></div>