
<div id="add-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form method="post" action="<?= $this->urlFor('add') ?>">
        <div class="modal-header">
          <h5>Page</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group row">
            <label for="" class="col-2 col-form-label">Name</label>
            <input class="form-control col-5" type="text" name="view[name]" value="">
          </div>
          <div class="form-group row">
            <label for="" class="col-2 col-form-label">Label</label>
            <input class="form-control col-5" type="text" name="view[label]" value="">
          </div>
        </div>
        <div class="modal-footer">
          <input class="btn btn-primary" type="submit" value="<?= LABEL_UPDATE ?>">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
          <input type="hidden" name="view[page_id]" value="<?= $this->page->value['id'] ?>">
        </div>
      </form>
    </div>
  </div>
</div>