<? include('_header.phtml') ?>

<div class="card">
  <h3 class="card-header">View</h3>
  <div class="card-block">
    <form id="form-edit" action="<?= url_for('update', $this->view->value['id']) ?>" method="post" autocomplete="off">
      <div class="form-group row">
        <?= FormHelper::formLabel('Name') ?>
        <?= $this->view->formInput('name', ['class' => 'form-control']) ?>
      </div>

      <div class="form-group row">
        <?= FormHelper::formLabel('Label') ?>
        <?= $this->view->formInput('label', ['class' => 'form-control']) ?>
      </div>

      <div class="form-group row">
        <?= FormHelper::formLabel('Overwrite') ?>
        <?= $this->view->formCheckbox('is_overwrite') ?>
      </div>

      <div class="form-group row">
        <?= FormHelper::formLabel('Label Width') ?>
        <?= $this->view->formSelect('label_width', ['csv' => 'bootstrap_width', 'unselect' => true]) ?>
      </div>

      <div class="form-group row">
        <?= FormHelper::formLabel('Note') ?>
        <?= $this->view->formTextarea('note') ?>
      </div>

      <?= FormHelper::submit(LABEL_UPDATE) ?>
      <?= FormHelper::linkButton('list', null, ['label' => LABEL_CANCEL]) ?>
    </form>

    <?= $this->view->formDelete() ?>
  </div>
</div>