<? include('_header.phtml') ?>
<? include('add_window.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkModal('#add-window', LABEL_ADD) ?>
  <?= $this->linkTo(['controller' => 'page'], ['label' => LABEL_BACK, 'class' => 'btn btn-outline-primary']) ?>
</div>

<? if ($this->page->view->values): ?>
<table class="table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Overwrite</th>
    <th>URI</th>
    <th>Label Width</th>
  </tr>
  <? foreach ($this->page->view->values as $view): ?>
  <tr>
    <td>
      <?= $this->page->view->linkEdit([], $view) ?>
    </td>
    <td>
      <div>
        <?= $this->linkTo(['controller' => 'view_item'], 
                          [
                          'label' => $view['name'],
                          'http_params' => ['view_id' => $view['id']]
                          ])
        ?>
      </div>
      <div>
        <?= $view['label'] ?>
      </div>
    </td>
    <td>
      <? if ($view['is_overwrite']): ?>
      <?= $this->linkTo(['action' => 'change_overwrite', 'id' => $view['id']], ['label' => 'overwrite', 'class' => 'badge badge-danger']) ?>
      <? else: ?>
      <?= $this->linkTo(['action' => 'change_overwrite', 'id' => $view['id']], ['label' => 'off', 'class' => 'badge badge-default']) ?>
      <? endif ?>
    </td>
    <td>
      <?= $this->page->value['entity_name'] ?>
      /
      <?= $view['name'] ?>
    </td>
    <td>
      <?= $view['label_width'] ?>
    </td>
  </tr>
  <? endforeach ?>
</table>
<? endif ?>