<? include('_header.phtml') ?>

<? include('add_window.phtml') ?>

<div class="pt-3">
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#add-window"><?= LABEL_ADD ?></a>
</div>

<? if ($this->view->values): ?>
<table class="table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Label</th>
    <th>Force Wirte</th>
    <th>Page</th>
  </tr>
  <? foreach ($this->view->values as $view): ?>
  <tr>
    <td><a class="btn btn-sm btn-outline-primary" href="<?= url_for('edit', $view['id']) ?>"><?= LABEL_EDIT ?></a></td>
    <td><?= $view['name'] ?></td>
    <td><?= $view['label'] ?></td>
    <td>
      <? if ($view['is_force_write']): ?>
      <?= FormHelper::link('change_force_write', 'forced', $view['id'], ['class' => 'badge badge-danger']) ?>
      <? else: ?>
      <?= FormHelper::link('change_force_write', 'forced', $view['id'], ['class' => 'badge badge-default']) ?>
      <? endif ?>
    </td>
    <td><?= $this->page->value['entity_name'] ?>/<?= $view['name'] ?></td>
    <td>
      <? if ($view['model_id']): ?><?= $this->models[$view['model_id']]['name'] ?><? endif ?>
    </td>
  </tr>
<? endforeach ?> 
</table>
<? endif ?>
