<div class="form-group row">

      <label class="form-control-label col-2" for="name"><?= LABEL_RECORDS_NAME ?></label>
        <?= $this->record->formInput('name') ?>
</div>
<div class="form-group row">

      <label class="form-control-label col-2" for="label"><?= LABEL_RECORDS_LABEL ?></label>
        <?= $this->record->formInput('label') ?>
</div>
<div class="form-group row">
</div>

  <?= FormHelper::submit(LABEL_SAVE) ?>
  <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>  
  <input type="hidden" name="record[project_id]" value="<?= $this->project->value['id'] ?>">
