<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table id="sortable-table" class="table table-list">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>
        <?= LABEL_RECORDS_NAME ?>
      </th>
      <th>
        <?= LABEL_RECORDS_LABEL ?>
      </th>
    </tr>
  </thead>

  <? if ($this->record->values): ?>
  <? foreach ($this->record->values as $values): ?>
  <tr row-id="<?= $values['id'] ?>">
    <td>
      <?= $this->record->linkEdit([], $values) ?>
    </td>
    <td>
      <?= $this->linkTo(['controller' => 'record_item'],
                        [
                        'label' => $values['name'],
                        'http_params' => ['record_id' => $values['id']]
                        ]) ?>
    </td>
    <td>
      <?= $values['label'] ?>
    </td>
  </tr>
  <? endforeach ?>
  <? endif ?>
</table>