<? include('views/components/project_header.phtml') ?>
<? if ($this->page->value): ?>
  <h3><?= $this->page->value['label'] ?> : <?= $this->page->value['name'] ?></h3>

  <div>
    <a class="btn btn-outline-primary" href="<?= $this->linkTo('page_model/', array('page_id' => $this->page->value['id'])) ?>">Model Requests</a>
    <a class="btn btn-outline-primary" href="<?= $this->linkTo('view/', array('page_id' => $this->page->value['id'])) ?>">View</a>
  </div>
<? endif ?>