<? include('views/components/project_header.phtml') ?>

<h2>Page</h2>
<?php if ($this->page->value): ?>
  <h3>
    <?= $this->page->value['label'] ?> : <?= $this->page->value['name'] ?>
    <?= PwForm::linkModal(
      '#php-page-export-window', 'Export...',
      [
      'class' => 'btn btn-sm btn-outline-primary',
      ]
      )
      ?>
  </h3>
  <? include('views/components/php_page_export_window.phtml') ?>
<?php endif ?>