<div id="artisan_controller_window" class="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form method="post" action="<?= $this->urlFor(['action' => 'artisan']) ?>">
        <div class="modal-header">
          <h5 class="modal-title">Artisan Controller</h5>
        </div>
        <div class="modal-body">
          <dl>
            <dt>Controller</dt>
            <dd>
              <div id="artisan_name"></div>
            </dd>
            <dt>Path</dt>
            <dd>
              <?= PwForm::select([
              'name' => 'user_project_setting_id',
              'model' => 'UserProjectSetting',
              'value' => 'id',
              'label' => ['User:login_name:user_id', 'project_path'],
              'where' => "project_id = {$this->project->value['id']}",
              'label_models' => ['User' => []],
              'label_separate' => ' : '
              ]) ?>
            </dd>
          </dl>
        </div>

        <div class="modal-footer">
          <input id="is_overwrite" type="checkbox" name="is_overwrite">
          <label for="is_overwrite">Overwrite</label>
          <?= PwForm::submit(LABEL_RUN) ?>
          <?= $this->linkJs(['pw-on-click' => 'hideArtisan', 'pw-controller' => 'page', 'label' => LABEL_CLOSE, 'class' => 'btn btn-outline-primary']) ?>
        </div>

        <input id="page_id" type="hidden" name="page_id" value="<?= $this->page->value['id'] ?>">
      </form>
    </div>
  </div>
</div>