<? include('_header.phtml') ?>

<? include('add_window.phtml') ?>

<div class="pt-3">
  <form action="<?= url_for('import_from_models') ?>" method="post">
    <?= FormHelper::linkModal('#add-window', LABEL_ADD) ?>
    <?= FormHelper::submit(LABEL_IMPORT, ['class' => 'btn btn-outline-primary confirm-dialog', 'message' => 'Do you import from Models?']) ?>
    <?= FormHelper::hidden('project_id', $this->project->value['id']) ?>
  </form>
</div>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th></th>
      <th>Name</th>
      <th>Class Name</th>
      <th></th>
      <th>Overwrite</th>
      <th>Entity Name</th>
      <th>Model</th>
    </tr>
  </thead>

  <? if ($this->pages): ?>
  <? foreach ($this->pages as $page): ?>
  <tr>
    <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $page['id']) ?></td>
    <td>
      <div>
        <?= $page['name'] ?>
      </div>
      <div>
        <?= $page['label'] ?>
      </div>
    </td>
    <td><a class="" href="<?= url_for('view/', array('page_id' => $page['id'])) ?>"><?= Page::className($page) ?></a></td>
    <td><a class="" href="<?= url_for('page_model/', array('page_id' => $page['id'])) ?>">models</a></td>
    <td>
      <? if ($page['is_overwrite']): ?>
      <?= FormHelper::link('change_overwrite', 'overwrite', $page['id'], ['class' => 'badge badge-danger']) ?>
    <? else: ?>
    <?= FormHelper::link('change_overwrite', 'off', $page['id'], ['class' => 'badge badge-default']) ?>
  <? endif ?>
</td>
<td><?= $page['entity_name'] ?></td>
<td><? if ($page['model_id']): ?><?= $page['model']['name'] ?><? endif ?></td>
</tr>
<? endforeach ?> 
<? endif ?>

</table>
