<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>坝称</th>
      <th>言語</th>
    </tr>
  </thead>

  <? if ($this->lang->values): ?>
  <? foreach ($this->lang->values as $values): ?>
  <tr>
    <td><?= $this->lang->linkEdit([], $values) ?></td>
    <td><?= $values['name'] ?></td>
    <td><?= $values['lang'] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>
