<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Language</th>
    </tr>
  </thead>

  <?php if ($this->lang->values): ?>
  <?php foreach ($this->lang->values as $values): ?>
  <tr>
    <td><?= $this->lang->linkEdit([], $values) ?></td>
    <td><?= $values['name'] ?></td>
    <td><?= $values['lang'] ?></td>
  </tr>
  <?php endforeach ?>
  <?php endif ?>

</table>
