<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', LABEL_ADD, null, ['class' => 'btn btn-primary']) ?>
  <?= FormHelper::linkButton('sort_order', LABEL_SORT_ORDER) ?>
</div>

<table class="table">
  <thead class="thead-deffault">
    <tr>
      <th>&nbsp;</th>
      <th>名称</th>
      <th>言語</th>
    </tr>
  </thead>

  <? if ($this->lang->values): ?>
  <? foreach ($this->lang->values as $values): ?>
  <tr>
    <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $values['id']) ?></td>
    <td><?= $values['name'] ?></td>
    <td><?= $values['lang'] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>
