<? include('_header.phtml') ?>
<form action="<?= $this->linkTo('add') ?>" method="post">

  <table class="table">

    <tr>
      <th>坝称</th>
      <td>
        <?= $this->lang->formInput('name') ?>        
      </td>
    </tr>

    <tr>
      <th>言語</th>
      <td>
        <?= $this->lang->formInput('lang') ?>        
      </td>
    </tr>

  </table>

  <?= FormHelper::submit(LABEL_SAVE) ?>
  <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?></form>