<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'add']) ?>" method="post">

  <table class="table">
    <tr>
      <th>Name</th>
      <td>
        <?= $this->lang->formInput('name') ?>        
      </td>
    </tr>
    <tr>
      <th>Language</th>
      <td>
        <?= $this->lang->formInput('lang') ?>        
      </td>
    </tr>
  </table>

  <?= PwForm::submit(LABEL_SAVE) ?>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?></form>