<div class="col-12">
  <div class="row">

    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-element">
          <?= PwTag::a(
            [
              'label' => LABEL_GRAPH,
              'class' => 'pw-click nav-link',
              'pw-controller' => $this->js_controller,
              'pw-action' => 'default_depth_graph',
              'selected_controller' => $this->pw_controller,
              'selected_action' => 'depth_graph',
            ]
          )
          ?>
        </li>
        <li class="nav-item nav-element">
          <?= PwTag::a(
            [
              'label' => LABEL_LIST,
              'class' => 'pw-click nav-link',
              'pw-controller' => $this->js_controller,
              'pw-action' => 'default_depth_list',
              'selected_controller' => $this->pw_controller,
              'selected_action' => 'depth_list',
            ]
          )
          ?>
        </li>
      </ul>
    </nav>

    <nav class="navbar bg-faded">
      <ul class="nav nav-pills">
        <li class="nav-item nav-title">
          <?= LABEL_DOWNLOAD ?>
        </li>
        <li class="nav-item nav-element">
          <?= PwTag::a(
            [
              'label' => LABEL_GRAPH,
              'icon_name' => 'download',
              'class' => 'pw-click btn btn-outline-primary',
              'message' => MESSAGE_DOWNLOAD,
              'pw-controller' => $this->js_controller,
              'pw-action' => 'graph_download',
            ]
          )
          ?>
          <?= PwTag::a(
            [
              'label' => LABEL_CSV,
              'icon_name' => 'download',
              'class' => 'pw-click btn btn-outline-primary',
              'message' => MESSAGE_DOWNLOAD,
              'pw-controller' => $this->js_controller,
              'pw-action' => 'csv_download',
            ]
          )
          ?>
          <?= PwTag::a([
            'class' => 'pw-click btn btn-outline-primary',
            'label' => LABEL_BATCH_DOWNLOAD,
            'pw-controller' => 'batchdownload',
            'pw-action' => 'setting',
            'spot_id' => $this->spot->value['id'],
            'batchdownload_type' => $this->instrument_type.'_group',
            'icon_name' => 'file-archive',
          ]); ?>
        </li>
      </ul>
    </nav>
  </div>

</div>

<? include('views/batchdownload/depth_graph.phtml') ?>