<? if ($this->isDeveloper()): ?>
<nav class="navbar bg-faded text-nowrap">
  <ul class="nav nav-pills">
    
    <li class="nav-item">
      <?= $this->linkTo(['action' => 'default_measure'],
        [
          'class' => 'nav-link',
          'label' => LABEL_TIME_SERIES,
          'icon_name' => 'chart-bar',
          'is_use_selected' => true,
          'menu_group' => 'measure',
        ]
      )
      ?>
    </li>

    <li class="nav-item">
      <?= $this->linkTo(['action' => 'default_group_measure'],
        [
          'class' => 'nav-link',
          'label' => LABEL_TIME_SERIES_GROUP,
          'icon_name' => 'chart-bar',
          'is_use_selected' => true,
          'menu_group' => 'measure_group',
        ]
      )
      ?>
    </li>

    <!-- TODO depth flag? -->
    <? if ($this->instrument_type == 'slope' || $this->instrument_type == 'pipe'): ?>
    <li class="nav-item">
        <?= $this->linkTo(['action' => 'default_depth'],
          [
            'label' => LABEL_INSTRUMENTS_DEPTH,
            'icon_name' => 'chart-area',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'menu_group' => 'depth_graph',
          ]
        )
        ?>
      </li>
      
      <li class="nav-item">
        <?= $this->linkTo(['action' => 'default_depth_time'],
          [
            'label' => LABEL_INSTRUMENTS_DEPTH.'('.LABEL_TIME_SERIES.')',
            'icon_name' => 'chart-area',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'menu_group' => 'depth_time_graph',
          ]
        )
        ?>
      </li>
    <? endif ?>

    <li class="nav-item">
      <?= $this->linkTo(['action' => 'default_displace'],
        [
          'class' => 'nav-link',
          'label' => LABEL_DISPLACE,
          'icon_name' => 'chart-line',
          'is_use_selected' => true,
          'menu_group' => 'displace',
        ]
      )
      ?>
    </li>

  </ul>
</nav>
<? endif ?>