<? include('views/components/login_user.phtml') ?>

<nav id="header" class="navbar navbar-toggleable fixed-top">

  <div>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapsea" data-target="#nav-header"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
        <i class="fa fa-bars"></i>
      </span>
    </button>
  </div>

  <div class="collapse navbar-collapse text-nowrap" id="nav-header">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'observe_spot',
          'action' => 'list',
          ],
          [
            'label' => LABEL_SPOTS,
            'class' => 'nav-link action-loading',
            'icon_name' => 'home',
            'is_use_selected' => true,
            'is_not_pw_multi_sid' => true,
          ]
        )
        ?>
      </li>

      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'observe_alert'],
            [
              'label' => LABEL_OBSERVE,
              'class' => 'nav-link',
              'icon_name' => 'desktop',
              'is_use_selected' => true,
              'is_not_pw_multi_sid' => true,
            ]
          )
          ?>
      </li>

      <li class="nav-item">
        <?= $this->linkTo(['controller' => 'observe_rainfall_area'],
          [
            'label' => LABEL_RAINFALL_AREAS,
            'class' => 'nav-link action-loading',
            'icon_name' => 'umbrella',
            'is_use_selected' => true,
            'is_not_pw_multi_sid' => true,
          ]
        )
        ?>
      </li>

      <li class="nav-item dropdown text-nowrap">
        <?= PwTag::a(
            [
              'id' => 'dropdown-message',
              'class' => 'nav-link dropdown-toggle',
              'label' => LABEL_MESSAGES,
              'icon_name' => 'desktop',
              'href' => '#',
              'data-toggle' => 'dropdown',
              'aria-haspopup' => 'true',
              'aria-expanded' => 'false',
              'is_use_selected' => true,
              'selected_key' => 'message',
              'selected_value' => $this->pw_controller,
            ]
          )
          ?>
        <div class="dropdown-menu" aria-labelledby="dropdown-weather">
          <?= $this->linkTo(['controller' => 'message'], 
              [
                'label' => LABEL_LIST,
                'class' => 'nav-link',
                'icon_name' => 'list',
                'is_not_pw_multi_sid' => true,
              ]
            )
            ?>
          <?= $this->linkTo(
              [
              'controller' => 'message',
              'action' => 'new'
              ], 
              [
                'label' => LABEL_ADD,
                'class' => 'nav-link',
                'icon_name' => 'edit',
                'is_not_pw_multi_sid' => true,
              ]
            )
            ?>
        </div>
      </li>

      <? if ($this->pw_auth->value['is_admin']): ?>
      <li class="nav-item nav-border">
        <?= $this->linkTo(['controller' => 'root'],
            [
              'label' => LABEL_ADMIN,
              'class' => 'nav-link',
              'icon_name' => 'cogs',
              'is_use_selected' => true,
              'is_not_pw_multi_sid' => true,
            ]
          )
          ?>
      </li>
      <? endif ?>
    </ul>
    <div class="p-2 text-nowrap">

      <?= $this->linkTo(['controller' => 'root'],
          [
            'label' => LABEL_JA,
            'class' => 'pl-2',
            'is_not_pw_multi_sid' => true,
            'http_params' => ['lang' => 'ja', 'is_change_lang' => 1]
          ]
        )
        ?>
      <?= $this->linkTo(['controller' => 'root'],
          [
            'label' => LABEN_EN,
            'class' => 'pl-2',
            'is_not_pw_multi_sid' => true,
            'http_params' => ['lang' => 'en', 'is_change_lang' => 1]
          ]
        )
        ?>

      <?= PwTag::a(
          [
          'icon_name' => 'address-card',
          'data-toggle' => 'modal',
          'data-target' => '#login_user',
          ]) ?>

      <?= $this->linkTo(
        [
        'controller' => 'staff',
        'action' => 'logout',
        ],
        [
          'class' => 'confirm-dialog',
          'label' => LABEL_LOGOUT,
          'message' => MESSAGE_LOGOUT,
          'icon_name' => 'sign-out-alt',
          'is_not_pw_multi_sid' => 1,
        ]) ?>
    </div>

  </div>
</nav>