<div class="modal delete-file-window">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="from-delete-title"><?= LABEL_DELETE ?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 class="modal-title"></h5>
        <?= MESSAGE_DELETE ?>
      </div>
      <div class="modal-footer">
        <?= $this->linkJs(
              [
              'id' => 'link_delete_image',
              'class' => 'pw-click btn btn-danger',
              'label' => LABEL_DELETE,
              'message' => MESSAGE_DELETE,
              ]
            ) ?>
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>

      </div>
    </div>
  </div>
</div>