<div id="delete-file-window" class="pw-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="from-delete-title"><?= LABEL_DELETE ?></h5>
        <button type="button" class="pw-modal-close close" selector="delete-file-window" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 class="modal-title"></h5>
        <?= MESSAGE_DELETE ?>
      </div>
      <div class="modal-footer">
          <?= $this->linkJs(
            [
            'id' => 'link_delete_file',
            'class' => 'pw-click btn btn-danger',
            'label' => LABEL_DELETE,
            'message' => MESSAGE_DELETE,
            ]
          ) ?>
        <button type="button" class="pw-modal-close btn btn-secondary" selector="delete-file-window"><?= LABEL_CLOSE ?></button>
      </div>
    </div>
  </div>
</div>