<?php if ($this->errors): ?>
  <div id="pw-error" class="pw-modal error-window" event="load" action="show">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><?= LABEL_ERROR ?></h5>
          <button type="button" class="pw-modal-close close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul class="list-unstyled">
            <?php if (is_array($this->errors)): ?>
              <?php foreach ($this->errors as $key => $error): ?>
                <?php if (is_array($error)): ?>
                <?php foreach ($error as $key2 => $value): ?>
                  <li><?= PwError::display($value, $this->pw_gets, $key)?></li>
                <?php endforeach?>
                <? else: ?>
                  <li><?= PwError::displayForString($error, $this->pw_gets, $key) ?></li>
                <?php endif ?>
              <?php endforeach?>
            <?php endif ?>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="pw-modal-close btn btn-secondary" selector="pw-error"><?= LABEL_CLOSE ?></button>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>