<div class="php_error">
    <div class="card">
      <div class="card-header">
        <h3>Error</h3>
      </div>
  
      <div class="alert alert-danger">
        <?php print_r($errors) ?>
      </div>
      <div class="card-block">
        <table class="table">
        <?php foreach ($errors as $key => $error) : ?>
        <?php if ($key == 'request') : ?>
          <tr>
            <th><?= $key ?></th>
            <td>
              <dl>
          <?php foreach ($error as $param_key => $param) : ?>
              <dt><?= $key ?></dt>
              <dd><?= $param ?></dd>
          <?php endforeach ?>
              </dl>
            </td>
          </tr>
        <? else : ?>
          <tr>
            <th><?= $key ?></th>
            <td><?= $error ?></td>
          </tr>
        <?php endif ?>
        <?php endforeach ?>
        </table>
      </div>
  
    </div>
  </div>
  