
<p id="pw-scroller-top" class="pw-scroller" pw-action="top"><a><?= TagHelper::iconTag('angle-double-up'); ?></a></p>
<p id="pw-scroller-up" class="pw-scroller" pw-action="up"><a><?= TagHelper::iconTag('angle-up'); ?></a></p>
<p id="pw-scroller-down" class="pw-scroller" pw-action="down"><a><?= TagHelper::iconTag('angle-down'); ?></a></p>
<p id="pw-scroller-bottom" class="pw-scroller" pw-action="bottom"><a><?= TagHelper::iconTag('angle-double-down'); ?></a></p>
<span id="pw_scroller_end"></span>

<?= TagHelper::stylesheet('pw_scroller') ?>