<a id="pw_sortable_edit_btn" class="btn btn-outline-primary pw-lib" pw-lib="PwSortable" pw-action="edit"><?= PwTag::iconTag('sort') ?><?= LABEL_SORT_ORDER ?></a>
&nbsp;
<a id="pw_sortable_update_btn" class="btn btn-primary pw-lib pw-sortable-control" pw-lib="PwSortable" pw-controller="<?= $this->name ?>" pw-action='update_sort' style="display: none"><?= PwTag::iconTag('save') ?><?= LABEL_UPDATE ?></a>
&nbsp;
<a id="pw_sortable_close_btn" class="btn btn-outline-primary pw-lib pw-sortable-control" pw-lib="PwSortable" pw-action="reset" style="display: none"><?= PwTag::iconTag('times') ?><?= LABEL_CLOSE ?></a>