
<div class="hero-unit">

  <table class="table">
    <tr>
      <th>command</th>
      <td><?= $this->results['cmd'] ?></td>
    </tr>
    <? foreach ($this->results['output'] as $value): ?>
    <tr>
      <th></th>
      <td><?= $value ?></td>
    </tr>
    <? endforeach ?>
    <tr>
      <th>return</th>
      <td><?= $this->results['return'] ?></td>
    </tr>
  </table>

  <a href="<?= url_for('/index') ?>"><?= LABEL_BACK ?></a>
</div>

