<h2>Setting</h2>

<div class="hero-unit">
  <? if ($this->pgsql_entity->is_connection_error) : ?>
    <div class="alert alert-danger">
      <p>
        Not Found project-manager's database '<?= DB_NAME ?>' on PostgreSQL
      </p>
      <p>createdb <?= DB_NAME ?></p>
      <p>
        * If you want createdb on browser, please set the permission on pg_hba.conf, postgresql.conf
      </p>
      <a class="btn btn-primary" href="<?= $this->urlFor(['action' => 'create_database']) ?>" onClick="return confirm('createdb for PostgreSQL?')">Create Database</a>
    </div>
  <? endif ?>

  <? if (!$this->database->is_success) : ?>
    <div class="alert alert-danger">
      Not Found <?= DB_NAME ?>'s tables.
      <?= $this->linkTo(['action' => 'pgsql'], ['label' => 'Create Table', 'class' => 'btn btn-primary']) ?>
    </div>
  <? endif ?>

  <div class="alert alert-success">
    <h1>Hello, project-manager! </h1>
    <p>
      'project-manager' is PostgreSQL manager and generates PHP files(MVC) by PHP frame work 'php-work'.
    </p>
    <h2>Required</h2>
    <ul>
      <li>PHP 7.x</li>
      <li>PostgreSQL 9.x</li>
      <li><a href="https://github.com/yoo16/phpwork" target="_blank">php-work</a></li>
    </ul>
    <p>
      <dl>
        <dd>* please create setting file 'app/settings/<?= $this->hostname ?>.php' </dd>
        <dd>* If you want manage PostgreSQL on browser, please set the permission on pg_hba.conf, postgresql.conf. </dd>
        <dd>
          * project-manager need database '<?= DB_NAME ?>' by PostgreSQL 9.x.
          <p>
            $ createdb project_manager
          </p>
          *DB setting file'path is <?= DB_SETTING_FILE ?>'.
        </dd>
        <dd>* If you export PHP files(Model, Controller, View etc...) by project-manager, please download PHP Framework
          '<a href="https://github.com/yoo16/phpwork" target="_blank">php-work</a>'.</dd>
      </dl>
    </p>
    <a class="btn btn-primary" href="<?= PHP_WORK_GIT_URL ?>" target="_blank">Download php-work(GitHub)</a>
  </div>

  <h2>setting file</h2>
  <div class="alert alert-success">
    app/settings/<?= $this->hostname ?>.php
  </div>
  <pre>
define('PROJECT_NAME', 'project-manager');
define('LOG_DIR', BASE_DIR.'log/');

ini_set('error_log', LOG_DIR.date('Ymd').'.log');
ini_set('display_errors', false);
ini_set('log_errors', true);
error_reporting(E_ALL & ~E_NOTICE);

define('PROJECT_DIR', BASE_DIR);
define('TMP_DIR', BASE_DIR . 'tmp/');
define('DB_DIR', BASE_DIR.'db/');

define('DEBUG', true);
define('SQL_LOG', false);

//shell
define('COMAND_PHP_PATH', '/usr/bin/php');

//Database Host
define('DB_HOSTS_CSV', DB_DIR.'db_info/db_hosts.csv');
define('DB_USERS_CSV', DB_DIR.'db_info/db_users.csv');
define('DB_PORTS_CSV', DB_DIR.'db_info/db_ports.csv');
</pre>

  <h3>PHP define</h3>
  <table class="table">
    <tr>
      <th>PROJECT_NAME</th>
      <td><?= undefineLabel('PROJECT_NAME', PROJECT_NAME) ?></td>
    </tr>
    <tr>
      <th>PROJECT_DIR</th>
      <td><?= undefineLabel('PROJECT_DIR', PROJECT_DIR) ?></td>
    </tr>
    <tr>
      <th>LOG_DIR</th>
      <td><?= undefineLabel('LOG_DIR', LOG_DIR) ?></td>
    </tr>
    <tr>
      <th>DB_DIR</th>
      <td><?= undefineLabel('DB_DIR', DB_DIR) ?></td>
    </tr>
    <tr>
      <th>TMP_DIR</th>
      <td><?= undefineLabel('TMP_DIR', TMP_DIR) ?></td>
    </tr>
    <tr>
      <th>DEBUG</th>
      <td><?= undefineLabel('DEBUG', DEBUG) ?></td>
    </tr>
    <tr>
      <th>SQL_LOG</th>
      <td><?= undefineLabel('SQL_LOG', SQL_LOG) ?></td>
    </tr>
    <tr>
      <th>COMAND_PHP_PATH</th>
      <td><?= undefineLabel('COMAND_PHP_PATH', COMAND_PHP_PATH) ?></td>
    </tr>
    <tr>
      <th>DB_HOSTS_CSV</th>
      <td><?= undefineLabel('DB_HOSTS_CSV', DB_HOSTS_CSV) ?></td>
    </tr>
    <tr>
      <th>DB_USERS_CSV</th>
      <td><?= undefineLabel('DB_USERS_CSV', DB_USERS_CSV) ?></td>
    </tr>
    <tr>
      <th>DB_HOSTS_CSV</th>
      <td><?= undefineLabel('DB_HOSTS_CSV', DB_HOSTS_CSV) ?></td>
    </tr>
  </table>

  <h2>PostgreSQL</h2>

  <div class="alert alert-success">
    <?= DB_SETTING_FILE ?>
  </div>
  <pre>
define('DB_NAME', 'project_manager');
define('DB_HOST', 'localhost');
define('DB_USER', 'postgres');
define('DB_PORT', '5432');
define('DB_PASS', '');
</pre>

  <h3>PHP define</h3>
  <table class="table">
    <tr>
      <th>DB_NAME</th>
      <td>
        <?= undefineLabel('DB_NAME', DB_NAME) ?>
      </td>
    </tr>
    <tr>
      <th>DB_HOST</th>
      <td><?= undefineLabel('DB_HOST', DB_HOST) ?></td>
    </tr>
    <tr>
      <th>DB_NAME</th>
      <td><?= undefineLabel('DB_PORT', DB_PORT) ?></td>
    </tr>
    <tr>
      <th>DB_USER</th>
      <td><?= undefineLabel('DB_USER', DB_USER) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
        <? if ($this->pg_connection) : ?>
          <?= $this->pg_connection ?>
        <? else : ?>
          <?= undefineLabelTag() ?>
        <? endif ?>
      </td>
    </tr>
  </table>