
<div class="hero-unit">
  <div class="alert alert-success">
    <h1>Hello, project-manager! </h1>
    <h2>Required</h2>
    <ul>
      <li>PHP 7.x</li>
      <li>PostgreSQL 9.x</li>
      <li><a href="https://github.com/yoo16/phpwork" target="_blank">php-work</a></li>
    </ul>
    <p>
      <dl>
        <dd>* If you want control PostgreSQL on browser, please set the permission on pg_hba.conf, postgresql.conf </dd>
        <dd>* If you export php files(Model, Controller, View etc...) by project-manager, please download PHP Framework '<a href="https://github.com/yoo16/phpwork" target="_blank">php-work</a>'.</dd>
      </dl>
    </p>
    <a class="btn btn-primary" href="<?= PHP_WORK_GIT_URL ?>" target="_blank">Download php-work(GitHub)</a>
  </div>

  <? if ($this->pgsql_entity->is_connection_error): ?>
  <div class="alert alert-danger">
    Not Found project-manager's database '<?= DB_NAME ?>'
    <p>createdb <?= DB_NAME ?></p>
    <a class="btn btn-primary" href="<?= url_for('create_database') ?>" onClick="return confirm('createdb for PostgreSQL?')">Create Database</a>
    * If you want createdb on browser, please set the permission on pg_hba.conf, postgresql.conf
  </div>
<? endif ?>

<? if ($this->database->is_not_has_tables): ?>
<div class="alert alert-danger">
  Not Found <?= DB_NAME ?>'s tables.
  <a class="btn btn-primary" href="<?= url_for('pgsql') ?>">Create Table</a>
</div>
<? endif ?>
<h2>PostgreSQL</h2>
<div class="alert alert-success">
  *DB setting file'path is <?= DB_SETTING_FILE ?>'.
</div>
<table class="table">
  <tr>
    <th>DB_NAME</th>
    <td>
      <?= undefineLabel('DB_NAME', DB_NAME) ?>
    </td>
  </tr>
  <tr>
    <th>DB_HOST</th>
    <td><?= undefineLabel('DB_HOST', DB_HOST) ?></td>
  </tr>
  <tr>
    <th>DB_NAME</th>
    <td><?= undefineLabel('DB_PORT', DB_PORT) ?></td>
  </tr>
  <tr>
    <th>DB_USER</th>
    <td><?= undefineLabel('DB_USER', DB_USER) ?></td>
  </tr>
  <tr>
    <th>pg_connection()</th>
    <td>
      <? if ($this->pg_connection): ?>
      <?= $this->pg_connection ?>
    <? else: ?>
    <?= undefineLabelTag() ?>
  <? endif ?>
</td>
</tr>
</table>

