
<div class="hero-unit">

  <h2>PostgreSQL</h2>
  <table class="table">
    <tr>
      <th>DB_NAME</th>
      <td><?= undefineLabel('DB_NAME', DB_NAME) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
        <?php if ($this->pg_connection): ?>
        <label class="badge badge-success">connected</label>
      <? else: ?>
      <?= undefineLabelTag() ?>
    <?php endif ?>
  </td>
</tr>
</table>

<h3>Create Table SQL</h3>
<div class="card">
  <div class="card-block overflow-list">
    <?php if ($this->sql_files): ?>
    <?php foreach ($this->sql_files as $sql_file): ?>
    <?= nl2br($sql_file) ?>
    <?php endforeach ?>
    <? else: ?>
    <?= undefineLabelTag() ?>
    <?php endif ?>
  </div>

  <div class="card-footer text-center">
    <?php if (!$this->pg_connection): ?>
    <a class="btn btn-primary confirm-dialog" href="<?= $this->urlFor(['action' => 'create_database']) ?>" message="createdb for PostgreSQL?"><?= LABEL_CREATE ?></a>
  <? else: ?>
  <?php if ($this->sql_files): ?>
  <a class="btn btn-primary confirm-dialog" href="<?= $this->urlFor(['action' => 'create_tables']) ?>" message="Init Database? *Data will be deleted on database."><?= LABEL_UPDATE ?></a>
  <?php endif ?>
<?php endif ?>
  <a class="btn btn-outline-primary" href="<?= $this->urlFor(['action' => 'index']) ?>"><?= LABEL_BACK ?></a>
</div>
</div>

</div>

