
<div class="hero-unit">

  <h2>PostgreSQL</h2>
  <table class="table">
    <tr>
      <th>DB_NAME</th>
      <td><?= undefineLabel('DB_NAME', DB_NAME) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
        <? if ($this->pg_connection): ?>
        <label class="badge badge-success">connected</label>
      <? else: ?>
      <?= undefineLabelTag() ?>
    <? endif ?>
  </td>
</tr>
</table>

<h3>Create Table SQL</h3>
<div class="card">
  <div class="card-block overflow-list">
    <? if ($this->sql): ?><?= nl2br($this->sql) ?><? else: ?><?= undefineLabelTag() ?><? endif ?>
  </div>

  <div class="card-footer text-center">
    <? if (!$this->pg_connection): ?>
    <a class="btn btn-primary confirm-dialog" href="<?= $this->linkTo('create_database') ?>" message="createdb for PostgreSQL?"><?= LABEL_CREATE ?></a>
  <? else: ?>
  <? if ($this->sql): ?>
  <a class="btn btn-primary confirm-dialog" href="<?= $this->linkTo('create_tables') ?>" message="Init Database? *Data will be deleted on database."><?= LABEL_UPDATE ?></a>
<? endif ?>
<? endif ?>
  <a class="btn btn-outline-primary" href="<?= $this->linkTo('index') ?>"><?= LABEL_BACK ?></a>
</div>
</div>

</div>

