<table>
  <tr>
    <th>プロジェクト名</th>
    <th>作成日</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

  <% if (is_array($this->releases)): %> 

  <% foreach ($this->releases as $key => $release): %> 
  <tr>
    <td><a href="<%=$this->project['dev_url'] %>release/<%=$release %>/" class="popup"><%=$release %></a></td>
    <th><%=convertDatestr2At($release) %></th>
    <td><a href="<%=url_for('project/download_publish', array('id' => $this->project['id'], 'key' => $release)) %>">ダウンロード</a></td>
    <td><a href="<%=url_for('project/delete_publish', array('id' => $this->project['id'], 'key' => $release)) %>">削除</a></td>
  </tr>
  <% endforeach %> 

  <% endif %> 

</table>
