
<div id="add-project-path-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <form id="" action="<?=url_for('add_user_project_setting') ?>" method="post">
    <div class="modal-dialog" role="document">

      <div class="modal-content">

        <div class="modal-header">
        <h3>Project Path</h3>
        </div>

        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Project path</label>
            <input class="form-control" name="user_project_setting[project_path]" type="text" value="<?= $this->user_project_setting['project_path'] ?>" placeholder="/home/users/<?= $this->project['name'] ?>/">
          </div>
        </div>

        <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="<?= LABEL_ADD ?>">
          <button type="button" class="btn btn-outline-primary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
          <input class="" name="user_project_setting[project_id]" type="hidden" value="<?= $this->project['id'] ?>">
        </div>

      </div>

    </div>
  </form>
</div>
