
<div id="add-project-path-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <form id="" action="<?=url_for('add_user_project_setting') ?>" method="post">
    <div class="modal-dialog" role="document">

      <div class="modal-content">

        <div class="modal-header">
        <h3>Local project path</h3>
        </div>

        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Project path</label>
            <?= DB::model('UserProjectSetting')->formInput('project_path', ['class' => 'form-control', 'placeholder' => '/home/users/project_name/']) ?>
          </div>
        </div>

        <div class="modal-footer">
          <?= FormHelper::submit(LABEL_ADD) ?>
          <?= FormHelper::button(LABEL_CLOSE, ['class' => 'btn btn-outline-primary', 'data-dismiss' => 'modal']) ?>
          <?= FormHelper::hidden('user_project_setting[project_id]', $this->project->value['id']) ?>
        </div>

      </div>

    </div>
  </form>
</div>
