<div id="add-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form method="post" action="<?= $this->urlFor(['action' => 'add']) ?>">
        <div class="modal-header">
          <h5 class="modal-title">Project</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <dl>
            <dt>Name</dt>
            <dd>
              <?= DB::model('Project')->formInput('name', [ 'class' => 'form-control' ]) ?>
            </dd>
            <dt>Database</dt>
            <dd>
              <?= DB::model('Project')->formSelect('database_id', 
            [
            'values' => $this->database->values,
            'value' => 'id', 'label' => 'name',
            'class' => 'form-control',
            'unselect' => true
            ]
            ) ?>
            </dd>
            <dt>Project Path</dt>
            <dd>
              <?= DB::model('UserProjectSetting')->formInput('project_path', [ 'class' => 'form-control' ]) ?>
            </dd>
          </dl>
        </div>

        <div class="modal-footer">
          <?= PwForm::submit(LABEL_ADD) ?>
          <?= $this->linkJs(['label' => LABEL_CLOSE, 'class' => 'btn btn-outline-primary', 'data-dismiss' => 'modal']) ?>
        </div>
      </form>
    </div>
  </div>
</div>