<? include('_header.phtml') ?>

<form id="" action="<?= url_for('update_user_project_setting', $this->user_project_setting->value['id']) ?>" method="post">
  <div class="form-group row">
    <label for="recipient-name" class="col-2 col-form-label">Project path</label>
    <input class="form-control col-5" name="user_project_setting[project_path]" type="text" value="<?= $this->user_project_setting->value['project_path'] ?>">
  </div>
  <div class="">
    <?= FormHelper::submit(LABEL_UPDATE) ?>
    <?= FormHelper::linkButton('export_list', LABEL_CLOSE, $this->project->value['id']) ?>
  </div>
</form>

<?= $this->user_project_setting->formDelete('delete_user_project_setting') ?>
