<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_gets['id']]) ?>" method="post">

  <table class="table table-list">
    <tr>
      <th>
        <?= PwForm::formLabel('Name', ['class' => 'col-2']) ?>
      </th>
      <td>
        <?= $this->project->formInput('name', ['class' => 'form-control']) ?>
      </td>
    </tr>
    <tr>
      <th>
        <?= PwForm::formLabel('Database', ['class' => 'col-2']) ?>
      </th>
      <td>
        <?= $this->project->formSelect('database_id', ['model' => 'Database', 'label' => 'name']) ?>
      </td>

    </tr>
  </table>

  <?= PwForm::submit(LABEL_UPDATE) ?>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
  <?= $this->project->confirmDelete() ?>
</form>