<? include('_header.phtml') ?>

<table class="table">
  <tr>
    <th>project name</th>
    <td><?= $this->project['name'] ?></td>
  </tr>
</table>

<h3>project path</h3>
<form id="" action="<?= url_for('update_user_project_setting', $this->user_project_setting['id']) ?>" method="post">
  <input class="form-control" name="user_project_setting[project_path]" type="text" value="<?= $this->user_project_setting['project_path'] ?>">
  <input class="btn btn-primary" type="submit" value="<?= LABEL_UPDATE ?>">
  <a class="btn btn-secondary" href="<?= url_for('export_list', $this->project['id']) ?>"><?= LABEL_CLOSE ?></a>
</form>

<form id="" action="<?= url_for('delete_user_project_setting', $this->user_project_setting['id']) ?>" method="post">
  <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
</form>
