<? include('_header.phtml') ?>

<h2>Project Setting</h2>
<div class="pt-3">
  <?= PwForm::linkModal('#add_project_path_window', LABEL_ADD) ?>
  <?= PwForm::linkButton(['action' => 'list'], ['label' => LABEL_BACK]) ?>
</div>

<? include('add_project_path_window.phtml'); ?>

<table class="table">
  <thead class="thead-default">
    <tr>
      <td></td>
      <td>Local project path</td>
      <td>Exists</td>
    </tr>
  </thead>
  <? if (is_array($this->project->user_project_setting->values)): ?>
  <tbody>
    <? foreach ($this->project->user_project_setting->values as $user_project_setting): ?>
    <tr>
      <td>
        <?= $this->linkTo(
        [ 'controller' => 'user_project_setting', 'action' => 'edit', 'id' => $user_project_setting['id'] ],
        [ 'class' => 'btn btn-outline-primary', 'label' => LABEL_EDIT] 
        ) ?>
      </td>
      <td><?= $user_project_setting['project_path'] ?></td>
      <td>
        <? if (file_exists($user_project_setting['project_path'])): ?>
        <? if (file_exists($user_project_setting['project_path']."app/")): ?><label class="badge badge-success">exists</label><? else: ?>
        <label class="badge badge-danger">not found php-work</label>
        <div>
          <a href="<?= PHP_WORK_GIT_URL ?>" target="_blank"><?= PHP_WORK_GIT_URL ?></a>
        </div>
      <? endif ?>
    <? else: ?>
    <label class="badge badge-danger">not exists</label>
  <? endif ?>
</td>
</tr>
<? endforeach ?>
<? endif ?>
</tbody>
</table>
