<? include('_header.phtml') ?>

<div class="pt-3">
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#add-project-path-window"><?= LABEL_ADD ?></a>
  <a href="<?= url_for('list') ?>" class="btn btn-outline-primary"><?= LABEL_BACK ?></a>
</div>

<? include('add_project_path_window.phtml'); ?>

<table class="table">
  <thead class="thead-default">
    <tr>
      <td></td>
      <td>Path</td>
      <td>Exists</td>
    </tr>
  </thead>
  <? if (is_array($this->user_project_settings)): ?>
  <tbody>
    <? foreach ($this->user_project_settings as $user_project_setting): ?>
    <tr>
      <td><a class="btn btn-outline-primary" href="<?= url_for('edit_user_project_setting', $user_project_setting['id']) ?>"><?= LABEL_EDIT ?></a></td>
      <td><?= $user_project_setting['project_path'] ?></td>
      <td>
        <? if (file_exists($user_project_setting['project_path'])): ?>
        <? if (file_exists($user_project_setting['project_path']."app/")): ?><label class="badge badge-success">exists</label><? else: ?>
        <label class="badge badge-danger">not found php-work</label>
        <div><?= PHP_WORK_GIT_URL ?></div>
      <? endif ?>
    <? else: ?>
    <label class="badge badge-danger">not exists</label>
  <? endif ?>
</td>
</tr>
<? endforeach ?>
<? endif ?>
</tbody>
</table>
