
<div class="hero-unit">
  <table class="table">
    <tr>
      <th>command</th>
      <td><?= $this->results['cmd'] ?></td>
    </tr>
    <? foreach ($this->results['output'] as $key => $value): ?>
    <tr>
      <th><?= $key ?></th>
      <td><?= $value ?></td>
    </tr>
    <? endforeach ?>
    <tr>
      <th>return</th>
      <td><?= $this->results['return'] ?></td>
    </tr>
  </table>

  <a class="btn btn-secondary" href="<?= $this->linkTo('setting/') ?>"><?= LABEL_BACK ?></a>
</div>

