<div id="help-project" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Attributes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body alert alert-success">
        <dl>
          <dd>* If you export PHP files(Model, Controller, View etc...) by project-manager, please download PHP
            Framework '
            <a href="https://github.com/yoo16/phpwork" target="_blank">php-work</a>'.</dd>
        </dl>
      </div>
    </div>
  </div>
</div>