<? include('_header.phtml') ?>

<? include('help.phtml') ?>

<? include('add_window.phtml') ?>

<div>
  <?= PwForm::linkModal('#add-window', LABEL_ADD) ?>
  <? include('views/components/lib/sortable.phtml') ?>
  <?= PwForm::linkModal('#help-project', 'Help', ['class' => 'btn btn-outline-primary']) ?>
</div>

<div class="content">
  <table id="sortable-table" class="table">
    <thead class="thead-default">
      <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>DB</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <? if (is_array($this->project->values)): ?>
    <? foreach ($this->project->values as $values): ?>
    <tr row-id="<?= $values['id']?>">
      <td>
        <?= $this->project->linkEdit([], $values) ?>
      </td>
      <td>
        <?= $this->linkTo(['controller' => 'model'], 
            [
              'label' => $values['name'],
              'http_params' => ['project_id' => $values['id']]
            ]
          )
          ?>
      </td>
      <td>
        <?= $values['database']['name'] ?>
      </td>
      <td>
        <?= $this->linkTo(['action' => 'export_list'],
          [
          'label' => LABEL_SETTING,
          'http_params' => ['project_id' => $values['id']],
          ]
        ) ?>
      </td>
      <td>
        <?= $this->linkTo(['action' => 'analyze'],
        [
        'http_params' => ['project_id' => $values['id']],
        'label' => 'analyze'
        ]
        ) ?>
      </td>
    </tr>
    <? endforeach ?>
    <? endif ?>

  </table>
</div>