<? include('_header.phtml') ?>
<div id="project">
  <form id="input_form" action="<?= $this->urlFor(['action' => 'update_sort']) ?>" method="post"> 
    <? include('_sort_order.phtml') ?>
    <div class="btns">
      <a class="btn" href="javascript:submitForm('#input_form')"><?=LABEL_BUTTON_SAVE ?></a>
      <?= FormHelper::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
    </div>

  </form>
</div>

