
<div class="form-group row">
  <label class="form-control-label col-2" for="value"><?= LABEL_PAGE_FILTERS_VALUE ?></label>
    <?= $this->page_filter->formInput('value') ?>    
</div>






<div class="form-group row">
  <label class="form-control-label col-2" for="equal_sign"><?= LABEL_PAGE_FILTERS_EQUAL_SIGN ?></label>
    <?= $this->page_filter->formSelect('equal_sign', ['csv' => 'equal_sign', 'unselect' => true]) ?>    
</div>



<div class="form-group row">
  <label class="form-control-label col-2" for="attribute_id"><?= LABEL_ATTRIBUTES ?></label>
    <?= $this->page_filter->formSelect('attribute_id', [
                        'unselect' => true,
                        'label_separate' => ' - ',
                        'label' => ['name', 'label'],
                        'model' => 'Attribute',
                        'where' => "model_id = {$this->model->value['id']}",
                        'order' => "name",
                        
                        ]) ?>    
</div>



<?= FormHelper::submit(LABEL_SAVE) ?>
<?= FormHelper::linkButton("cancel", LABEL_BACK) ?>
<input type="hidden" name="page_filter[page_id]" value="<?= $this->page->value['id'] ?>">
