<? include('_header.phtml') ?>

<div class="pt-3">
  <?= PwForm::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <? include('views/components/lib/sortable.phtml') ?>
</div>

<table id="sortable-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>
        <?= LABEL_PAGE_FILTERS_VALUE ?>
      </th>
      <th>
        <?= LABEL_PAGE_FILTERS_EQUAL_SIGN ?>
      </th>
      <th>
        <?= LABEL_ATTRIBUTES ?>
      </th>
    </tr>
  </thead>

  <? if ($this->page_filter->values): ?>
  <? foreach ($this->page_filter->values as $values): ?>
  <tr row-id="<?= $values['id'] ?>">
    <td>
      <?= $this->page_filter->linkEdit([], $values) ?>
    </td>
    <td>
      <?= $values['value'] ?>
    </td>
    <td>
      <?= $values['equal_sign'] ?>
    </td>
    <td>
      <?= $this->attribute->values[$values['attribute_id']]['name'] ?>
    </td>
  </tr>
  <? endforeach ?>
  <? endif ?>
</table>