<?= '<?php' ?>

/**
 * <?= $values['model']['class_name'] ?>
 *
 * @create  <?= $values['model']['created_at'] ?>
 */

require_once 'PgsqlEntity.php';

class <?= $values['model']['class_name'] ?> extends PgsqlEntity {

<? if ($values['model']['is_none_id_column']): ?>
    var $is_none_id_column = true;
<? else: ?>
<? if ($values['model']['id_column_name']): ?>
    var $id_column = '<?=  $values['model']["id_column_name"] ?>';
<? else: ?>
    var $id_column = 'id';
<? endif ?>
<? endif ?>

    var $name = '<?= $values['model']['class_name'] ?>';
    var $entity_name = '<?=  $values['model']['entity_name']?>';

    static $columns = array(
    );

    static $column_labels = array (
    );

    function __construct($params=null) {
        parent::__construct();        
        if ($params['pg_info']) $pg_info = $params['pg_info'];
    }

   /**
    * validate
    *
    * @param
    * @return void
    */
    function validate() {
        parent::validate();
    }

}