<?= '<?php' ?>

/**
 * <?= $values['model']['class_name'] ?> 
 * 
 * @create  <?= $values['model']['created_at'] ?> 
 */

//namespace <?= $values['project']['name'] ?>;

require_once 'PwPgsql.php';

class _<?= $values['model']['class_name'] ?> extends PwPgsql {

<? if ($values['model']['is_none_id_column']): ?>
    public $is_none_id_column = true;
<? else: ?>
<? if ($values['model']['id_column_name']): ?>
    public $id_column = '<?=  $values['model']["id_column_name"] ?>';
<? else: ?>
    public $id_column = 'id';
<? endif ?>
<? endif ?>
    public $name = '<?= $values['model']['name'] ?>';
    public $entity_name = '<?= $values['model']['entity_name']?>';

<? if ($values['attribute']): ?>
    public $columns = array(
<? foreach ($values['attribute'] as $attribute): ?>
<? if ($attribute['name'] != 'id'): ?>
        <?= Model::columnPropertyForTemplate($attribute) ?>,
<? endif ?>
<? endforeach ?>
    );
<? endif ?>

<? if ($values['primary']): ?>
    public $primary_key = '<?= $values['primary'] ?>';
<? endif ?>
<? if ($values['foreign']): ?>
    public $foreign = array(
<? foreach ($values['foreign'] as $conname => $foreign): ?>
            '<?= $conname ?>' => [
                                  'column' => '<?= $foreign['attname'] ?>',
                                  'class_name' => '<?= PwFile::phpClassNameFromPwEntityName($foreign['foreign_relname']) ?>',
                                  'foreign_table' => '<?= $foreign['foreign_relname'] ?>',
                                  'foreign_column' => '<?= $foreign['foreign_attname'] ?>',
                                  'cascade_update_type' => '<?= $foreign['confupdtype'] ?>',
                                  'cascade_delete_type' => '<?= $foreign['confdeltype'] ?>',
                                  ],
<? endforeach ?>
    );
<? endif ?>

<? if ($values['unique']): ?>
    public $unique = array(
<? foreach ($values['unique'] as $conname => $uniques): ?>
            '<?= $conname ?>' => [
<? foreach ($uniques as $unique): ?>
                        '<?= $unique['attname'] ?>',
<? endforeach ?>
                        ],
<? endforeach ?>
    );
<? endif ?>

<? if ($values['model']['old_name']): ?>
    public $old_name = '<?= $values['model']['old_name'] ?>';
<? endif ?>

<? if ($values['old_id_column']): ?>
    public $old_id_column = '<?= $values['old_id_column'] ?>';
<? endif ?>

    function __construct($params = null) {
        parent::__construct($params);
    }

   /**
    * validate
    *
    * @param
    * @return void
    */
    function validate() {
        parent::validate();
    }

}