from lib.pgsql import Pgsql

class _<?= $values['model']['class_name'] ?>(Pgsql):

<?php if ($values['model']['id_column_name']): ?>
    id_column = '<?=  $values['model']["id_column_name"] ?>'
<? else: ?>
    id_column = 'id'
<?php endif ?>
    name = '<?= $values['model']['name'] ?>'
    table_name = '<?= $values['model']['name'] ?>'
    entity_name = '<?= $values['model']['entity_name']?>'

<?php if ($values['attribute']): ?>
    columns = {
<?php foreach ($values['attribute'] as $attribute): ?>
<?php if ($attribute['name'] != 'id'): ?>
        <?= Model::pythonPropertyForTemplate($attribute) ?>,
<?php endif ?>
<?php endforeach ?>
    }
<?php endif ?>

<?php if ($values['primary']): ?>
    primary_key = '<?= $values['primary'] ?>'
<?php endif ?>
<?php if ($values['foreign']): ?>
    foreigns = {
<?php foreach ($values['foreign'] as $conname => $foreign): ?>
        '<?= $conname ?>': {
            'column': '<?= $foreign['attname'] ?>',
            'class_name': '<?= PwFile::phpClassNameFromPwEntityName($foreign['foreign_relname']) ?>',
            'foreign_table': '<?= $foreign['foreign_relname'] ?>',
            'foreign_column': '<?= $foreign['foreign_attname'] ?>',
            'cascade_update_type': '<?= $foreign['confupdtype'] ?>',
            'cascade_delete_type': '<?= $foreign['confdeltype'] ?>',
        },
<?php endforeach ?>
    }
<?php endif ?>

<?php if ($values['unique']): ?>
    unique: {
<?php foreach ($values['unique'] as $conname => $uniques): ?>
            '<?= $conname ?>': {<?php foreach ($uniques as $unique): ?>'<?= $unique['attname'] ?>',<?php endforeach ?>},
<?php endforeach ?>
    }
<?php endif ?>
    def __init__(self):
        super().__init__()
        return