#!/usr/bin/env php
<?php
require_once dirname(__FILE__).'/../lib/setting.php';

require_once 'PHPUnit/Framework.php';
require_once 'PHPUnit/TextUI/TestRunner.php';

$suite = new PHPUnit_Framework_TestSuite();
if ($dp = opendir(BASE_DIR . 'test')) {
    while ($file = readdir($dp)) {
        if (preg_match("/^(\w+Test)\.php$/", $file, $matches)) {
            $test_case = $matches[1];
            $suite->addTestFile(BASE_DIR . "test/{$test_case}.php");
        }
    }
}
PHPUnit_TextUI_TestRunner::run($suite);
?>
