
<div>
  <a class="btn btn-outline-primary" href="<?= url_for('new') ?>"><?= LABEL_ADD ?></a>
  <a class="btn btn-outline-primary" href="<?= url_for('sort_order') ?>"><?= LABEL_SORT_ORDER ?></a>
</div>


  <table class="table">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>名称</th>
      </tr>
    </thead>

<? if (is_array($this->users)): ?>

<? foreach ($this->users as $key => $user): ?>
    <tr>
      <td>
        <a class="btn btn-outline-primary" href="<?= url_for('edit', $user['id']) ?>"><?= LABEL_EDIT ?></a>
      </td>
      <td><?= $user['login_name'] ?></td>
    </tr>
<? endforeach ?>

<? endif ?>

  </table>
