<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', null, ['label' => LABEL_ADD, 'class' => 'btn btn-primary'] ) ?>
  <? include('views/components/sortable.phtml') ?>

</div>

<table id="sortable-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_USERS_LOGIN_NAME ?></th>
          </tr>
  </thead>

  <? if ($this->user->values): ?>
  <? foreach ($this->user->values as $values): ?>
  <tr row-id="<?= $values['id'] ?>">
    <td><?= FormHelper::linkButton('edit', $values['id'], ['label' => LABEL_EDIT]) ?></td>
    <td><?= $values['login_name'] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>