

ALTER TABLE models
 ADD CONSTRAINT models_database_id_fk FOREIGN KEY (database_id)
 REFERENCES databases(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE attributes
 ADD CONSTRAINT attributes_model_id_fk FOREIGN KEY (model_id)
 REFERENCES models(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE input_type_values
 ADD CONSTRAINT input_type_values_input_type_id_fk FOREIGN KEY (input_type_id)
 REFERENCES input_types(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE menus
 ADD CONSTRAINT menus_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE menu_items
 ADD CONSTRAINT menu_items_menu_id_fk FOREIGN KEY (menu_id)
 REFERENCES menus(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE menu_items
 ADD CONSTRAINT menu_items_model_id_fk FOREIGN KEY (model_id)
 REFERENCES models(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE menu_items
 ADD CONSTRAINT menu_items_page_id_fk FOREIGN KEY (page_id)
 REFERENCES pages(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE monitors
 ADD CONSTRAINT monitors_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE pages
 ADD CONSTRAINT pages_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE pages
 ADD CONSTRAINT pages_model_id_fk FOREIGN KEY (model_id)
 REFERENCES models(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE page_actions
 ADD CONSTRAINT page_actions_page_id_fk FOREIGN KEY (page_id)
 REFERENCES pages(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE page_items
 ADD CONSTRAINT page_items_model_id_fk FOREIGN KEY (model_id)
 REFERENCES models(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE page_items
 ADD CONSTRAINT page_items_attribute_id_fk FOREIGN KEY (attribute_id)
 REFERENCES attributes(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE page_items
 ADD CONSTRAINT page_items_page_action_id_fk FOREIGN KEY (page_action_id)
 REFERENCES page_actions(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE page_layouts
 ADD CONSTRAINT page_layouts_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE test_actions
 ADD CONSTRAINT test_actions_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE test_actions
 ADD CONSTRAINT test_actions_page_action_id_fk FOREIGN KEY (page_action_id)
 REFERENCES pages(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE test_actions
 ADD CONSTRAINT test_actions_action_id_fk FOREIGN KEY (action_id)
 REFERENCES page_actions(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE localize_labels
 ADD CONSTRAINT localize_labels_attribute_id_fk FOREIGN KEY (attribute_id)
 REFERENCES attributes(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE localize_labels
 ADD CONSTRAINT localize_labels_model_id_fk FOREIGN KEY (model_id)
 REFERENCES models(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE apis
 ADD CONSTRAINT apis_project_id_fk FOREIGN KEY (project_id)
 REFERENCES projects(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;

ALTER TABLE api_params
 ADD CONSTRAINT api_params_api_id_fk FOREIGN KEY (api_id)
 REFERENCES apis(id)
 ON DELETE CASCADE
 ON UPDATE NO ACTION
 NOT DEFERRABLE;



