
<div class="hero-unit">

  <h1>Hello, ProjectManager! (Made in <a href="https://github.com/yoo16/phpwork" target="_blank">PHPWork</a>)</h1>

  build with 
  <ul>
    <li><a href="https://jquery.com/" target="_blank">jQuery</a></li>
    <li><a href="https://v4-alpha.getbootstrap.com/" target="_blank">Bootstrap4</a></li>
  </ul>

  <h2>Application Information</h2>
  <table class="table">
    <tr>
      <th>setting file path</th>
      <td><?= undefineLabel('APP_SETTING_FILE_PATH', APP_SETTING_FILE_PATH) ?></td>
    </tr>
    <tr>
      <th>BASE_DIR</th>
      <td><?= undefineLabel('BASE_DIR', BASE_DIR) ?></td>
    </tr>
    <tr>
      <th>PROJECT_NAME</th>
      <td><?= undefineLabel('PROJECT_NAME', PROJECT_NAME) ?></td>
    </tr>
    <tr>
      <th>PROJECT_DIR</th>
      <td><?= undefineLabel('PROJECT_DIR', PROJECT_DIR) ?></td>
    </tr>
    <tr>
      <th>TMP_DIR</th>
      <td><?= undefineLabel('TMP_DIR', TMP_DIR) ?></td>
    </tr>
    <tr>
      <th>DB_DIR</th>
      <td><?= undefineLabel('DB_DIR', DB_DIR) ?></td>
    </tr>
    <tr>
      <th>DEBUG</th>
      <td><?= undefineLabel('DEBUG', DEBUG) ?></td>
    </tr>
    <tr>
      <th>PG_INFO</th>
      <td><?= undefineLabel('PG_INFO', PG_INFO) ?></td>
    </tr>
    <tr>
      <th>MAIL_SETTING_FILE</th>
      <td><?= undefineLabel('MAIL_SETTING_FILE', MAIL_SETTING_FILE) ?></td>
    </tr>
    <tr>
      <th>DEFAULT_LOCALE</th>
      <td><?= undefineLabel('DEFAULT_LOCALE', DEFAULT_LOCALE) ?></td>
    </tr>
  </table>

  <h2>Application Setting</h2>
  <table class="table">
    <tr>
      <th>file path</th>
      <td><?= BASE_DIR."app/application_setting.php" ?></td>
    </tr>
    <tr>
      <th>APP_NAME</th>
      <td><?= undefineLabel('APP_NAME', APP_NAME) ?></td>
    </tr>
    <tr>
      <th>HTML_TITLE</th>
      <td><?= undefineLabel('HTML_TITLE', HTML_TITLE) ?></td>
    </tr>
    <tr>
      <th>VERSION</th>
      <td><?= undefineLabel('VERSION', VERSION) ?></td>
    </tr>
  </table>

  <h2>PostgreSQL</h2>
  <table class="table">
    <tr>
      <th>PG_INFO</th>
      <td><?= undefineLabel('PG_INFO', PG_INFO) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
      <? if ($this->pg_connection): ?>
      <?= $this->pg_connection ?>
      <? else: ?>
      <?= undefineLabelTag() ?>
      <? endif ?>
      </td>
    </tr>
    <tr>
      <th>PG_INFO</th>
      <td>
      <? if (!file_exists($this->create_sql_path)): ?>
      <?= undefineLabelTag() ?>
      <? endif ?>
      <?= $this->create_sql_path ?>
      </td>
    </tr>
  </table>
  <? if (!$this->pg_connection): ?>
  <a class="btn btn-primary" href="<?= url_for('create_database') ?>" onClick="return confirm('createdb for PostgreSQL?')"><?= LABEL_CREATE ?></a>
  <? endif ?>
  <a class="btn btn-primary" href="<?= url_for('pgsql') ?>"><?= LABEL_SETTING ?></a>

</div>

