
<div class="hero-unit">

  <table class="table">
    <tr>
      <th>command</th>
      <td><?= $this->results['cmd'] ?></td>
    </tr>
    <tr>
      <th></th>
      <td>
    <? foreach ($this->results['output'] as $value): ?>
      <?= $value ?><br>
    <? endforeach ?>
      </td>
    </tr>
    <tr>
      <th>return</th>
      <td><?= $this->results['return'] ?></td>
    </tr>
  </table>

  <a class="btn btn-outline-primary" href="<?= url_for('init_database') ?>" onClick="return confirm('init database?')"><?= LABEL_INIT ?></a>
  <a class="btn btn-outline-primary" href="<?= url_for('/index') ?>"><?= LABEL_BACK ?></a>
</div>

