
<div class="hero-unit">

  <h2>PostgreSQL</h2>
  <table class="table">
    <tr>
      <th>PG_INFO</th>
      <td><?= undefineLabel('PG_INFO', PG_INFO) ?></td>
    </tr>
    <tr>
      <th>pg_connection()</th>
      <td>
      <? if ($this->pg_connection): ?>
      <label class="badge badge-success">connected</label>
      <? else: ?>
      <?= undefineLabelTag() ?>
      <? endif ?>
      </td>
    </tr>
    <tr>
      <th>PG_INFO</th>
      <td>
      <? if (!file_exists($this->create_sql_path)): ?>
      <?= undefineLabelTag() ?>
      <? endif ?>
      <?= $this->create_sql_path ?>
      </td>
    </tr>
  </table>
  <? if (!$this->pg_connection): ?>
  <a class="btn btn-outline-primary" href="<?= url_for('create_database') ?>" onClick="return confirm('createdb for PostgreSQL?')"><?= LABEL_CREATE ?></a>
  <? endif ?>
  <a class="btn btn-outline-primary" href="<?= url_for('init_database') ?>" onClick="return confirm('init database? *Data will be deleted on database.')"><?= LABEL_INIT ?></a>


</div>

