<?= PwTag::pwProjectName($this->pw_project_name) ?>

<?= PwTag::javascript('jquery/jquery-3.3.1.min') ?>
<?= PwTag::javascript('jquery/jquery-ui-1.12.1.min') ?>
<?= PwTag::javascript('jquery/jpicker-1.1.6.min') ?>

<?= PwTag::javascript('bootstrap/tether.min') ?>
<?= PwTag::javascript('bootstrap/bootstrap.min') ?>

<?= PwTag::javascript('functions') ?>

<!-- pw lib -->
<?= PwTag::javascript('lib/PwController') ?>
<?= PwTag::javascript('lib/PwNode') ?>
<?= PwTag::javascript('lib/PwUI') ?>
<?= PwTag::javascript('lib/PwLoadingOverlay') ?>
<?= PwTag::javascript('lib/PwForm') ?>
<?= PwTag::javascript('lib/PwTableDND') ?>
<?= PwTag::javascript('lib/PwDate') ?>
<?= PwTag::javascript('lib/PwModal') ?>
<?= PwTag::javascript('lib/PwScroller') ?>
<?= PwTag::javascript('lib/PwAnimation') ?>
<?= PwTag::javascript('lib/PwLog') ?>

<?= PwTag::javascript('pw_functions') ?>