<!-- TODO setting -->
<?= TagHelper::javascript('jquery/jquery-1.11.1.min') ?>
<?= TagHelper::javascript('jquery/jquery-ui.min') ?>
<?= TagHelper::javascript('jquery/jquery.tablednd') ?>
<?= TagHelper::javascript('jquery/jquery.validate') ?>
<?= TagHelper::javascript('jquery/jquery.datetimepicker') ?>

<?= TagHelper::javascript('bootstrap/tether.min') ?>
<?= TagHelper::javascript('bootstrap/bootstrap.min') ?>

<?= TagHelper::javascript('default') ?>
<?= TagHelper::javascript('functions') ?>
<?= TagHelper::javascript('api') ?>

