<? include('views/components/login_user.phtml') ?>

<nav id="header" class="navbar navbar-toggleable fixed-top">

  <div>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapsea" data-target="#nav-header"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
        <i class="fa fa-bars"></i>
      </span>
    </button>
  </div>

  <div class="collapse navbar-collapse text-nowrap" id="nav-header">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'simulate_spot',
          'action' => 'list',
          ],
          [
            'label' => LABEL_SPOTS,
            'class' => 'nav-link action-loading',
            'icon_name' => 'home',
            'is_use_selected' => true,
            'is_not_pw_multi_sid' => true,
          ]
        )
        ?>
      </li>

    </div>

  </div>
</nav>