<? include('_header.phtml') ?>

<div class="card">
  <h4 class="card-header">
  <?= $this->model->value['name'] ?> <label class="badge badge-pill badge-info"><?= $this->pg_class['pg_class_id'] ?></label>
  <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
  </h4>

  <div class="card-body">
    <table class="table">
      <thead class="thead-default">
        <tr>
          <th></th>
          <th>Name</th>
          <th>Comment/Note</th>
        </tr>
      </thead>

      <tbody>
        <? if ($this->attribute->values): ?>
        <? foreach ($this->attribute->values as $attribute): ?>
        <tr>
          <td>
            <? if (!Model::$required_columns[$attribute['name']]): ?><?= PwForm::linkButton('edit', LABEL_EDIT, $attribute['id']) ?><? endif ?>
          </td>

          <td>
            <?= $attribute['name'] ?>
            <? if ($attribute['old_name']): ?>
            <div>
              (<?= $attribute['old_name'] ?>)
            </div>
          <? endif ?>
        </td>

        <td>
          <form method="post" action="<?= $this->urlFor('update_attribute', $attribute['id']) ?>">
            <div class="row">
             <div class="input-group">
               <?= PwForm::text('attribute[label]', $attribute['label'], ['class' => 'form-control form-control-sm']) ?>
               <span class="input-group-btn"><?= PwForm::button(LABEL_UPDATE, ['class' => 'btn btn-primary btn-sm']) ?></span>
             </div>
           </div>
            <div class="row">
             <div class="input-group">
               <?= PwForm::textarea('attribute[note]', $attribute['note'], ['class' => 'form-control', 'rows' => 3]) ?>
             </div>
           </div>
           <?= PwForm::hidden('pg_class_id', $attribute['pg_attribute']['pg_class_id']) ?>
           <?= PwForm::hidden('database_id', $this->database->value['id']) ?>
         </form>
       </td>

     </tr>
   <? endforeach ?>
 <? endif ?>
</tbody>
</table>
</div>
</div>
