<a name="php">&nbsp;</a>
<h1>PHP</h1>

<? include('_header.phtml') ?>

<?= $this->total_row_count ?>
-
<?= $this->total_file_count ?>

<a class="btn" href="#" onClick="$('#error_documents').show()">Error Documents</a>
<a class="btn" href="<?= url_for('test_php', array('project_id' => $this->project->value['id'])) ?>">Test PHP</a>
<div id="error_documents">
  <ul>
    <? foreach ($this->missmatch_function_params as $file_name => $missmatch_function_params): ?>
    <li>
      <h3><?= $file_name ?></h3>
      <? foreach ($missmatch_function_params as $function_name => $missmatch_function_param): ?>
      <h4><?= $function_name ?></h4>
      <ul>
        <? foreach ($missmatch_function_param as $param): ?>
        <li>
          <?= $param ?>
          <? endforeach ?>
        </li>
      </ul>
      <? endforeach ?>
    </li>
    <? endforeach ?>
  </ul>
</div>

<h2>Document</h2>
<div>
  <? foreach ($this->controller_files as $path => $controller_file): ?>
  <? $dir_index++ ?>
  <div><a href="#<?=$path ?>"><?= $path ?></a></div>
  <? endforeach ?>
</div>

<div>

  <dl>
    <? foreach ($this->controller_files as $path => $controller_file): ?>
    <? $dir_index++ ?>
    <dt><a name="<?= $path ?>">&nbsp;</a><?= $path ?></dt>
    <? foreach ($controller_file as $key => $_controller): ?>
    <? $function_key = "document_{$dir_index}_{$key}" ?>
    <dd>
      <h2><a href="javascript:showHideDocument('#<?= $function_key ?>');"><?= $_controller['file_name'] ?></a></h2>
      <div id="<?= $function_key ?>" class="document_element">

        <? if($_controller['documents']['class_documents']): ?>
        <div class="row">
          <div class="">
            <table class="table table-bordered table-condensed">
              <tr>
                <th class="col-xs-2 col-lg-2">Class</th>
                <td><?= $_controller['documents']['class_documents']['class_name'] ?></td>
              </tr>
              <tr>
                <th>Extends Class</th>
                <td><?= $_controller['documents']['class_documents']['extends_class_name'] ?></td>
              </tr>
              <tr>
                <th>package</th>
                <td><?= $_controller['documents']['class_documents']['package'] ?></td>
              </tr>
              <tr>
                <th>Comment</th>
                <td><?= nl2br($_controller['documents']['class_documents']['comment']) ?></td>
              </tr>
              <tr>
                <th>require_once</th>
                <td>
                  <? if($_controller['documents']['require_once']): ?>
                  <ul class="nav">
                    <? foreach ($_controller['documents']['require_once'] as $key => $require_once): ?>
                    <li><?= $require_once ?></li>
                    <? endforeach ?>
                  </ul>
                  <? endif ?>
                </td>
              </tr>
            </table>
          </div>
        </div>
        <? endif ?>

        <p><?= $_controller['documents']['row_count'] ?>行</p>

        <? foreach ($_controller['documents']['function_documents'] as $key2 =>  $values): ?>
        <h3>
          <? $controller_name =  php_controller_uri_name($_controller['file_name']) ?>
          <? $url = "http://{$_SERVER['SERVER_NAME']}/{$this->project->value['name']}/{$controller_name}/{$values['action_name']}/" ?>
          <a href="<?= $url ?>" target="_blank"><?= $values['function_name'] ?></a>
        </h3>
        <table class="table table-bordered table-condensed">
          <tr>
            <th class="col-xs-2 col-lg-2">タイトル</th>
            <td class=""><?= $values['first_explains'] ?></td>
          </tr>
          <tr>
            <th class="">説明</th>
            <td><?= nl2br($values['explains']) ?></td>
          </tr>
          <tr>
            <th>パラメータ</th>
            <td><? foreach ($values['params'] as $key3 => $param): ?><?=$param ?><br /><? endforeach ?></td>
          </tr>
          <tr>
            <th>戻り値</th>
            <td><?= $values['return'] ?></td>
          </tr>
        </table>
        <? endforeach ?>
      </div>
    </dd>
    <? endforeach ?>
    <? endforeach ?>

  </dl>
</div>
