<div class="row car">
  <div class="card col-xs-6 col-sm-6 col-md-6">
    <div class="card-block">
      <form id="form-edit" action="<?= $this->urlFor('add') ?>" method="post" autocomplete="off">
        <div class="form-group">
          <label for="recipient-name" class="form-control-label"><?= LABEL_PAGE_NAME ?></label>
          <?= $this->model->formInput('name') ?>
        </div>

        <div class="form-group">
          <label for="recipient-name" class="form-control-label"><?= LABEL_LABEL ?></label>
          <?= $this->model->formInput('label') ?>
        </div>
      <button class="btn btn-outline-primary" type="submit"><?= LABEL_ADD ?></button>
    </form>
  </div>
</div>
</div>
