<? include('_header.phtml') ?>
<div class="card">

  <form action="<?= url_for('update', $this->params['id']) ?>" method="post">

    <div class="card-header">
      <h4></h4>
      <div class="text-left">
        <?= FormHelper::submit(LABEL_SAVE) ?>        <?= FormHelper::linkButton("cancel", LABEL_BACK) ?>      </div>
    </div>

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>

  </form>

  <div class="card-footer">
    <div class="text-left">
      <?= $this->view_item_group_member->formDelete() ?>    </div>
  </div>

</div>
