



<div class="form-group row">
  <label class="form-control-label col-2" for="view_item_id"><?= LABEL_VIEW_ITEMS ?></label>
    <?= $this->view_item_group_member->formSelect('view_item_id', [
                        'unselect' => true,
                        'label_separate' => '-',
                        'label' => ['label'],
                        'model' => 'ViewItem',
                        'where' => "view_id = {$this->view->value['id']}",
                        
                        
                        ]) ?>    
</div>



<?= FormHelper::submit(LABEL_SAVE) ?>
<?= FormHelper::linkButton("cancel", LABEL_BACK) ?>
<input type="hidden" name="view_item_group_member[view_item_group_id]" value="<?= $this->view_item_group->value['id'] ?>">
