<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton('new', LABEL_ADD, null, ['class' => 'btn btn-primary']) ?>
  <a href="#" class="btn btn-outline-primary change-sortable" rel="list-table"><?= LABEL_SORT_ORDER ?></a>

  <a href="#" class="btn btn-primary update-sortable" controller="view_item_group_member"><?= LABEL_UPDATE ?></a>
</div>

<table id="list-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= LABEL_VIEW_ITEM_GROUPS ?></th>
            <th><?= LABEL_VIEW_ITEMS ?></th>
          </tr>
  </thead>

  <? if ($this->view_item_group_member->values): ?>
  <? foreach ($this->view_item_group_member->values as $values): ?>
  <tr id="<?= $values['id'] ?>">
    <td><?= FormHelper::linkButton('edit', LABEL_EDIT, $values['id']) ?></td>
    <td><?= $this->view_item_group->values[$values['view_item_group_id']][''] ?></td>
    <td><?= $this->view_item->values[$values['view_item_id']][''] ?></td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>