
<form id="form-edit">
  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_MAIL ?></label>
    <input class="form-control" type="text" name="email" value="<?= $this->user['email'] ?>">
  </div>
  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_LAST_NAME ?></label>
    <input class="form-control" type="text" name="last_name" value="<?= $this->user['last_name'] ?>">
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_FIRST_NAME ?></label>
    <input class="form-control" type="text" name="first_name" value="<?= $this->user['first_name'] ?>">
  </div>

<? if (!$this->user['id']): ?>
  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_PASSWORD ?></label>
    <input class="form-control" type="password" name="password" value="">
  </div>
<? endif ?>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_GENDER ?></label>
    <?= FormHelper::genderRadio($this->forms['gender'], $this->user['gender']); ?>
  </div>

  <div class="form-group">
    <label for="recipient-name" class="form-control-label"><?= LABEL_BIRTHDAY ?></label>
    <?= FormHelper::selectBirthday($this->forms['birthday_at'], $this->user['birthday_at']); ?>
  </div>

</div>

</table>
<input type="hidden" name="id" value="<?= $this->user['id'] ?>">
</form>
