
<div>
  <a action="new" class="action btn btn-outline-primary" href="#" data-toggle="modal" data-target="#edit_modal"><?= LABEL_ADD ?></a>
  <a action="list" class="action btn btn-outline-primary" href="#"><?= LABEL_RELOAD ?></a>
</div>

<div id="user_list"></div>

<div class="modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div id="user_edit" class="modal-body"></div>

      <div class="modal-footer">
        <a action="update" class="action btn btn-outline-primary" href="#"><?= LABEL_UPDATE ?></a>
        <? if (!$this->user['id']): ?>
        <a action="delete" class="action btn btn-outline-danger" href="#"><?= LABEL_DELETE ?></a>
        <? endif ?>
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
      </div>

    </div>
  </div>
</div>

<?= TagHelper::javascript('controllers/AdminUserController') ?>
