<div class="col-12">
  <div class="row">
    <div class="btn-group btn-group-toggle">
    <? if ($this->spot_display_day->values): ?>
      <? foreach ($this->spot_display_day->values as $this->spot_display_day->value): ?>
        <?= $this->linkJs( 
        [
          'class' => 'pw-click btn btn-outline-primary display-day-group',
          'label' => SpotDisplayDay::displayDay($this->spot_display_day->value['day']),
          'pw-controller' => $this->jsControllerName(),
          'pw-action' => 'latest_days_diagram',
          'latest-days' => $this->spot_display_day->value['day'],
        ]
        )
        ?>
      <? endforeach ?>
    <? endif ?>
    </div>
    
    <input id="from-at" class="form-control datetimepicker ml-1" type="text" value="<?= $this->app_date->from_at ?>">
    <input id="to-at" class="form-control datetimepicker ml-1" type="text" value="<?= $this->app_date->to_at ?>">
    <input type="submit" class="pw-click btn btn-outline-primary ml-1" pw-controller="<?= $this->jsControllerName() ?>" pw-action="reload" value="<?= LABEL_RELOAD ?>">
  </div>
</div>
