<? include('views/components/menu/admin/instrument.phtml') ?>

<? if ($this->instrument_displace_type->value['id']): ?>
<div class="d-flex p-2">
  <h2>
    <?= $this->instrument_displace_type->value['name'] ?>
  </h2>
</div>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <?= $this->linkTo(
          [
          'controller' => 'instrument_displace_type',
          'action' => 'edit',
          'id' => $this->instrument_displace_type->value['id'],
          ],
          [
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'class' => 'nav-link',
            'is_use_selected' => true
          ]
        )
        ?>
    </li>
    <li class="nav-item">
        <? if ($this->instrument_displace_type->value['collapse_graph_id']): ?>
        <?= $this->linkTo(
          [
          'controller' => 'instrument_collapse_graph',
          'action' => 'edit',
          'id' => $this->instrument_displace_type->value['collapse_graph_id']
          ],
          [
          'label' => LABEL_COLLAPSE_GRAPHS,
          'icon_name' => 'chart-bar',
          'class' => 'nav-link',
          'is_use_selected' => true,
          'http_params' => ['instrument_displace_type_id' => $this->instrument_displace_type->value['id']]
          ]
          )
        ?>
        <? else: ?>
        <?= $this->linkTo(
          [
          'controller' => 'instrument_collapse_graph',
          'action' => 'new',
          ],
          [
          'label' => LABEL_COLLAPSE_GRAPHS,
          'icon_name' => 'chart-bar',
          'class' => 'nav-link',
          'is_use_selected' => true,
          'http_params' => ['instrument_displace_type_id' => $this->instrument_displace_type->value['id']]
          ]
          )
        ?>
        <? endif ?>
      </li>
  </ul>
</nav>
<? endif ?>