<div class="modal fade" id="login_user" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
  
        <div class="modal-header">
          <h2 class="modal-title"><?= LABEL_LOGIN ?></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
  
        <div id="user_edit" class="modal-body">
            <?= $this->pw_auth->value['name'] ?>
            <br>
            <?= $this->pw_auth->value['login_at'] ?>
        </div>
  
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
        </div>
  
      </div>
    </div>
  </div>
