<div class="btn-group btn-group-toggle">
<?= $this->linkJs(
  [
    'label' => LABEL_START_DATE,
    'icon_name' => 'angle-double-left',
    'class' => 'pw-click btn btn-outline-primary',
    'pw-controller' => $this->jsControllerName(),
    'pw-action' => 'start_list',
  ]
)
?>
<?= $this->linkJs(
  [
    'label' => LABEL_PREV_DATE,
    'icon_name' => 'angle-left',
    'class' => 'pw-click btn btn-outline-primary',
    'pw-controller' => $this->jsControllerName(),
    'pw-action' => 'prev_list',
  ]
)
?>
<?= $this->linkJs(
  [
    'label' => LABEL_NEXT_DATE,
    'icon_name' => 'angle-right',
    'class' => 'pw-click btn btn-outline-primary',
    'pw-controller' => $this->jsControllerName(),
    'pw-action' => 'next_list',
  ]
)
?>
<?= $this->linkJs(
  [
    'label' => LABEL_LATEST_DATE,
    'icon_name' => 'angle-double-right',
    'class' => 'pw-click btn btn-outline-primary',
    'pw-controller' => $this->jsControllerName(),
    'pw-action' => 'latest_list',
  ]
)
?>
</div>
<?= PwForm::input(
  [
    'id' => 'from-at',
    'name' => 'from_at',
    'class' => 'datetimepicker form-control',
    'value' => $this->app_date->from_at,
    'change_selector' => '#date_number',
  ]
)
?>

<?= $this->linkJs(
  [
    'label' => LABEL_RELOAD,
    'class' => 'pw-click btn btn-outline-primary',
    'icon_name' => 'redo-alt',
    'pw-controller' => $this->jsControllerName(),
    'pw-action' => 'list',
  ]
)
?>