<? include('views/components/menu/admin/spot.phtml') ?>

<? if ($this->soil_moisture_instrument->value['id']): ?>
  <div class="d-flex p-2">
    <h2><?= $this->soil_moisture_instrument->value['name'] ?></h2>
    <input type="hidden" id="soil_moisture_instrument" value="<?= $this->soil_moisture_instrument->value['id'] ?>">
  </div>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'soil_moisture_instrument',
          'action' => 'edit',
          'id' => $this->soil_moisture_instrument->value['id']
          ],
          [
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'class' => 'nav-link',
            'is_use_selected' => true,
          ]
        )
        ?>
      </li>
    </ul>
  </nav>

<? endif ?>