<? include('views/components/menu/admin/spot.phtml') ?>

<? if ($this->temperature_instrument->value['id']): ?>
  <div class="d-flex p-2">
    <h2><?= $this->temperature_instrument->value['name'] ?></h2>
    <input type="hidden" id="temperature_instrument_id" value="<?= $this->temperature_instrument->value['id'] ?>">
  </div>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'temperature_instrument',
          'action' => 'edit',
          'id' => $this->temperature_instrument->value['id']
          ],
          [
            'label' => LABEL_SETTING,
            'icon_name' => 'edit',
            'class' => 'nav-link',
            'is_use_selected' => true,
          ]
        )
        ?>
      </li>

      <? if ($this->pw_auth->value['is_super']): ?>
      <li class="nav-item">
        <?= $this->linkTo(
          [
          'controller' => 'temperature',
          'action' => 'list',
          ],
          [
            'label' => LABEL_MEASUREMENT,
            'icon_name' => 'database',
            'class' => 'nav-link',
            'is_use_selected' => true,
            'http_params' => ['temperature_instrument_id' => $this->temperature_instrument->value['id']]
          ]
        )
        ?>
      <? endif ?>
      </li>
    </ul>
  </nav>

<? endif ?>