
<table class="table">

    <tr>
      <th><?= LABEL_PUBLIC_LOCALIZE_STRINGS_LABEL ?></th>
      <td>
          <?= $this->public_localize_string->formInput('label', ['class' => 'form-control']) ?>
      </td>
    </tr>


    <tr>
      <th><?= LABEL_PUBLIC_LOCALIZE_STRINGS_NAME ?></th>
      <td>
          <?= $this->public_localize_string->formInput('name', ['class' => 'form-control']) ?>
      </td>
    </tr>

</table>

    