<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'add']) ?>" method="post">
  <div class="card">

    <div class="card-block">

      <? include('form.phtml') ?>      
    </div>

    <div class="card-footer">
      <h4></h4>
      <div class="text-left">
        
        <?= PwForm::submit(LABEL_SAVE) ?>
        <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
      </div>
    </div>
  </div>
</form>
