<? if ($this->spot->value['id']): ?>
<nav class="navbar navbar-light bg-faded">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'observe_sensor'],
        [
          'label' => LABEL_SENSORS,
          'class' => 'nav-link action-loading action-loading',
          'is_use_selected' => true,
          'icon_name' => 'compass'
        ]
      )
      ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'observe_instrument'],
        [
          'label' => LABEL_INSTRUMENTS,
          'class' => 'nav-link action-loading action-loading',
          'is_use_selected' => true,
          'icon_name' => 'tachometer-alt'
        ]
      )
      ?>
    </li>
    <li class="nav-item dropdown">
      <? foreach ($this->csv_options['instrument_type'] as $instrument_type => $label): ?>
        <?= $this->linkTo(['controller' => "observe_{$instrument_type}"],
          [
            'label' => $label,
            'class' => 'dropdown-item action-loading',
            'is_use_selected' => true,
            'selected_key' => $instrument_type,
            'selected_value' => $this->instrument_type,
          ]
        )
        ?>
      <? endforeach ?>
    </li>

    <? if ($this->isDeveloper()): ?>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'observe_temperature_instrument'],
        [
          'label' => LABEL_TEMPERATURE,
          'class' => 'nav-link action-loading action-loading',
          'is_use_selected' => true,
          'icon_name' => 'thermometer-three-quarters'
        ]
      )
      ?>
    </li>
    <li class="nav-item">
      <?= $this->linkTo(['controller' => 'observe_soil_moisture_instrument'],
        [
          'label' => LABEL_SOIL_MOISTURE_MEASURES,
          'class' => 'nav-link action-loading action-loading',
          'is_use_selected' => true,
          'icon_name' => 'tint'
        ]
      )
      ?>
    </li>
    <? endif ?>
  </ul>
</nav>
<? endif ?>
