  <table class="table">

    <tr>
      <th><?= DATABASE_NAME ?></th>
      <td><input class="form-control" name="database[name]" type="text" value="<?= $this->database['name'] ?>" required="required"></td>
    </tr>

    <tr>
      <th><?= DATABASE_HOST ?></th>
      <td>
        <?= FormHelper::select($this->forms['hostname']) ?>
      </td>
    </tr>
                 
    <tr>
      <th><?= DATABASE_USER ?></th>
      <td>
        <?= FormHelper::select($this->forms['user_name']) ?>
      </td>
    </tr>
                 
    <tr>
      <th><?= DATABASE_PORT ?></th>
      <td>
        <?= FormHelper::select($this->forms['port']) ?>
      </td>
    </tr>

  </table>

