  <table class="table">

    <tr>
      <th><?= DATABASE_NAME ?></th>
      <td><?= $this->database->formInput('name', ['class' => 'form-control']) ?></td>
    </tr>

    <tr>
      <th><?= DATABASE_HOST ?></th>
      <td>
        <?= $this->database->formSelect('hostname', ['csv' => DB_HOSTS_CSV]) ?>
      </td>
    </tr>

    <tr>
      <th><?= DATABASE_USER ?></th>
      <td>
        <?= $this->database->formSelect('user_name', ['csv' => DB_USERS_CSV]) ?>
      </td>
    </tr>

    <tr>
      <th><?= DATABASE_PORT ?></th>
      <td>
        <?= $this->database->formSelect('port', ['csv' => DB_PORTS_CSV]) ?>
      </td>
    </tr>

    <tr>
      <th>Delete Lock</th>
      <td>
        <?= $this->database->formCheckbox('is_lock') ?>
      </td>
    </tr>

    <tr>
      <th>Old database</th>
      <td>
      <?= $this->database->formSelect('old_database_id', 
        [
        'model' => 'Database',
        'unselect' => true,
        'label' => array('name', 'hostname'),
        'label_separate' => ' : '
        ])
        ?>
      </td>
    </tr>
  </table>

