  <table class="table">

    <tr>
      <th><?= DATABASE_NAME ?></th>
      <td><?= $this->database->formInput('name') ?></td>
    </tr>

    <tr>
      <th><?= DATABASE_HOST ?></th>
      <td>
        <?= $this->database->formSelect('hostname', ['csv' => 'db_hosts']) ?>
      </td>
    </tr>
                 
    <tr>
      <th><?= DATABASE_USER ?></th>
      <td>
        <?= $this->database->formSelect('user_name', ['csv' => 'db_users']) ?>
      </td>
    </tr>
                 
    <tr>
      <th><?= DATABASE_PORT ?></th>
      <td>
        <?= $this->database->formSelect('port', ['csv' => 'db_ports']) ?>
      </td>
    </tr>

    <tr>
      <th>Delete Lock</th>
      <td>
        <?= $this->database->formCheckbox('is_lock') ?>
      </td>
    </tr>

  </table>

