<table class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th><?= DATABASE_NAME ?></th>
      <th><?= DATABASE_HOST ?></th>
      <th><?= DATABASE_USER ?></th>
      <th><?= DATABASE_PORT ?></th>
      <th>Delete Lock</th>
    </tr>
  </thead>

  <?php if ($this->database->values): ?> 

  <?php foreach ($this->database->values as $database): ?> 
  <tr>
    <td><?= $this->database->linkEdit([], $database) ?></td>
    <td>
      <?= $this->linkTo(['action' => 'tables'],
                        [
                        'label' => $database['name'],
                        'http_params' => ['database_id' => $database['id']]
                        ]
      ) ?>
    </td>
    <td><?= $database['hostname'] ?></td>
    <td><?= $database['user_name'] ?></td>
    <td><?= $database['port'] ?></td>
    <td><?= PwForm::activeLabelTag($database['is_lock']) ?></td>
  </tr>
  <?php endforeach ?> 

  <?php endif ?> 

</table>
