<h3>Model</h3>
<a href="<?= $this->urlFor(['action' => 'export_model', 'id' => $this->pw_params['id']]) ?>" onClick="return confirmPHPmodelOutput();">PHP
  Export</a>
<table>
  <tr>
    <th>
      <?= $this->linkTo(['controller' => 'model', 'action' => 'new'],
      [
      'label' => LABEL_ADD,
      'class' => 'btn btn-outline-primary',
      'http_params' => ['database_id' => $this->database['id']]
      ]
      ) ?>
    </th>
    <th>モデル坝</th>
    <th>relfilenode</th>
  </tr>

  <? if (is_array($this->models)): ?>

  <? foreach ($this->models as $key => $model): ?>
  <tr class="<?=tr_model($model) ?>">
    <td>
      <?= $this->linkTo(['controller' => 'model', 'action' => 'edit', 'id' => $model['id']],
        [
        'label' => LABEL_EDIT,
        'class' => 'btn btn-outline-primary',
        ]
      ) ?>
    <td>
        <?= $this->linkTo(['controller' => 'attribute', 'action' => 'list', 'id' => $model['id']],
        [
        'label' => $model['name'] ?>,
        'class' => 'btn btn-outline-primary',
        'http_params' => ['database_id' => $this->database['id']]
        ]
        ) ?>
    </td>
    <td>
      <? if ($model['relfilenode'] > 0): ?>
      <?=$model['relfilenode'] ?>
      <? else: ?>
      <a href="<?= $this->urlFor(['controller' => 'create_table', 'id' => $model['id']) ?>">Create Table</a>
      <? endif ?>
    </td>
  </tr>
  <? endforeach ?>

  <? endif ?>

</table>