<div class="card">
  <div class="card-header">
    <h4>カラム</h4>
  </div>
  <div class="card-block">
    <form action="<?= url_for('add_column') ?>" method="post">
      <div class="form-group row">
        <label for="" class="col-1 col-form-label">name</label>
        <input class="form-control col-3" type="text" name="name">
        <label for="" class="col-1 col-form-label">type</label>
        <input class="form-control col-1" type="text" name="name">
        <label for="" class="col-1 col-form-label">length</label>
        <input class="form-control col-1" type="text" name="name">
      </div>
    </form>
  </div>
  <div class="card-footer text-center">
    <input class="btn btn-primary" type="submit" value="<?= LABEL_ADD ?>">
    <input type="hidden" name="database_id" value="<?= $this->database['id'] ?>">
    <input type="hidden" name="table_name" value="<?= $this->pg_table['tablename'] ?>">
  </div>
</div>

<form action="<?= url_for('update_column_comment') ?>" method="post">
  <div class="card">
    <div class="card-header">
      <h4>カラム</h4>
    </div>

    <div class="card-block overflow-list">
      <table class="table">
        <tr>
          <th></th>
          <th>comment</th>
          <th>name</th>
          <th>type</th>
          <th>length</th>
          <th>attrelid</th>
          <th>attnum</th>
          <th>NOT NULL</th>
        </tr>
        <? foreach ($this->attributes as $attribute): ?>
        <tr>
          <td></td>
          <td nowrap="nowrap">
            <input class="form-control" type="text" name="comments[<?= $attribute['column_name'] ?>]" value="<?= $attribute['comment'] ?>">
          </td>
          <td><?= $attribute['column_name'] ?></td>
          <td><?= $attribute['udt_name'] ?></td>
          <td><?= $attribute['character_maximum_length'] ?></td>
          <td><?= $attribute['attrelid'] ?></td>
          <td><?= $attribute['attnum'] ?></td>
          <td><?= $attribute['attnotnull'] ?></td>
          <td><a class="btn btn-danger" href="<?= url_for('delete_column', array('column_name' => $attribute['column_name'])) ?>"><?= LABEL_DELETE ?></a></td>
        </tr>
      <? endforeach ?>
    </table>

    <div class="card-footer text-center">
      <div class="text-center">
        <input class="btn btn-primary" type="submit" value="<?= LABEL_UPDATE ?>">
        <input type="hidden" name="database_id" value="<?= $this->database['id'] ?>">
        <input type="hidden" name="table_name" value="<?= $this->pg_table['tablename'] ?>">
        <a href="<?= url_for('tables', $this->database['id']) ?>" class="btn btn-secondary action" action="closeColumns"><?= LABEL_BACK ?></a>
      </div>
    </div>

  </div>
</form>
