<? include('_header.phtml') ?>
<div id="database">
  <form id="" action="<?= $this->urlFor(['action' => 'update', 'id' => $this->database->value['id']]) ?>" method="post">

    <? include('_edit.phtml') ?>

    <input class="btn btn-primary" type="submit" value="<?=LABEL_UPDATE ?>">
    <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>

  </form>

  <? if ($this->database->value['id'] && !$this->database->value['is_lock']): ?>
  <form id="" action="<?= $this->urlFor(['action' => 'delete', 'id' => $this->database->value['id']]) ?>" method="post">
    <input class="btn btn-danger" type="submit" value="<?= LABEL_DELETE ?>">
  </form>
  <? endif ?>
</div>
