<div id="help-database" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Attributes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body alert alert-success">
        <dl>
          <dd>* If you want manage PostgreSQL on browser, please set the permission on pg_hba.conf, postgresql.conf.
          </dd>
          <dd>* project-manager need database '
            <?= DB_NAME ?>' by PostgreSQL 9.x. </dd>
        </dl>
      </div>
    </div>
  </div>
</div>