<div id="help-database" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Database</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body alert alert-success">
        <dl>
          <dd>* If you want manage PostgreSQL on browser, please set the permission on pg_hba.conf, postgresql.conf.
          </dd>
          <dd>
            * project-manager need database '<?= DB_NAME ?>' by PostgreSQL 9.x.
            <p>
              $ createdb project_manager
            </p>
          </dd>
          <dd>
            * setting define in php file
            <p>
            <?= DB_SETTING_FILE ?>
            </p>
          </dd>
        </dl>
        <pre>
define('DB_NAME', 'project_manager');
define('DB_HOST', 'localhost');
define('DB_USER', 'postgres');
define('DB_PORT', '5432');
define('DB_PASS', '');
        </pre>
      </div>
    </div>
  </div>
</div>