
<div id="import_database_window" class="pw-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Database Import</h5>
        <button type="button" class="close pw-modal-close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div id="import_list">
        </div>
      </div>
    </div>
  </div>
</div>
