
<?= PwForm::select(
        [
        'class' => 'pw-click form-control',
        'csv' => DB_HOSTS_CSV,
        'pw-controller' => 'database',
        'pw-action' => 'import_list', 
        ],
        $this->host) ?>
<table class="table">
<?php foreach ($this->pg_databases as $pg_database): ?>
<tr>
  <td><?= $pg_database['datname'] ?></td>
  <td>
    <form method="post" action="<?= $this->urlFor(['action' => 'import_database']) ?>">
      <?= PwForm::submit(LABEL_IMPORT) ?>
      <?= PwForm::hidden('database_name', $pg_database['datname']) ?>
      <?= PwForm::hidden('host', $this->host) ?>
    </form>
  </td>
</tr>
<?php endforeach ?>
</table>
