<? include('_header.phtml') ?>

<? include('help.phtml') ?>

<div>
  <?= $this->linkTo(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary']) ?>
  <?= PwForm::linkModal('#import-table', LABEL_IMPORT, 
    [
    'class' => 'btn btn-outline-primary btn-sm pw-click', 
    'pw-controller' => 'database',
    'pw-action' => 'import_list', 
    ]) ?>
  <?= PwForm::linkModal('#help-database', 'Help', ['class' => 'btn btn-outline-primary']) ?>
</div>
<? include('import_window.phtml') ?>

<? include('_list.phtml') ?>

<?= PwTag::javascript('controllers/DatabaseController') ?>