<? include('_header.phtml') ?>

<div class="alert alert-success">
  if you want create database's table, please add model on '<a href="<?= url_for('project/') ?>">Project</a>'.
</div>
<? if ($this->pg_classes): ?>
<div class="row">
  <? foreach ($this->pg_classes as $pg_class_id => $pg_class): ?>
  <div class="col-6">
    <div id="<?= $pg_class_id ?>" class="card">

      <div class="card-header">
        <div><?= $pg_class['tablename'] ?> : <?= $pg_class_id ?></div>
        <div><?= $pg_class['comment'] ?></div>
      </div>

      <div class="card-block">
        <dl>
          <? foreach ($pg_class['pg_attribute'] as $attnum => $pg_attribute): ?>
          <dd id="<?= $pg_class_id ?>-<?= $attnum ?>">
            <small><?= $pg_attribute['attname'] ?></small>
             : 
            <small><?= $pg_attribute['comment'] ?></small>
            
            <small>(<?= $pg_attribute['udt_name'] ?>)</small>
          </dd>
          <? endforeach ?>
      </dl>
    </div>

    <div class="card-block">
    <strong>constraint</strong>
        <dl>

          <? foreach ($pg_class['pg_constraint'] as $pg_constraint): ?>
          <? if ($pg_constraint['confkey']): ?>

          <? foreach ($pg_constraint['confkey'] as $foreign_attnum): ?>
          <dd>
          <small>
          <a href="#<?= $pg_constraint['confrelid'] ?>-<?= $foreign_attnum ?>"><?= $pg_constraint['conname'] ?></a>
          (<?= $this->pg_classes[$pg_constraint['confrelid']]['relname'] ?>
          :
          <?= $this->pg_classes[$pg_constraint['confrelid']]['pg_attribute'][$foreign_attnum]['attname'] ?>)
          </small>
          </dd>
          <? endforeach ?>

          <? else: ?>

          <? if ($pg_constraint['conkey']): ?>
          <? foreach ($pg_constraint['conkey'] as $attnum): ?>
          <dd>
          <small><?= $pg_constraint['conname'] ?></small>
          :
          <small><?= $this->pg_classes[$pg_constraint['conrelid']]['pg_attribute'][$attnum]['attname'] ?></small>
          </dd>
          <? endforeach ?>
          <? endif ?>

          <? endif ?>
          <? endforeach ?>
      </dl>

    </div>
  </div>
</div>
<? endforeach ?>
</div>
<? endif ?>

<?= TagHelper::javascript('controllers/DatabaseController') ?>