<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_params['id']]) ?>" method="post">

  <div class="card">

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>

    <div class="card-footer">
      <h4></h4>
      <div class="text-left">

        <?= PwForm::submit(LABEL_SAVE) ?>        
        <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
      </div>
    </div>

  </div>
</form>

<div class="card">
  <div class="card-footer">
    <div class="text-left">

      <?= $this->user_project_setting->confirmDelete() ?>
    </div>
  </div>
</div>
