<? include('_header.phtml') ?>
<form action="<?= $this->urlFor(['action' => 'update', 'id' => $this->pw_gets['id']]) ?>" method="post">

  <div class="card">

    <div class="card-block">

      <? include('form.phtml') ?>
    </div>

    <div class="card-footer">
      <div class="text-left">

        <?= PwForm::submit(LABEL_SAVE) ?>        
        <?= PwForm::linkButton(['action' => 'cancel'], ['label' => LABEL_BACK]) ?>
        <?= $this->user_project_setting->confirmDelete() ?>
      </div>
    </div>

  </div>
</form>
