
<table class="table">

    <tr>
      <th><?= LABEL_USER ?></th>
      <td>
          <?= $form = $this->user_project_setting->formSelect('user_id', [
                        'unselect' => true,
                        'label_separate' => '-',
                        'label' => ['login_name'],
                        'model' => 'User',
                        ]) ?>
          <?php if (!$from): ?>
          <div>
          Please, create user!!
          </div>
          <?= $this->linkTo(['controller' => 'user'], ['label' => 'create', 'class' => 'btn btn-primary']) ?>
          <?php endif ?>
      </td>
    </tr>

    <tr>
      <th>Project</th>
      <td>
          <?= $this->user_project_setting->formSelect('project_id', [
                        'unselect' => true,
                        'label_separate' => '-',
                        'label' => ['name'],
                        'model' => 'Project',
                        ]) ?>
      </td>
    </tr>

    <tr>
      <th>Local Path</th>
      <td>
          <?= $this->user_project_setting->formInput('project_path', ['class' => 'form-control']) ?>
      </td>
    </tr>

</table>

        