<? include('_header.phtml') ?>

<div class="pt-3">
  <?= FormHelper::linkButton(['action' => 'new'], ['label' => LABEL_ADD, 'class' => 'btn btn-primary'] ) ?>
  <? include('views/components/lib/sortable.phtml') ?>

</div>

<table id="sortable-table" class="table">
  <thead class="thead-default">
    <tr>
      <th>&nbsp;</th>
      <th>
        <?= LABEL_USERS ?>
      </th>
      <th>
        <?= LABEL_USER_PROJECT_SETTINGS_PROJECT_PATH ?>
      </th>
      <th>
        <?= LABEL_USER_PROJECT_SETTINGS_GROUP_NAME ?>
      </th>
    </tr>
  </thead>

  <? if ($this->user_project_setting->values): ?>
  <? foreach ($this->user_project_setting->values as $values): ?>
  <tr row-id="<?= $values['id'] ?>">
    <td>
      <?= FormHelper::linkButton('edit', $values['id'], ['label' => LABEL_EDIT]) ?>
    </td>
    <td>
      <?= $this->user->values[$values['user_id']][''] ?>
    </td>
    <td>
      <?= $values['project_path'] ?>
    </td>
    <td>
      <?= $values['group_name'] ?>
    </td>
  </tr>
  <? endforeach ?>
  <? endif ?>

</table>