<? include('_header.phtml') ?>

<div>
  <?= PwForm::linkModal('#add_project_path_window', LABEL_ADD) ?>
</div>

<? include('views/components/add_project_path_window.phtml'); ?>

<table class="table">
  <thead class="thead-default">
    <tr>
      <td></td>
      <td>Local project path</td>
      <td>project exists</td>
    </tr>
  </thead>
  <?php if (is_array($this->user_project_setting->values)): ?>
  <tbody>
    <?php foreach ($this->user_project_setting->values as $user_project_setting): ?>
    <tr>
      <td>
        <?= $this->linkTo(
        [ 'controller' => 'user_project_setting', 'action' => 'edit', 'id' => $user_project_setting['id'] ],
        [ 'class' => 'btn btn-outline-primary', 'label' => LABEL_EDIT] 
        ) ?>
      </td>
      <td><?= $user_project_setting['project_path'] ?></td>
      <td>
        <?php if (file_exists($user_project_setting['project_path'])): ?>
        <?php if (file_exists($user_project_setting['project_path']."app/")): ?><label class="badge badge-success">exists</label><? else: ?>
        <label class="badge badge-danger">not found php-work</label>
        <a class="btn btn-primary" href="<?= $this->urlFor(['action' => 'git_clone'], ['user_project_setting_id' => $user_project_setting['id']]) ?>">git clone php-work</a>
      <?php endif ?>
    <? else: ?>
    <label class="badge badge-danger">not exists</label>
    <a class="btn btn-primary" href="<?= $this->urlFor(['action' => 'git_clone'], ['user_project_setting_id' => $user_project_setting['id']]) ?>">git clone php-work</a>
  <?php endif ?>
</td>
</tr>
<?php endforeach ?>
<?php endif ?>
</tbody>
</table>
