<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>

<?= PwTag::stylesheet('bootstrap.min') ?>
<?= PwTag::stylesheet('font-awesome.min') ?>
<?= PwTag::stylesheet('default') ?>

<?= PwTag::javascript('jquery/jquery-1.11.1.min') ?>
<?= PwTag::javascript('jquery/jquery-ui.min') ?>

<?= PwTag::javascript('bootstrap/tether.min') ?>
<?= PwTag::javascript('bootstrap/bootstrap.min') ?>

<?= PwTag::javascript('default') ?>

</head>
<body>

  <div id="main" class="container">

    <?= $this->content_for_layout?>

  </div>

</body>
</html>