<html lang="ja">

<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>
</head>

<body>

  <div class="nav">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<?= $this->urlControllerFor('pw_admin') ?>">
          PwAdmin
        </a>
      </div>

    </div>
  </div>

  <div id="main" class="container">

    <?= $this->content_for_layout?>

  </div>

  <? include('views/components/error_message.phtml') ?>

</body>
</html>