<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>

  <script type="text/javascript">
    var project_name = '<?= PROJECT_ROOT ?>';
  </script>
</head>
<body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <div class="container">
      <ul class="nav nav-pills justify-content-left">
        <li class="nav-item">
          <a class="nav-link <?= cssClass('project', $this->params['controller'], 'active'); ?>" href="<?= url_for('project/') ?>">Project</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?= cssClass('database', $this->params['controller'], 'active'); ?>" href="<?= url_for('database/') ?>">Database</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?= cssClass('setting', $this->params['controller'], 'active'); ?>" href="<?= url_for('setting/') ?>">Setting</a>
        </li>
      </ul>
    </div>
  </nav>

  <div id="main" class="container">

    <?= $this->content_for_layout?>

  </div>

<? if ($this->errors): ?>
<? include('views/components/error_dialog.phtml') ?>
<? endif ?>
</body>
</html>