<!DOCTYPE html>
<html lang="ja">
<head>
  <? include('components/meta.phtml') ?>
  <? include('components/stylesheet.phtml') ?>
  <? include('components/javascript.phtml') ?>
</head>
<body>

<div class="container-fluid">
  <div class="row">
  <? include('views/components/side_nav.phtml') ?>

  <div role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <?= $this->content_for_layout?>
  </div>

  </div>
</div>

<? include('views/components/php_export_window.phtml') ?>
<? include('views/components/sql_export_window.phtml') ?>

<? include('views/components/lib/pw_component.phtml') ?>
</body>
</html>