<div class="modal calendar-window">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="from-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <?= PwForm::input(
            [
              'id' => 'from-at',
              'name' => 'from_at',
              'class' => 'datetimepicker form-control',
              'value' => $this->app_date->from_at,
              'change_selector' => '#date_number',
            ]
          )
          ?>
          
          <?= $this->linkJs(
            [
              'label' => LABEL_RELOAD,
              'class' => 'pw-click btn btn-outline-primary',
              'icon_name' => 'redo-alt',
              'pw-controller' => $this->jsControllerName(),
              'pw-action' => 'list',
            ]
          )
          ?>
      </div>
      <div class="modal-footer">
          <?= $this->linkJs(
            [
            'id' => 'input_date',
            'class' => 'pw-click btn btn-primary',
            'label' => LABEL_OK,
            ]
          ) ?>
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= LABEL_CLOSE ?></button>
      </div>
    </div>
  </div>
</div>